// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// Defines values for ErrorDetailLocation.
const (
	ErrorDetailLocationBody   ErrorDetailLocation = "body"
	ErrorDetailLocationCookie ErrorDetailLocation = "cookie"
	ErrorDetailLocationHeader ErrorDetailLocation = "header"
	ErrorDetailLocationPath   ErrorDetailLocation = "path"
	ErrorDetailLocationQuery  ErrorDetailLocation = "query"
)

// Valid indicates whether the value is a known member of the ErrorDetailLocation enum.
func (e ErrorDetailLocation) Valid() bool {
	switch e {
	case ErrorDetailLocationBody:
		return true
	case ErrorDetailLocationCookie:
		return true
	case ErrorDetailLocationHeader:
		return true
	case ErrorDetailLocationPath:
		return true
	case ErrorDetailLocationQuery:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusStatus.
const (
	HealthStatusStatusOk HealthStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case HealthStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for MoneyCurrency.
const (
	MoneyCurrencyGHS MoneyCurrency = "GHS"
)

// Valid indicates whether the value is a known member of the MoneyCurrency enum.
func (e MoneyCurrency) Valid() bool {
	switch e {
	case MoneyCurrencyGHS:
		return true
	default:
		return false
	}
}

// Error The single error envelope used by every endpoint.
type Error struct {
	Error ErrorBody `json:"error"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	// Code Stable snake_case error code, e.g. `validation_failed`, `not_found`.
	//
	// Examples: validation_failed
	Code string `json:"code"`

	// Details Per-field problems, present for `validation_failed`.
	Details *[]ErrorDetail `json:"details,omitempty"`

	// Message Human-readable summary. Do not parse.
	//
	// Examples: Request validation failed
	Message string `json:"message"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Field Parameter name, or a JSON pointer into the body (e.g. `/items/0/qty`).
	//
	// Examples: /items/0/qty
	Field    *string             `json:"field,omitempty"`
	Location ErrorDetailLocation `json:"location"`

	// Message Examples: must be >= 1
	Message string `json:"message"`
}

// ErrorDetailLocation defines model for ErrorDetail.Location.
type ErrorDetailLocation string

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Status HealthStatusStatus `json:"status"`
}

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// Money An amount of money in the smallest currency unit (pesewas).
type Money struct {
	// Amount Integer pesewas. GHS 12.50 is `1250`.
	//
	// Examples: 1250
	Amount   int64         `json:"amount"`
	Currency MoneyCurrency `json:"currency"`
}

// MoneyCurrency defines model for Money.Currency.
type MoneyCurrency string

// PageMeta defines model for PageMeta.
type PageMeta struct {
	Limit int32 `json:"limit"`
	Page  int32 `json:"page"`

	// Total Total matching items across all pages.
	Total int64 `json:"total"`
}

// Limit defines model for Limit.
type Limit = int32

// Page defines model for Page.
type Page = int32

// BadRequest The single error envelope used by every endpoint.
type BadRequest = Error

// Forbidden The single error envelope used by every endpoint.
type Forbidden = Error

// InternalError The single error envelope used by every endpoint.
type InternalError = Error

// NotFound The single error envelope used by every endpoint.
type NotFound = Error

// Unauthorized The single error envelope used by every endpoint.
type Unauthorized = Error

// Unavailable The single error envelope used by every endpoint.
type Unavailable = Error

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealthz Liveness probe
	// (GET /healthz)
	GetHealthz(c *gin.Context)
	// GetReadyz Readiness probe
	// (GET /readyz)
	GetReadyz(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealthz(c)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetReadyz(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealthz)
	router.GET(options.BaseURL+"/readyz", wrapper.GetReadyz)
}

type BadRequestJSONResponse Error

type ForbiddenJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type UnavailableJSONResponse Error

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse HealthStatus

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyzRequestObject struct {
}

type GetReadyzResponseObject interface {
	VisitGetReadyzResponse(w http.ResponseWriter) error
}

type GetReadyz200JSONResponse HealthStatus

func (response GetReadyz200JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyz503JSONResponse struct{ UnavailableJSONResponse }

func (response GetReadyz503JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealthz Liveness probe
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// GetReadyz Readiness probe
	// (GET /readyz)
	GetReadyz(ctx context.Context, request GetReadyzRequestObject) (GetReadyzResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(ctx *gin.Context) {
	var request GetHealthzRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadyz operation middleware
func (sh *strictHandler) GetReadyz(ctx *gin.Context) {
	var request GetReadyzRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadyz(ctx, request.(GetReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadyz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetReadyzResponseObject); ok {
		if err := validResponse.VisitGetReadyzResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFfbbuS4Ef2VApMHG1Cr1XYcLBQEgWcmvixmNsbYizy4jVG1VGpxLZEakmq7x+h/D4pU39vjRZCdvOlC",
	"Vh3W5dThi8h102pFylmRvogWDTbkyPi3j7KRjh8KsrmRrZNaiVTc4JTAym8Ui0hI/vK1IzMXkVDYkEhF",
	"7fdFwuYVNRgMlNjVTqQnSSRKbRp0IhVSudMTEYkGn2XTNSI9SyLRSBVeRpFw85bCOpqSEYtF5J3vQxoN",
	"JmipgJahqa6ZkHkNHC85jG10CNr30CwiYci2Wlny8XqHxWf62pH1Qcu1cqT8I7ZtLXNksMPfLCN+2QDw",
	"Z0OlSMWfhutcDMNfO/ynMbp3tX3iu4rABGcgLTRYM3YqQBsoUdYWZljLwvuMxSISF9pMZFGQ+uOxnXeu",
	"IuXYKhURTDoHSjvAutZPVIDTUGhwlbQe2LVyZBTWwdwfDu5XRc8t5Y4KsGRmZIB4qYfyi3YXulPFj0qf",
	"1Z3JCQpN1keInqV1HsmvCjtXaSO/0Q9A80laK9U0AnpupQlFJJUvIMgNFZxMrO0S2QxljZOafkAlQUEt",
	"qYJUPucy79bOY08HvQV2sKqf/Ujz4WoKiQZSM6p1S9AxY0zmQDMycyBVtFoqx7zRGt2ScTK0NS0Nv3mE",
	"d7qYi0ALXzsOpEjv++0PK/7Qk98odxzK9Z70ZcdnrosDNHfr+ORgFT7Slxzt8ki8OgKKpzFk67b/wjxA",
	"RRZBprT7UnJlZ3w8esamrdnRvdhbvoHUOiPVVPisOOaUA7OAzKCUVBfQGj2pqbERtIYsKQelNofgeGJ2",
	"1NjfFdIP3rNYrEChMTjn94asPTgMrroG1cAQFiFaXdOgmcfwQfsma9FY2g1Dz9sbpAmvhmMnvz5Vaziv",
	"Jro/yV6qffgOTdl+FAMProhbEuHn23/9Ar5MiTvUMY0STHQxh6OQ/qEP7TAZfnXz7Hj3mJt/Dya61qGB",
	"fd0rHnz3okVXiWg1RyvCgoyIRK71o+Sjs/+D1jZStImi6ayDCcG4S5JT+juM3g7yCtf3A31FWLvq1qHr",
	"7H6k7er78mj68W3X/a5D7j5pRfP91J0rwEZ3yoEuoeE1IJXPlG2wrrnO8s4YT2qdkg6OWrL0hPZ4n3yC",
	"oX0f10GFQL8zhsurWxidxGcJ82Q2OjlLdnudvz1sa5y//kXs65pILNFthury6vbtWPVoNywcChtruE/k",
	"cD9D9VJx/vcaMQoK76CN725z2mF9YH7wZ2jQ5ZVUU/ANBJgbbS0rGi85LUd6L64rd8lBJbsZt16ULoVz",
	"gLIfOh54lHdGuvktk2QI2oTQkGHRtX67WIL5+d93YneqXkhDrJfh+gM4/UgqXgpidhYMrOuicq4Ns1mq",
	"Ui9nPuY+T72ovkDTSFvBZYUKxd4Yf6+VM5i7QSmNdXB1d3cD5zfXfkL0W2O4q6SFUtbEBeybJagjXYIz",
	"navSsbrUS83G2CygIZiSIsNCE0qjG+Buyhp8XP/IjiNAVSzVst81Vj3RUwE4RalYRTtAB6ZTTjYUj9VY",
	"vddqRorPYNOxGvTsuypYb9WzIqzvTR5Tjg3V79GymQF8CgzA5fKEcwtyu3XhKPMr4tA82TG0dWchW7ZQ",
	"yq2deUt+jlgWLqAVrZRMCtnLOOiMsUjhZexn0lhEMF6yZXjpx/g/xmKxYIsAGa/MPDiwe+pCeuVXSjJ/",
	"g6y35BdXWyOWDXEsGpxDXqGahnN/lNatZJUFx0nJWm/iyOdqdOy3Zb7sMzgaDc6S4z5XrjMKsiVThONv",
	"3St2LSPslTWghey819F+fKTwzld3GD25X+UfiT34DsxJWU8f68OLVHwM3z9TObgxujWSHG7eKjc/cpcG",
	"zbHbGYBTI/Oudp3xnGIeybU15sTdwE3opKs3++n85lpEYkbGhkZK4lGcsAPdksJWilSc+k+Rn9KeDoaV",
	"H4Lf+HlKB0bHZx9cCydJAk8VNxx3W2t0TtZCjio0mW/TGN5XlD/y9WQtxWUgPO4DH9XrQqTiktxV73jn",
	"WnySJP+zm8LWgH/lXrU8ie84OaN4izhFev+wmaCPckaKl7OAJc4BTr1KsXPrqBEPvHnIpT7/vSGlMOwL",
	"dOjrEZV98tQALY+QJ+kqqeAELOVaFTYC7SoyT9ISnCWnB0P7Ofj/P0bWI+C7eygOZ7AsZe6vhGfJ6WvW",
	"V3CHm/fG7+WD/cg3ErK9fXsC3j8s2J4fE9b/3dHVRhddzi9wxKqyhoI8jTakPP1b0Ap46KXDoV9QaevS",
	"n5KfkmMRic7U/Uy06XCIrYzLfoBNK7F4WKHddbsqs0BvW2e08ZpI+kMuHhb/GQA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
