// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorDetailLocation.
const (
	ErrorDetailLocationBody   ErrorDetailLocation = "body"
	ErrorDetailLocationCookie ErrorDetailLocation = "cookie"
	ErrorDetailLocationHeader ErrorDetailLocation = "header"
	ErrorDetailLocationPath   ErrorDetailLocation = "path"
	ErrorDetailLocationQuery  ErrorDetailLocation = "query"
)

// Valid indicates whether the value is a known member of the ErrorDetailLocation enum.
func (e ErrorDetailLocation) Valid() bool {
	switch e {
	case ErrorDetailLocationBody:
		return true
	case ErrorDetailLocationCookie:
		return true
	case ErrorDetailLocationHeader:
		return true
	case ErrorDetailLocationPath:
		return true
	case ErrorDetailLocationQuery:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusStatus.
const (
	HealthStatusStatusOk HealthStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case HealthStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for MeRole.
const (
	MeRoleAdmin MeRole = "admin"
	MeRoleUser  MeRole = "user"
)

// Valid indicates whether the value is a known member of the MeRole enum.
func (e MeRole) Valid() bool {
	switch e {
	case MeRoleAdmin:
		return true
	case MeRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for MeSignupMethod.
const (
	MeSignupMethodEmail  MeSignupMethod = "email"
	MeSignupMethodPhone  MeSignupMethod = "phone"
	MeSignupMethodSocial MeSignupMethod = "social"
)

// Valid indicates whether the value is a known member of the MeSignupMethod enum.
func (e MeSignupMethod) Valid() bool {
	switch e {
	case MeSignupMethodEmail:
		return true
	case MeSignupMethodPhone:
		return true
	case MeSignupMethodSocial:
		return true
	default:
		return false
	}
}

// Defines values for MoneyCurrency.
const (
	MoneyCurrencyGHS MoneyCurrency = "GHS"
)

// Valid indicates whether the value is a known member of the MoneyCurrency enum.
func (e MoneyCurrency) Valid() bool {
	switch e {
	case MoneyCurrencyGHS:
		return true
	default:
		return false
	}
}

// Error The single error envelope used by every endpoint.
type Error struct {
	Error ErrorBody `json:"error"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	// Code Stable snake_case error code, e.g. `validation_failed`, `not_found`.
	//
	// Examples: validation_failed
	Code string `json:"code"`

	// Details Per-field problems, present for `validation_failed`.
	Details *[]ErrorDetail `json:"details,omitempty"`

	// Message Human-readable summary. Do not parse.
	//
	// Examples: Request validation failed
	Message string `json:"message"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Field Parameter name, or a JSON pointer into the body (e.g. `/items/0/qty`).
	//
	// Examples: /items/0/qty
	Field    *string             `json:"field,omitempty"`
	Location ErrorDetailLocation `json:"location"`

	// Message Examples: must be >= 1
	Message string `json:"message"`
}

// ErrorDetailLocation defines model for ErrorDetail.Location.
type ErrorDetailLocation string

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Status HealthStatusStatus `json:"status"`
}

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// Me The signed-in user's own view of their account. Never returned for other users.
type Me struct {
	CreatedAt   time.Time `json:"createdAt"`
	DisplayName *string   `json:"displayName,omitempty"`

	// Email Present when the Firebase account has an email.
	Email         *string            `json:"email,omitempty"`
	EmailVerified bool               `json:"emailVerified"`
	Id            openapi_types.UUID `json:"id"`

	// Phone E.164 phone number, present for phone sign-ins.
	//
	// Examples: +233241234567
	Phone          *string        `json:"phone,omitempty"`
	Role           MeRole         `json:"role"`
	SellerVerified bool           `json:"sellerVerified"`
	SignupMethod   MeSignupMethod `json:"signupMethod"`
	UpdatedAt      time.Time      `json:"updatedAt"`
}

// MeRole defines model for Me.Role.
type MeRole string

// MeSignupMethod defines model for Me.SignupMethod.
type MeSignupMethod string

// Money An amount of money in the smallest currency unit (pesewas).
type Money struct {
	// Amount Integer pesewas. GHS 12.50 is `1250`.
	//
	// Examples: 1250
	Amount   int64         `json:"amount"`
	Currency MoneyCurrency `json:"currency"`
}

// MoneyCurrency defines model for Money.Currency.
type MoneyCurrency string

// PageMeta defines model for PageMeta.
type PageMeta struct {
	Limit int32 `json:"limit"`
	Page  int32 `json:"page"`

	// Total Total matching items across all pages.
	Total int64 `json:"total"`
}

// UpdateMeRequest defines model for UpdateMeRequest.
type UpdateMeRequest struct {
	// DisplayName Leading/trailing whitespace is trimmed; must contain a non-space character.
	DisplayName string `json:"displayName"`
}

// Limit defines model for Limit.
type Limit = int32

// Page defines model for Page.
type Page = int32

// BadRequest The single error envelope used by every endpoint.
type BadRequest = Error

// Forbidden The single error envelope used by every endpoint.
type Forbidden = Error

// InternalError The single error envelope used by every endpoint.
type InternalError = Error

// NotFound The single error envelope used by every endpoint.
type NotFound = Error

// Unauthorized The single error envelope used by every endpoint.
type Unauthorized = Error

// Unavailable The single error envelope used by every endpoint.
type Unavailable = Error

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateMeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealthz Liveness probe
	// (GET /healthz)
	GetHealthz(c *gin.Context)
	// GetReadyz Readiness probe
	// (GET /readyz)
	GetReadyz(c *gin.Context)
	// GetMe Get my account
	// (GET /v1/me)
	GetMe(c *gin.Context)
	// UpdateMe Update my account
	// (PATCH /v1/me)
	UpdateMe(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealthz(c)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetReadyz(c)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// UpdateMe operation middleware
func (siw *ServerInterfaceWrapper) UpdateMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateMe(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealthz)
	router.GET(options.BaseURL+"/readyz", wrapper.GetReadyz)
	router.GET(options.BaseURL+"/v1/me", wrapper.GetMe)
	router.PATCH(options.BaseURL+"/v1/me", wrapper.UpdateMe)
}

type BadRequestJSONResponse Error

type ForbiddenJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type UnavailableJSONResponse Error

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse HealthStatus

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyzRequestObject struct {
}

type GetReadyzResponseObject interface {
	VisitGetReadyzResponse(w http.ResponseWriter) error
}

type GetReadyz200JSONResponse HealthStatus

func (response GetReadyz200JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyz503JSONResponse struct{ UnavailableJSONResponse }

func (response GetReadyz503JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMeRequestObject struct {
	Body *UpdateMeJSONRequestBody
}

type UpdateMeResponseObject interface {
	VisitUpdateMeResponse(w http.ResponseWriter) error
}

type UpdateMe200JSONResponse Me

func (response UpdateMe200JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateMe400JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateMe401JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealthz Liveness probe
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// GetReadyz Readiness probe
	// (GET /readyz)
	GetReadyz(ctx context.Context, request GetReadyzRequestObject) (GetReadyzResponseObject, error)
	// GetMe Get my account
	// (GET /v1/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// UpdateMe Update my account
	// (PATCH /v1/me)
	UpdateMe(ctx context.Context, request UpdateMeRequestObject) (UpdateMeResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(ctx *gin.Context) {
	var request GetHealthzRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadyz operation middleware
func (sh *strictHandler) GetReadyz(ctx *gin.Context) {
	var request GetReadyzRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadyz(ctx, request.(GetReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadyz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetReadyzResponseObject); ok {
		if err := validResponse.VisitGetReadyzResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(ctx *gin.Context) {
	var request GetMeRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateMe operation middleware
func (sh *strictHandler) UpdateMe(ctx *gin.Context) {
	var request UpdateMeRequestObject

	var body UpdateMeJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateMe(ctx, request.(UpdateMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdateMeResponseObject); ok {
		if err := validResponse.VisitUpdateMeResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFlpb+M40v4rBb4vsAlWlu0cswMNFotMTx8ZdHobnZ7dD+1gREtlixOJVJNUEk/g/76oomTLttLpXczx",
	"zZLIYp1PPUU/isxUtdGovRPJo6illRV6tPz0VlXK048cXWZV7ZXRIhHv5RLBqV8xFpFQ9OZzg3YlIqFl",
	"hSIRJe+LhMsKrGQQsJBN6UVyMonEwthKepEIpf3piYhEJR9U1VQiOZ9EolI6PEwj4Vc1hnW4RCvW64gP",
	"P1RpOppLhznUpJpuqjnap5SjJcO6TYdU+5I260hYdLXRDtlf38v8A35u0LHTMqM9av4p67pUmSRlx784",
	"0vixp8D/W1yIRPzfeBuLcfjqxi+tNe1RuxZ/LBBsOAyUg0qWpDvmYCwspCod3MlS5XxmLNaReGXsXOU5",
	"6t9ft4vGF6g9ScU8gnnjQRsPsizNPebgDeQGfKEcK3apPVotyyDud1fuJ40PNWYec3Bo79AC0lJW5Z3x",
	"r0yj8z8qfM40NkPIDTr2ED4o51mTn7RsfGGs+hX/AG2ulHNKLyPAh1rZkERKcwJBZjGnYMrSdZrdSVXK",
	"eYl/QCZBjjXqHHW2ojRvtofHDAetBDpgkz+HnibjSgyBBtR3WJoaoSHEmK8A79CuAHVeG6U94UZtTY3W",
	"q1DW2Al+1oTvTb4SARY+N+RIkXxqt99s8MPMf8HMkyu3e5LHvTMzkw/A3LUny8FpeYs/Z9J1JtHqCDBe",
	"xpBuy/5nwgHM0whSbfzPC8rslMzDB1nVJR30SRws72nqvFV6KTgqnjBloBegHS0UljnU1sxLrFwEtUWH",
	"2sPC2CF1GJg9Vu6rXPoDnyzWG6WktXJFzxU6N9gM3jSV1COLMg/eaqpK2lUMPxguslpah/tuaHG7B5rw",
	"pDv24suh2qrzZKBbSw5Cze4b6rJtKwZqXBGVpIQfr//5DjhNkSrUE4wizE2+gqMQ/jG7djwZf/ar9Hjf",
	"zP7XwUCXJhQw572mxvdJ1NIXItr00QJljlZEIjPmVpHpdP6gtF6I+lpUjfMwR5g1k8kp/h2mzzt5o9eX",
	"Hf0GZemLay994w497TbvO9PM7fNHt7uGjrvCp/BmqTEfKU0YY//iwNxruFN4D2ZBEVMWZJaZRvsY3hH8",
	"gEXfWI05F43xBVre6g7RKLNIbfWCIXfDV3LpceRVhWKjZq96latLuXrHBOjx8DtWbWLuZWBbx/cFas6z",
	"V8oi8axOeSikA6mB98dDJ/OXf6FVCxX6WLtibkyJUtMSle8Y0jQqH5JUF0YPePtlPP3mDPhjy/t28Sd8",
	"oXiMlHb75fDXk9PTk7PpyenZ+Td/G8xga0rsJwwFRURC5pXSgxscliXaL5tM6jT1FfrC5H3hzmRKlqIL",
	"SGf00DFNnf93WbCX1CrvjtmouqdXa/uBRVEvA/t6DNaH0bg6DNqFBllxApkFVLQGVMgwV8myJBzOGmu5",
	"6TdaeTiq0eG9dMeH5RAEHZ5xGVg6tDtjeP3mGqYn8fmEeEQ6PTmf7PdCenezOwN8cyYOeX8kOu36wXv9",
	"5vp5LGm17UkYchvNOFfo5SGCld1E9r/PUFGYgAZlfHGbN14OoMRHeg2V9Fmh9BK4wYDMrHGOGD+PZFx4",
	"B37dHDcZnPT6fmuHtm6wDKoMue4nzscr7M1hMs8V6SrL9z1fLmTpcD+Z9oBy19C3KHOll2NvpSrJ1PtC",
	"eXS1zJBSyltVVZh/B9zdiBZLpUGCNnoUFmWFtDLzYTSt5MNb1EtfiOTbELHucUoR8h4tHTqbXT9by32t",
	"D33CmJQ1VvnVNRGrYOkcpUVLg9r26VUXoB///VHsM/EN9l/+AN7coo67IZrBjQVsNS28rwOfV3phujlB",
	"ZhyQdhB/JW2lXAGvC6mlOKD+L4z25K7RQlnn4c3Hj+/h4v0lo3q7NYaPhXKwUGWIAAFImKiozdrGF8lM",
	"vzbdnEe6OZAWYYkaLeEWLKypgBAmreTt9kN6HIHUeTdh866Zbskh5iCXUmnnaaf0YBtNoBvP9Ey/MPoO",
	"NdngkpketYxtk2UslZkUbO9aWKdMVli+kI7EjOAqoCKV0L1cOVC7cAZHKa+IA6Ckx1CXjYO0g5WE4C5l",
	"Scw9HbEJoFbYTT8JpI+zMJvMRAKPM+axMxHBrGNY4aGl/v+YifWaJAKktDJl5cAdTCSKp8WFQvsdpK0k",
	"Xlzs0HISRL6o5IoKQy+D3W+V85tRzIGnoKQ1izjiWE2PeVvKUJDC0XR0PjluY0UUCtIOPYP5O3cR+5Il",
	"HKQ1SAfpRTt7M+VM4HvO7kBXM17FPzG44yWPjxRgXg5taTpKjkaX6PhXjlkp6W3aVWMCn27SGLrZm0QN",
	"jN98XEDSJfqQ47JCOJtMIW16twTpJrRsd/owWoQqGVEfT4ApSwpGE2PbartFx3K1VZ2O4Q2kFe2Ho7PJ",
	"KaSL7hIpDST1Xjk8pjLEzWWKXhiboQN8kJkvV3BfSFabJLkas40n4plmSM9QO4bbbeYQ2ob3H3AxIti2",
	"Cr3sX+P1XxLEhSFvH1ZALq3KmtI3lpuUvUVflwTGF+8vmbEqX/bB6OL9pYjEHVoXUGgST+MJHWBq1LJW",
	"IhGn/IpBumAsHRc8dfxKv5c4wEU+cGY6OJlMqGmUyP6trckoOTKpg/MY42J4UWB260Cb7d2HCh10E7XL",
	"XCTiNfo37cF795Ank8lvdjWzM1E9cZHVWcJwpe66q5k2z0Xy6aYfoLfqDjUtpxsDZqpyyWzcrZzHStzQ",
	"5jHhxOprXdrOJ7n0Mswn2t0zrkLNjVr5Qmk4AYeZ0bmLtskL55PTQdd+COf/iZ5lDeiyNCSHt3KxUBnf",
	"wZ1PTp+SvlF33L+o+1I8PjCveTYgd9Nxhc/Gww9Nv5tZl5IltPOMAE0uPNoeCM90O6hBGDEIOANKHITn",
	"Cn/P0FzhU6m+axsH42wy/apgbO9z1zuA9Ro9VKvOST33E51juu6z4tDjgek6wFyFHlxbw0yI75NcDC9p",
	"uuPOGIZgaREqqeWSruALa5plsfH8YQl0RFoEronOdxeVv4mH93n6epfUetvg+k8JcDvQ9sM7eT68vX9+",
	"foOMCM75QlLslfMunf90s6b65nbs+Ov+tY7Jm4we4Iiu1UrIkYlDhZq5rCOSQAw+GY95QWGcT76dfDs5",
	"FpFobNkSfJeMx7JWccsz4mUh1jcbTQ/Gpw72A1fbwRwXbxt7Czrr6Ksv1jp42cqoUKxv1v8ZAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
