// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorDetailLocation.
const (
	ErrorDetailLocationBody   ErrorDetailLocation = "body"
	ErrorDetailLocationCookie ErrorDetailLocation = "cookie"
	ErrorDetailLocationHeader ErrorDetailLocation = "header"
	ErrorDetailLocationPath   ErrorDetailLocation = "path"
	ErrorDetailLocationQuery  ErrorDetailLocation = "query"
)

// Valid indicates whether the value is a known member of the ErrorDetailLocation enum.
func (e ErrorDetailLocation) Valid() bool {
	switch e {
	case ErrorDetailLocationBody:
		return true
	case ErrorDetailLocationCookie:
		return true
	case ErrorDetailLocationHeader:
		return true
	case ErrorDetailLocationPath:
		return true
	case ErrorDetailLocationQuery:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusStatus.
const (
	HealthStatusStatusOk HealthStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case HealthStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for MeRole.
const (
	MeRoleAdmin MeRole = "admin"
	MeRoleUser  MeRole = "user"
)

// Valid indicates whether the value is a known member of the MeRole enum.
func (e MeRole) Valid() bool {
	switch e {
	case MeRoleAdmin:
		return true
	case MeRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for MeSignupMethod.
const (
	MeSignupMethodEmail  MeSignupMethod = "email"
	MeSignupMethodPhone  MeSignupMethod = "phone"
	MeSignupMethodSocial MeSignupMethod = "social"
)

// Valid indicates whether the value is a known member of the MeSignupMethod enum.
func (e MeSignupMethod) Valid() bool {
	switch e {
	case MeSignupMethodEmail:
		return true
	case MeSignupMethodPhone:
		return true
	case MeSignupMethodSocial:
		return true
	default:
		return false
	}
}

// Defines values for MoneyCurrency.
const (
	MoneyCurrencyGHS MoneyCurrency = "GHS"
)

// Valid indicates whether the value is a known member of the MoneyCurrency enum.
func (e MoneyCurrency) Valid() bool {
	switch e {
	case MoneyCurrencyGHS:
		return true
	default:
		return false
	}
}

// Error The single error envelope used by every endpoint.
type Error struct {
	Error ErrorBody `json:"error"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	// Code Stable snake_case error code: `bad_request`, `validation_failed`,
	// `unauthorized`, `reauth_required`, `forbidden`, `not_found`,
	// `method_not_allowed`, `rate_limited`, `turnstile_failed`,
	// `internal_error`, `unavailable`. `reauth_required` means the
	// sign-in is too old for a step-up operation: sign the user in
	// again and retry.
	//
	//
	// Examples: validation_failed
	Code string `json:"code"`

	// Details Per-field problems, present for `validation_failed`.
	Details *[]ErrorDetail `json:"details,omitempty"`

	// Message Human-readable summary. Do not parse.
	//
	// Examples: Request validation failed
	Message string `json:"message"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Field Parameter name, or a JSON pointer into the body (e.g. `/items/0/qty`).
	//
	// Examples: /items/0/qty
	Field    *string             `json:"field,omitempty"`
	Location ErrorDetailLocation `json:"location"`

	// Message Examples: must be >= 1
	Message string `json:"message"`
}

// ErrorDetailLocation defines model for ErrorDetail.Location.
type ErrorDetailLocation string

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Status HealthStatusStatus `json:"status"`
}

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// Me The signed-in user's own view of their account. Never returned for other users.
type Me struct {
	CreatedAt   time.Time `json:"createdAt"`
	DisplayName *string   `json:"displayName,omitempty"`

	// Email Present when the Firebase account has an email.
	Email         *string            `json:"email,omitempty"`
	EmailVerified bool               `json:"emailVerified"`
	Id            openapi_types.UUID `json:"id"`

	// Phone E.164 phone number, present for phone sign-ins.
	//
	// Examples: +233241234567
	Phone          *string        `json:"phone,omitempty"`
	Role           MeRole         `json:"role"`
	SellerVerified bool           `json:"sellerVerified"`
	SignupMethod   MeSignupMethod `json:"signupMethod"`
	UpdatedAt      time.Time      `json:"updatedAt"`
}

// MeRole defines model for Me.Role.
type MeRole string

// MeSignupMethod defines model for Me.SignupMethod.
type MeSignupMethod string

// Money An amount of money in the smallest currency unit (pesewas).
type Money struct {
	// Amount Integer pesewas. GHS 12.50 is `1250`.
	//
	// Examples: 1250
	Amount   int64         `json:"amount"`
	Currency MoneyCurrency `json:"currency"`
}

// MoneyCurrency defines model for Money.Currency.
type MoneyCurrency string

// PageMeta defines model for PageMeta.
type PageMeta struct {
	Limit int32 `json:"limit"`
	Page  int32 `json:"page"`

	// Total Total matching items across all pages.
	Total int64 `json:"total"`
}

// UpdateMeRequest defines model for UpdateMeRequest.
type UpdateMeRequest struct {
	// DisplayName Leading/trailing whitespace is trimmed; must contain a non-space character.
	DisplayName string `json:"displayName"`
}

// Limit defines model for Limit.
type Limit = int32

// Page defines model for Page.
type Page = int32

// BadRequest The single error envelope used by every endpoint.
type BadRequest = Error

// Forbidden The single error envelope used by every endpoint.
type Forbidden = Error

// InternalError The single error envelope used by every endpoint.
type InternalError = Error

// NotFound The single error envelope used by every endpoint.
type NotFound = Error

// TooManyRequests The single error envelope used by every endpoint.
type TooManyRequests = Error

// Unauthorized The single error envelope used by every endpoint.
type Unauthorized = Error

// Unavailable The single error envelope used by every endpoint.
type Unavailable = Error

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateMeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealthz Liveness probe
	// (GET /healthz)
	GetHealthz(c *gin.Context)
	// GetReadyz Readiness probe
	// (GET /readyz)
	GetReadyz(c *gin.Context)
	// GetMe Get my account
	// (GET /v1/me)
	GetMe(c *gin.Context)
	// UpdateMe Update my account
	// (PATCH /v1/me)
	UpdateMe(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealthz(c)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetReadyz(c)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// UpdateMe operation middleware
func (siw *ServerInterfaceWrapper) UpdateMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateMe(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealthz)
	router.GET(options.BaseURL+"/readyz", wrapper.GetReadyz)
	router.GET(options.BaseURL+"/v1/me", wrapper.GetMe)
	router.PATCH(options.BaseURL+"/v1/me", wrapper.UpdateMe)
}

type BadRequestJSONResponse Error

type ForbiddenJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type TooManyRequestsResponseHeaders struct {
	RetryAfter          *int
	XRateLimitLimit     *int
	XRateLimitRemaining *int
	XRateLimitReset     *int
}
type TooManyRequestsJSONResponse struct {
	Body Error

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedJSONResponse Error

type UnavailableJSONResponse Error

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse HealthStatus

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyzRequestObject struct {
}

type GetReadyzResponseObject interface {
	VisitGetReadyzResponse(w http.ResponseWriter) error
}

type GetReadyz200JSONResponse HealthStatus

func (response GetReadyz200JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyz503JSONResponse struct{ UnavailableJSONResponse }

func (response GetReadyz503JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response GetMe429JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	if response.Headers.XRateLimitLimit != nil {
		w.Header().Set("X-RateLimit-Limit", fmt.Sprint(*response.Headers.XRateLimitLimit))
	}
	if response.Headers.XRateLimitRemaining != nil {
		w.Header().Set("X-RateLimit-Remaining", fmt.Sprint(*response.Headers.XRateLimitRemaining))
	}
	if response.Headers.XRateLimitReset != nil {
		w.Header().Set("X-RateLimit-Reset", fmt.Sprint(*response.Headers.XRateLimitReset))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMeRequestObject struct {
	Body *UpdateMeJSONRequestBody
}

type UpdateMeResponseObject interface {
	VisitUpdateMeResponse(w http.ResponseWriter) error
}

type UpdateMe200JSONResponse Me

func (response UpdateMe200JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateMe400JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateMe401JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response UpdateMe429JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	if response.Headers.XRateLimitLimit != nil {
		w.Header().Set("X-RateLimit-Limit", fmt.Sprint(*response.Headers.XRateLimitLimit))
	}
	if response.Headers.XRateLimitRemaining != nil {
		w.Header().Set("X-RateLimit-Remaining", fmt.Sprint(*response.Headers.XRateLimitRemaining))
	}
	if response.Headers.XRateLimitReset != nil {
		w.Header().Set("X-RateLimit-Reset", fmt.Sprint(*response.Headers.XRateLimitReset))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealthz Liveness probe
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// GetReadyz Readiness probe
	// (GET /readyz)
	GetReadyz(ctx context.Context, request GetReadyzRequestObject) (GetReadyzResponseObject, error)
	// GetMe Get my account
	// (GET /v1/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// UpdateMe Update my account
	// (PATCH /v1/me)
	UpdateMe(ctx context.Context, request UpdateMeRequestObject) (UpdateMeResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(ctx *gin.Context) {
	var request GetHealthzRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadyz operation middleware
func (sh *strictHandler) GetReadyz(ctx *gin.Context) {
	var request GetReadyzRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadyz(ctx, request.(GetReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadyz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetReadyzResponseObject); ok {
		if err := validResponse.VisitGetReadyzResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(ctx *gin.Context) {
	var request GetMeRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateMe operation middleware
func (sh *strictHandler) UpdateMe(ctx *gin.Context) {
	var request UpdateMeRequestObject

	var body UpdateMeJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateMe(ctx, request.(UpdateMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdateMeResponseObject); ok {
		if err := validResponse.VisitUpdateMeResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFp7b9y2sv8qA94LXBt3n370tFsUB06aVxGnge2cHCBrWLQ0u2ItkQpJ2d4G+90PZihptSvZTg+a9h9j",
	"JZHD4Tx+/M3QX0Rs8sJo1N6J2ReRokzQ8s9/D8+kx7cqV37If+llgi62qvDKaDETz0rrPMSykLHyKzAL",
	"8ClCRoPBp9KDLIpMYTISA+HiFHNJMvyqQDETSntcohXr9WBrrTPMpdJKL7vrneHnEp13kOHCwzUujK2W",
	"U3r5Bxdx2LOhc4yNThyU2qustRnlYFFm2QosFhlq5dInN7UeiEJamaOv7PmADd/LJYJTvyPJU/Tmc4l2",
	"JQZCy5xEsgZbayW4kGXmxexgMhALY3Ppw9KHB2Igcnmv8jIXs+PJQORKh4fpoM8ktHhXpenwWjpMoCDV",
	"dJlfo31IORrSr9u0T7XHtFkPhEVXGO2Q7fVMJpW/6Sk22qPmnxxUsSRlx7850vhLS4H/tbgQM/E/401g",
	"j8NXN35hramW2t7xRYpgw2Lk61xmpDsmYCwspMoc3MpMJbzmSKwH4qWx1ypJUH973U5Kn6L2JBWTAVyX",
	"HrTxILPM3GEC3kBiwKfKsWJvtEerZRbEfXPlPmi8LzD2mIBDe4sWkIayKu+Mf2lKnfxV7nOmtDFCYtCx",
	"hfBeOc+aXBhzKvWqho9vrxABTQUdeB8jJpiM4Ay9XYFceLQQ8cPwhB4icAF2KMlaANwa8hRSySZ671SW",
	"wTXW4fGHQLFBqL49V4qNuxMew++vlbSZ9BBQf70kmsA++aBl6VNj1e/4FwThqXJO6eUA8L5QNmCH0owb",
	"EFtMKIdlFrL0g5a3UmXyOsO/AEAgwQJ1gjpegaKQaRYfcQxUEmiBBja6CUabyzDkN6C+xcwUCCUdFNcr",
	"wFu0K0CdFEZpT2FXWFOg9SqgOdaCn9zCM5OsRDgNPpdkSDH7VE2/bI4Nc/0bxhx6mzmzLztrxibpOd3O",
	"Pe0cnJY3eBVLV2+JRs8gupbJVZVM0QCiDe5f0UGASTSY66hsRRaNskjPV7XG9GpRnxD0oI2/WhAW8uwc",
	"fWqSK3pZpSnLkB6vGDPCsy+tdl5l2F5YVfB+xTrTsJY3o1FXE8hRakdUZq6dWuqh0hQD3hgwWQILY0GC",
	"81gMywLIeLzXGdBYmkUOpjiea7mUSoPUCVgCptFci4HAe5kXGZn7k+iYquUv522V3Al6OlB7iBDa4UJh",
	"lkBhzXWGuRtAYdGh9qxmjyuYlXjM3VcF1s+8slg3Sklr5Yqec3Sulwm9LnOphxZlEmKmzHNpVyP42fAJ",
	"U0jrcLRjhuqUaTEGeNAcO1HOAbtR58Fwr3bSCXg2Xx/FrHgoEGsbAPv8l/Nf3wEnK/vXG/b2tUlWsIej",
	"5QiiMZt2PBl/9qtof3eb7a+9js5MgDHOfk2s75MopE/FoCGRAb/FQMTG3CjaOq3fK63lorYWeemoEIB5",
	"OZkc4k8wfdrIjV6PG/o1ysyn51760nUt7Zr39dbMzdNLV7P6ljvFh1B3qTGhrKVE/D8H5k7DrcK7qtpS",
	"FmQcm1L7EbwjEKbsLK3GkNvGp2h5quticmyROOUJHzwNWU+kx6FXOYpGzVb2KldkcvWO2f+X7nfMq8Dc",
	"icAqj+9SDKjyUlmkIqNWHlLpQGrg+aO+lfnLv9CqhQqneTXi2pgMpaYhKtnaSFmqpE9SkRrdY+0Xo+l3",
	"R8Afq6JnG3/ClwpD3W46/P/B4eHB0fTg8Oj4u3/0RrA1GbYDhpwiBkImudK9ExxmGdrHt0zqlMUpHyht",
	"4c7ESmaidki96b5lyiL5Y1GwE9QqqZdpVN3Rq9p7Z0eDVgS29ejND6Nx1XXaiQaZcwCZBeQ0BlSIMJfL",
	"LEPnIS6tZepTauVhr0CHd9Ltd9MhCOqu8SbQZahmjuDV63OYHoyOJ6AcRNOD40m0Ew707nK7AP7uSHSL",
	"3oGotWs779Xr86expNK2JaHPbFTgn6KXXQTLarL/3zcQBqH875Xx6DRvvOxBiQt6Dbn0car0EviAARlb",
	"4xzVM9yP4MTr2LVZbtLb5mjbrepY1F2VoEqf6T5wPJ5iqwkhk0SRrjJ737LlQmYOd4NpByi3N/oWZaL0",
	"cuytVBlt9S5VHl0hY2RyZlWeY/Ij8OlGxQEzL9BGD8OgOJVWxj70ZXJ5/xb10qdi9n3wWP04JQ95j5YW",
	"nc/Pn8zlttZdmzAmxaVVfnVOxCrs9BqlRUtdis3Ty9pBv3y8ELv1SIP9b34Gb25QN0UqgxsL2Giael+E",
	"qkbphamrJRmzQ6ou1Etpc+VSeJVKLUWnAHputCdzDRfKOg+vLy7ew8n7N4zq1dQRXKTU5FNZ8AABSGgn",
	"0DFrS5/O5vqVqZscpJsDaRGWqNESbsHCmhwIYaJc3mw+RPuDijRXvUtpca4rcogJMK12nmZKD5bq+RxH",
	"cz3Xz42+RU17cLO5HlaMrYkylspMCjaNRtYpljlmz6UjMUM4DahIKXQnVw7UNpzBXsQjRgFQon0ostJB",
	"VMPKjOAuYknMPR2xCaCjsK4BZxB9mYcKbS5m8GXOPHYuBjCvGVZ4qKj/P+divSaJABGNjFg5cJ26THHN",
	"vFBof4SoksSD0y1aToLIFrlcUWLoZdj3W+V8U5A68OSUqGARe+yr6T5PixgKItibDo8n+3WBU1oNUY2e",
	"YftbjbhdyRI6YQ3SQXRS1YlVWfWMozvQ1ZhH8U8M5njBRXRThUGVmo6Co9QZOv6VYJxJehvV2TiDT5fR",
	"COoOBInqaULwcgFJl+hDjMsc4Wgyhe2KtnEt7zu6Hy5ClgzpHJ8BU5YIjAapW9pu0DFbbVSnZXgCaUXz",
	"Ye9octiujwNJvVMO9ykNsekk6oWxMTrAexn7bAV3dKXAlSyAKzBuLLGrZlXPzihzsatoo5uEhUWX1qSO",
	"5O41boy4kKZsjOBO+VRpOIZc6dKj24fbisTwJ+6/3VZ1BUmJU4xvRnBCQZ01pJHM7oK5O2U6ieGM+Pjx",
	"47AdaU3McIL9NBdKu3KxULFC7a+IRF7JzXBaX0QcAS5UdHFGA+FGmzsH3nQK+wBATfC0AoaEVDHjvGpF",
	"DUObinsChx2xaX66WdUXqruTe9QNLYKUlAssLvbJoMpB1fyAAi0bMWguk8SicwFFN+VQg6dFVeCMtgKV",
	"6CvLm7EtUDvl1S1GJC6gjVV0gNL04SY0eMoIfmWQr69/ZnB08AM7Z6tHE1y/1cmlJm91hQGxtHYFUadf",
	"GrwT9XY/o4BInX5mBHtVj3h/N9abNlEd7a3ofp6ZMllQisBFPazCpsCSK02aj8ML+hhBKMx/BAn5Jiws",
	"/hY6/UFCFcwTltFpVoX2UKZi1I4Z0AbMiQCF92e4GBKTsgq9bF8rtV8S6wh9l92THuTSqrjMfGmZN9ob",
	"9EVG/Ojk/RsuIpXP2vzg5P0bMRC3aF0gBpPRdDShBUyBWhZKzMQhv2LelDK9GYc4/Z1+L/vuDM/4sHBw",
	"MJkQjyMLp0hhHaOjKNABz5h2jOA5IYMDbTZNWRVIbROEbxIxE6/Qv64W3rkXO5hM/rSe8VaT44GLlXon",
	"zCDUbd0zro4eMft02XbQW3WLmoZzXpMP5JILZLdyHnNxSZPHdHSvvtakVcsgkV6GloF2d0x1oGDuHLD5",
	"oL5FGWzOEzieHPaa9iys/zdaljVgPObg8FYSpvPlwPHk8CHpjbrj9g3CY/4441LjSYfcTsc5PukP39eQ",
	"atpPFCyBYcfEMcJF14YXbfrPoep3oHxAiY57TvFbuuYUHwr17b2xM44m069yxuaiiSYd/PD0pN1LyfUW",
	"0L1CD/mqNm7LbVSZceXt47TrqVC0OsBEBTpdWMNFDbeG3QheUKOGT5nQz6KzIZdaLgnXU2vKZdp4rJs6",
	"dU0sQtmIztc3L3+KZ3ZL7vV2fUrn2/pvCYyqN9UOi8nTHm79B8PfGEnBqI8E0w58bFf0ny7XhCfMyB1/",
	"3e3smqSM6QH2qLOeQYJcO+SouZx1YDRQET8bj3lAapyffT/5frIvBqK0WVXju9l4LAs1qnjNaJmK9WWj",
	"aaeDUh8zoVzbwjg32hCJCuTWg6/urddwtpGRo1hfrv8zAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
