// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_events (actor_id, action, target_type, target_id, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, actor_id, action, target_type, target_id, metadata, created_at
`

type InsertAuditEventParams struct {
	ActorID    pgtype.UUID
	Action     string
	TargetType string
	TargetID   string
	Metadata   []byte
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
