// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCategoryChildren = `-- name: CountCategoryChildren :one
SELECT count(*) FROM categories WHERE parent_id = $1
`

// A listing's category must be a leaf (or a parent with no children).
func (q *Queries) CountCategoryChildren(ctx context.Context, parentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoryChildren, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAttribute = `-- name: DeleteAttribute :one
DELETE FROM category_attributes WHERE id = $1 AND category_id = $2 RETURNING id
`

type DeleteAttributeParams struct {
	ID         uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) DeleteAttribute(ctx context.Context, arg DeleteAttributeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteAttribute, arg.ID, arg.CategoryID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getCategoryAttribute = `-- name: GetCategoryAttribute :one
SELECT id, category_id, key, label, type, options, required, sort_order, created_at, updated_at FROM category_attributes WHERE id = $1 AND category_id = $2
`

type GetCategoryAttributeParams struct {
	ID         uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) GetCategoryAttribute(ctx context.Context, arg GetCategoryAttributeParams) (CategoryAttribute, error) {
	row := q.db.QueryRow(ctx, getCategoryAttribute, arg.ID, arg.CategoryID)
	var i CategoryAttribute
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Key,
		&i.Label,
		&i.Type,
		&i.Options,
		&i.Required,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, parent_id, name, slug, icon, listing_group, sort_order, is_active, created_at, updated_at FROM categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.ListingGroup,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, parent_id, name, slug, icon, listing_group, sort_order, is_active, created_at, updated_at FROM categories WHERE slug = $1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.ListingGroup,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAttribute = `-- name: InsertAttribute :one
INSERT INTO category_attributes (category_id, key, label, type, options, required, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (category_id, key) DO NOTHING
RETURNING id, category_id, key, label, type, options, required, sort_order, created_at, updated_at
`

type InsertAttributeParams struct {
	CategoryID uuid.UUID
	Key        string
	Label      string
	Type       string
	Options    []string
	Required   bool
	SortOrder  int32
}

// Returns no row when the key is taken on this category (409).
func (q *Queries) InsertAttribute(ctx context.Context, arg InsertAttributeParams) (CategoryAttribute, error) {
	row := q.db.QueryRow(ctx, insertAttribute,
		arg.CategoryID,
		arg.Key,
		arg.Label,
		arg.Type,
		arg.Options,
		arg.Required,
		arg.SortOrder,
	)
	var i CategoryAttribute
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Key,
		&i.Label,
		&i.Type,
		&i.Options,
		&i.Required,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCategory = `-- name: InsertCategory :one
INSERT INTO categories (name, slug, parent_id, icon, listing_group, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (slug) DO NOTHING
RETURNING id, parent_id, name, slug, icon, listing_group, sort_order, is_active, created_at, updated_at
`

type InsertCategoryParams struct {
	Name         string
	Slug         string
	ParentID     pgtype.UUID
	Icon         *string
	ListingGroup *string
	SortOrder    int32
}

// Returns no row when the slug is taken (callers map that to 409).
func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, insertCategory,
		arg.Name,
		arg.Slug,
		arg.ParentID,
		arg.Icon,
		arg.ListingGroup,
		arg.SortOrder,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.ListingGroup,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCategories = `-- name: ListActiveCategories :many
SELECT id, parent_id, name, slug, icon, listing_group, sort_order, is_active, created_at, updated_at FROM categories WHERE is_active ORDER BY sort_order, name
`

func (q *Queries) ListActiveCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listActiveCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Icon,
			&i.ListingGroup,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttributesByCategory = `-- name: ListAttributesByCategory :many
SELECT id, category_id, key, label, type, options, required, sort_order, created_at, updated_at FROM category_attributes WHERE category_id = $1 ORDER BY sort_order, key
`

func (q *Queries) ListAttributesByCategory(ctx context.Context, categoryID uuid.UUID) ([]CategoryAttribute, error) {
	rows, err := q.db.Query(ctx, listAttributesByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryAttribute{}
	for rows.Next() {
		var i CategoryAttribute
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Key,
			&i.Label,
			&i.Type,
			&i.Options,
			&i.Required,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryAndChildIDs = `-- name: ListCategoryAndChildIDs :many
SELECT c.id FROM categories c
WHERE c.slug = $1
   OR c.parent_id = (SELECT p.id FROM categories p WHERE p.slug = $1)
`

// A category filter on a parent slug must include its children (DOMAIN §9);
// on a child slug it returns just that child.
func (q *Queries) ListCategoryAndChildIDs(ctx context.Context, slug string) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCategoryAndChildIDs, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttribute = `-- name: UpdateAttribute :one
UPDATE category_attributes SET
  label = COALESCE($1, label),
  type = COALESCE($2, type),
  options = COALESCE($3, options),
  required = COALESCE($4, required),
  sort_order = COALESCE($5, sort_order)
WHERE id = $6 AND category_id = $7
RETURNING id, category_id, key, label, type, options, required, sort_order, created_at, updated_at
`

type UpdateAttributeParams struct {
	Label      *string
	Type       *string
	Options    []string
	Required   *bool
	SortOrder  *int32
	ID         uuid.UUID
	CategoryID uuid.UUID
}

// Scoped to the category: an attribute of another category reads as missing.
func (q *Queries) UpdateAttribute(ctx context.Context, arg UpdateAttributeParams) (CategoryAttribute, error) {
	row := q.db.QueryRow(ctx, updateAttribute,
		arg.Label,
		arg.Type,
		arg.Options,
		arg.Required,
		arg.SortOrder,
		arg.ID,
		arg.CategoryID,
	)
	var i CategoryAttribute
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Key,
		&i.Label,
		&i.Type,
		&i.Options,
		&i.Required,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET
  name = COALESCE($1, name),
  icon = COALESCE($2, icon),
  sort_order = COALESCE($3, sort_order),
  is_active = COALESCE($4, is_active)
WHERE id = $5
RETURNING id, parent_id, name, slug, icon, listing_group, sort_order, is_active, created_at, updated_at
`

type UpdateCategoryParams struct {
	Name      *string
	Icon      *string
	SortOrder *int32
	IsActive  *bool
	ID        uuid.UUID
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.Icon,
		arg.SortOrder,
		arg.IsActive,
		arg.ID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.ListingGroup,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCategoryAttribute = `-- name: UpsertCategoryAttribute :one
INSERT INTO category_attributes (category_id, key, label, type, options, required, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (category_id, key) DO UPDATE SET
  label = EXCLUDED.label, type = EXCLUDED.type, options = EXCLUDED.options,
  required = EXCLUDED.required, sort_order = EXCLUDED.sort_order
WHERE category_attributes.label IS DISTINCT FROM EXCLUDED.label
   OR category_attributes.type IS DISTINCT FROM EXCLUDED.type
   OR category_attributes.options IS DISTINCT FROM EXCLUDED.options
   OR category_attributes.required IS DISTINCT FROM EXCLUDED.required
   OR category_attributes.sort_order IS DISTINCT FROM EXCLUDED.sort_order
RETURNING id, category_id, key, label, type, options, required, sort_order, created_at, updated_at
`

type UpsertCategoryAttributeParams struct {
	CategoryID uuid.UUID
	Key        string
	Label      string
	Type       string
	Options    []string
	Required   bool
	SortOrder  int32
}

// Seed upsert with the same no-change guard as categories.
func (q *Queries) UpsertCategoryAttribute(ctx context.Context, arg UpsertCategoryAttributeParams) (CategoryAttribute, error) {
	row := q.db.QueryRow(ctx, upsertCategoryAttribute,
		arg.CategoryID,
		arg.Key,
		arg.Label,
		arg.Type,
		arg.Options,
		arg.Required,
		arg.SortOrder,
	)
	var i CategoryAttribute
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Key,
		&i.Label,
		&i.Type,
		&i.Options,
		&i.Required,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCategoryBySlug = `-- name: UpsertCategoryBySlug :one
INSERT INTO categories (name, slug, parent_id, icon, listing_group, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, icon = EXCLUDED.icon,
  listing_group = EXCLUDED.listing_group, sort_order = EXCLUDED.sort_order
WHERE categories.name IS DISTINCT FROM EXCLUDED.name
   OR categories.icon IS DISTINCT FROM EXCLUDED.icon
   OR categories.listing_group IS DISTINCT FROM EXCLUDED.listing_group
   OR categories.sort_order IS DISTINCT FROM EXCLUDED.sort_order
RETURNING id, parent_id, name, slug, icon, listing_group, sort_order, is_active, created_at, updated_at
`

type UpsertCategoryBySlugParams struct {
	Name         string
	Slug         string
	ParentID     pgtype.UUID
	Icon         *string
	ListingGroup *string
	SortOrder    int32
}

// Seed upsert: updates only when something changed (the WHERE guard keeps a
// repeat run from touching updated_at). Returns no row when unchanged.
func (q *Queries) UpsertCategoryBySlug(ctx context.Context, arg UpsertCategoryBySlugParams) (Category, error) {
	row := q.db.QueryRow(ctx, upsertCategoryBySlug,
		arg.Name,
		arg.Slug,
		arg.ParentID,
		arg.Icon,
		arg.ListingGroup,
		arg.SortOrder,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.ListingGroup,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
