// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkout.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listCommissionConfigs = `-- name: ListCommissionConfigs :many
SELECT id, category_id, rate_bps FROM commission_configs
`

type ListCommissionConfigsRow struct {
	ID         uuid.UUID
	CategoryID pgtype.UUID
	RateBps    int32
}

// Every category override plus the default row, for server-side commission
// resolution. DOMAIN §2.1 snapshots the resolved rate on each order.
func (q *Queries) ListCommissionConfigs(ctx context.Context) ([]ListCommissionConfigsRow, error) {
	rows, err := q.db.Query(ctx, listCommissionConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommissionConfigsRow{}
	for rows.Next() {
		var i ListCommissionConfigsRow
		if err := rows.Scan(&i.ID, &i.CategoryID, &i.RateBps); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuoteListings = `-- name: ListQuoteListings :many
SELECT l.id, l.seller_id, sp.business_name AS seller_name, l.title, l.unit,
       l.price_pesewas AS unit_price, l.quantity_available, l.min_order_qty,
       l.category_id, c.parent_id AS category_parent_id,
       (l.status = 'active' AND l.expires_at > $1::timestamptz)::bool AS active,
       l.offers_pickup, l.offers_seller_delivery, l.seller_delivery_fee_pesewas
FROM listings l
JOIN categories c ON c.id = l.category_id
JOIN seller_profiles sp ON sp.user_id = l.seller_id
WHERE l.id = ANY($2::uuid[])
`

type ListQuoteListingsParams struct {
	Now        time.Time
	ListingIds []uuid.UUID
}

type ListQuoteListingsRow struct {
	ID                       uuid.UUID
	SellerID                 uuid.UUID
	SellerName               string
	Title                    string
	Unit                     string
	UnitPrice                int64
	QuantityAvailable        int32
	MinOrderQty              int32
	CategoryID               uuid.UUID
	CategoryParentID         pgtype.UUID
	Active                   bool
	OffersPickup             bool
	OffersSellerDelivery     bool
	SellerDeliveryFeePesewas *int64
}

// The server-side snapshot a quote may use. Prices come only from this query:
// cart lines carry quantities, never prices. Active is evaluated against the
// caller's clock, which tests control; the pricing function itself stays pure.
func (q *Queries) ListQuoteListings(ctx context.Context, arg ListQuoteListingsParams) ([]ListQuoteListingsRow, error) {
	rows, err := q.db.Query(ctx, listQuoteListings, arg.Now, arg.ListingIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuoteListingsRow{}
	for rows.Next() {
		var i ListQuoteListingsRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.SellerName,
			&i.Title,
			&i.Unit,
			&i.UnitPrice,
			&i.QuantityAvailable,
			&i.MinOrderQty,
			&i.CategoryID,
			&i.CategoryParentID,
			&i.Active,
			&i.OffersPickup,
			&i.OffersSellerDelivery,
			&i.SellerDeliveryFeePesewas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
