// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: engagement.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bumpFavoriteCount = `-- name: BumpFavoriteCount :exec
UPDATE listings SET favorite_count = favorite_count + $2 WHERE id = $1
`

type BumpFavoriteCountParams struct {
	ID            uuid.UUID
	FavoriteCount int32
}

func (q *Queries) BumpFavoriteCount(ctx context.Context, arg BumpFavoriteCountParams) error {
	_, err := q.db.Exec(ctx, bumpFavoriteCount, arg.ID, arg.FavoriteCount)
	return err
}

const countFavoritesByUser = `-- name: CountFavoritesByUser :one
SELECT count(*) FROM favorites WHERE user_id = $1
`

func (q *Queries) CountFavoritesByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFavoritesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVisibleReviewsByListing = `-- name: CountVisibleReviewsByListing :one
SELECT count(*) FROM reviews WHERE listing_id = $1 AND hidden_at IS NULL
`

func (q *Queries) CountVisibleReviewsByListing(ctx context.Context, listingID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVisibleReviewsByListing, listingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFavorite = `-- name: DeleteFavorite :execrows
DELETE FROM favorites WHERE user_id = $1 AND listing_id = $2
`

type DeleteFavoriteParams struct {
	UserID    uuid.UUID
	ListingID uuid.UUID
}

// Idempotent remove: the caller drops the counter only when a row went away.
func (q *Queries) DeleteFavorite(ctx context.Context, arg DeleteFavoriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFavorite, arg.UserID, arg.ListingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFavorite = `-- name: GetFavorite :one
SELECT user_id, listing_id, created_at FROM favorites WHERE user_id = $1 AND listing_id = $2
`

type GetFavoriteParams struct {
	UserID    uuid.UUID
	ListingID uuid.UUID
}

func (q *Queries) GetFavorite(ctx context.Context, arg GetFavoriteParams) (Favorite, error) {
	row := q.db.QueryRow(ctx, getFavorite, arg.UserID, arg.ListingID)
	var i Favorite
	err := row.Scan(&i.UserID, &i.ListingID, &i.CreatedAt)
	return i, err
}

const getListingForFavorite = `-- name: GetListingForFavorite :one
SELECT id FROM listings WHERE id = $1
`

// Existence gate for favorites: any listing may be favourited, including
// inactive ones (they show flagged).
func (q *Queries) GetListingForFavorite(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getListingForFavorite, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT id, order_id, listing_id, seller_id, reviewer_id, rating, comment, hidden_at, created_at, updated_at FROM reviews WHERE id = $1
`

func (q *Queries) GetReviewByID(ctx context.Context, id uuid.UUID) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewByID, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ListingID,
		&i.SellerID,
		&i.ReviewerID,
		&i.Rating,
		&i.Comment,
		&i.HiddenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFavorite = `-- name: InsertFavorite :one
INSERT INTO favorites (user_id, listing_id)
VALUES ($1, $2)
ON CONFLICT (user_id, listing_id) DO NOTHING
RETURNING user_id, listing_id, created_at
`

type InsertFavoriteParams struct {
	UserID    uuid.UUID
	ListingID uuid.UUID
}

// Idempotent add: returns no row when already favourited. The caller bumps
// the counter only on a returned row, in the same transaction.
func (q *Queries) InsertFavorite(ctx context.Context, arg InsertFavoriteParams) (Favorite, error) {
	row := q.db.QueryRow(ctx, insertFavorite, arg.UserID, arg.ListingID)
	var i Favorite
	err := row.Scan(&i.UserID, &i.ListingID, &i.CreatedAt)
	return i, err
}

const insertReview = `-- name: InsertReview :one
INSERT INTO reviews (order_id, listing_id, seller_id, reviewer_id, rating, comment)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (order_id, listing_id, reviewer_id) DO NOTHING
RETURNING id, order_id, listing_id, seller_id, reviewer_id, rating, comment, hidden_at, created_at, updated_at
`

type InsertReviewParams struct {
	OrderID    uuid.UUID
	ListingID  uuid.UUID
	SellerID   uuid.UUID
	ReviewerID uuid.UUID
	Rating     int16
	Comment    *string
}

// Records a review. Returns no row when this reviewer already reviewed this
// listing in this order: the caller treats that as already_reviewed.
func (q *Queries) InsertReview(ctx context.Context, arg InsertReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, insertReview,
		arg.OrderID,
		arg.ListingID,
		arg.SellerID,
		arg.ReviewerID,
		arg.Rating,
		arg.Comment,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ListingID,
		&i.SellerID,
		&i.ReviewerID,
		&i.Rating,
		&i.Comment,
		&i.HiddenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFavoriteListings = `-- name: ListFavoriteListings :many
WITH active_promo AS (
  SELECT DISTINCT ON (listing_id) listing_id, tier, tier_rank
  FROM listing_promotions
  WHERE starts_at <= $2 AND ends_at > $2
  ORDER BY listing_id, tier_rank DESC
)
SELECT l.id, l.slug, l.title, l.price_pesewas, l.unit, l.region, l.district, l.item_state,
       l.published_at, c.slug AS category_slug, c.name AS category_name,
       p.tier AS promo_tier,
       COALESCE((SELECT m.key FROM listing_images li JOIN media_objects m ON m.id = li.media_id
         WHERE li.listing_id = l.id ORDER BY li.sort_order LIMIT 1), '') AS cover_key,
       sp.business_name AS seller_name, (sp.verification_status = 'verified') AS seller_verified,
       (l.status = 'active' AND l.expires_at > $2)::bool AS available
FROM listings l
JOIN favorites f ON f.listing_id = l.id
JOIN categories c ON c.id = l.category_id
JOIN seller_profiles sp ON sp.user_id = l.seller_id
LEFT JOIN active_promo p ON p.listing_id = l.id
WHERE f.user_id = $1
ORDER BY f.created_at DESC
LIMIT $4 OFFSET $3
`

type ListFavoriteListingsParams struct {
	UserID uuid.UUID
	Now    *time.Time
	Offset int32
	Limit  int32
}

type ListFavoriteListingsRow struct {
	ID             uuid.UUID
	Slug           string
	Title          string
	PricePesewas   int64
	Unit           string
	Region         string
	District       string
	ItemState      string
	PublishedAt    *time.Time
	CategorySlug   string
	CategoryName   string
	PromoTier      *string
	CoverKey       interface{}
	SellerName     string
	SellerVerified bool
	Available      bool
}

// The caller's favourited listings, newest favourited first, including
// inactive ones: the available flag tells the client which are browsable.
// The projection mirrors SearchListings so summaries map the same way.
func (q *Queries) ListFavoriteListings(ctx context.Context, arg ListFavoriteListingsParams) ([]ListFavoriteListingsRow, error) {
	rows, err := q.db.Query(ctx, listFavoriteListings,
		arg.UserID,
		arg.Now,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFavoriteListingsRow{}
	for rows.Next() {
		var i ListFavoriteListingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.PricePesewas,
			&i.Unit,
			&i.Region,
			&i.District,
			&i.ItemState,
			&i.PublishedAt,
			&i.CategorySlug,
			&i.CategoryName,
			&i.PromoTier,
			&i.CoverKey,
			&i.SellerName,
			&i.SellerVerified,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleReviewsByListing = `-- name: ListVisibleReviewsByListing :many
SELECT id, order_id, listing_id, seller_id, reviewer_id, rating, comment, hidden_at, created_at, updated_at FROM reviews
WHERE listing_id = $1 AND hidden_at IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListVisibleReviewsByListingParams struct {
	ListingID uuid.UUID
	Offset    int32
	Limit     int32
}

func (q *Queries) ListVisibleReviewsByListing(ctx context.Context, arg ListVisibleReviewsByListingParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listVisibleReviewsByListing, arg.ListingID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ListingID,
			&i.SellerID,
			&i.ReviewerID,
			&i.Rating,
			&i.Comment,
			&i.HiddenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sellerRating = `-- name: SellerRating :one
SELECT coalesce(round(avg(rating)::numeric, 1), 0)::float AS average,
       count(*)::bigint AS count
FROM reviews WHERE seller_id = $1 AND hidden_at IS NULL
`

type SellerRatingRow struct {
	Average float64
	Count   int64
}

// The seller's aggregate over visible reviews: the average to one decimal
// and the count. Average is 0 when there are no visible reviews.
func (q *Queries) SellerRating(ctx context.Context, sellerID uuid.UUID) (SellerRatingRow, error) {
	row := q.db.QueryRow(ctx, sellerRating, sellerID)
	var i SellerRatingRow
	err := row.Scan(&i.Average, &i.Count)
	return i, err
}

const setReviewHidden = `-- name: SetReviewHidden :one
UPDATE reviews SET hidden_at = $2 WHERE id = $1 AND hidden_at IS NULL
RETURNING id, order_id, listing_id, seller_id, reviewer_id, rating, comment, hidden_at, created_at, updated_at
`

type SetReviewHiddenParams struct {
	ID       uuid.UUID
	HiddenAt *time.Time
}

// Hides a review for moderation. Returns no row when already hidden.
func (q *Queries) SetReviewHidden(ctx context.Context, arg SetReviewHiddenParams) (Review, error) {
	row := q.db.QueryRow(ctx, setReviewHidden, arg.ID, arg.HiddenAt)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ListingID,
		&i.SellerID,
		&i.ReviewerID,
		&i.Rating,
		&i.Comment,
		&i.HiddenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
