// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerAccount = `-- name: CreateLedgerAccount :one
INSERT INTO ledger_accounts (code, type, currency, owner_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (code) DO NOTHING
RETURNING id, code, type, currency, owner_id, created_at
`

type CreateLedgerAccountParams struct {
	Code     string
	Type     string
	Currency string
	OwnerID  pgtype.UUID
}

// Creates an account, or returns no row when code already exists. Dynamic
// seller and promotion-credit accounts use this path; the caller selects the
// existing row after losing the race.
func (q *Queries) CreateLedgerAccount(ctx context.Context, arg CreateLedgerAccountParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, createLedgerAccount,
		arg.Code,
		arg.Type,
		arg.Currency,
		arg.OwnerID,
	)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Currency,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger_entries (transaction_id, account_id, amount, currency, order_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, transaction_id, account_id, amount, currency, order_id, created_at
`

type CreateLedgerEntryParams struct {
	TransactionID int64
	AccountID     int64
	Amount        int64
	Currency      string
	OrderID       pgtype.UUID
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.TransactionID,
		arg.AccountID,
		arg.Amount,
		arg.Currency,
		arg.OrderID,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.AccountID,
		&i.Amount,
		&i.Currency,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}

const createLedgerTransaction = `-- name: CreateLedgerTransaction :one
INSERT INTO ledger_transactions (kind, reference)
VALUES ($1, $2)
ON CONFLICT (kind, reference) DO NOTHING
RETURNING id, kind, reference, created_at
`

type CreateLedgerTransactionParams struct {
	Kind      string
	Reference string
}

// Creates a ledger transaction, or returns no row when (kind, reference) was
// already posted. That missing row is the caller's idempotency signal.
func (q *Queries) CreateLedgerTransaction(ctx context.Context, arg CreateLedgerTransactionParams) (LedgerTransaction, error) {
	row := q.db.QueryRow(ctx, createLedgerTransaction, arg.Kind, arg.Reference)
	var i LedgerTransaction
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Reference,
		&i.CreatedAt,
	)
	return i, err
}

const getLedgerAccountByCode = `-- name: GetLedgerAccountByCode :one
SELECT id, code, type, currency, owner_id, created_at FROM ledger_accounts WHERE code = $1
`

// An account row by its unique code.
func (q *Queries) GetLedgerAccountByCode(ctx context.Context, code string) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getLedgerAccountByCode, code)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Currency,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const sumLedgerAccountBalance = `-- name: SumLedgerAccountBalance :one
SELECT COALESCE(SUM(le.amount), 0)::bigint AS balance
FROM ledger_accounts la
LEFT JOIN ledger_entries le ON le.account_id = la.id
WHERE la.code = $1
`

// The account balance is derived from its entries. A code with no entries has
// a zero balance, so this always returns a row for an existing account.
func (q *Queries) SumLedgerAccountBalance(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRow(ctx, sumLedgerAccountBalance, code)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}
