// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listings.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSellerListings = `-- name: CountSellerListings :one
SELECT count(*) FROM listings
WHERE seller_id = $1 AND ($2::text IS NULL OR status = $2)
`

type CountSellerListingsParams struct {
	SellerID uuid.UUID
	Status   *string
}

func (q *Queries) CountSellerListings(ctx context.Context, arg CountSellerListingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSellerListings, arg.SellerID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteListing = `-- name: DeleteListing :one
DELETE FROM listings WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteListing(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteListing, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const deleteListingAttributes = `-- name: DeleteListingAttributes :exec
DELETE FROM listing_attribute_values WHERE listing_id = $1
`

func (q *Queries) DeleteListingAttributes(ctx context.Context, listingID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteListingAttributes, listingID)
	return err
}

const deleteListingImages = `-- name: DeleteListingImages :exec
DELETE FROM listing_images WHERE listing_id = $1
`

func (q *Queries) DeleteListingImages(ctx context.Context, listingID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteListingImages, listingID)
	return err
}

const expireDueListings = `-- name: ExpireDueListings :many
UPDATE listings SET status = 'expired'
WHERE status = 'active' AND expires_at <= $1
RETURNING id
`

// The expiry sweep: active listings past their expiry become expired.
func (q *Queries) ExpireDueListings(ctx context.Context, expiresAt *time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, expireDueListings, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListingByID = `-- name: GetListingByID :one
SELECT id, seller_id, category_id, title, slug, description, price_pesewas, unit, quantity_available, min_order_qty, is_negotiable, item_state, status, region, district, area, offers_pickup, offers_seller_delivery, seller_delivery_fee_pesewas, published_at, expires_at, view_count, favorite_count, contact_count, created_at, updated_at FROM listings WHERE id = $1
`

func (q *Queries) GetListingByID(ctx context.Context, id uuid.UUID) (Listing, error) {
	row := q.db.QueryRow(ctx, getListingByID, id)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.PricePesewas,
		&i.Unit,
		&i.QuantityAvailable,
		&i.MinOrderQty,
		&i.IsNegotiable,
		&i.ItemState,
		&i.Status,
		&i.Region,
		&i.District,
		&i.Area,
		&i.OffersPickup,
		&i.OffersSellerDelivery,
		&i.SellerDeliveryFeePesewas,
		&i.PublishedAt,
		&i.ExpiresAt,
		&i.ViewCount,
		&i.FavoriteCount,
		&i.ContactCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListingByIDForUpdate = `-- name: GetListingByIDForUpdate :one
SELECT id, seller_id, category_id, title, slug, description, price_pesewas, unit, quantity_available, min_order_qty, is_negotiable, item_state, status, region, district, area, offers_pickup, offers_seller_delivery, seller_delivery_fee_pesewas, published_at, expires_at, view_count, favorite_count, contact_count, created_at, updated_at FROM listings WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetListingByIDForUpdate(ctx context.Context, id uuid.UUID) (Listing, error) {
	row := q.db.QueryRow(ctx, getListingByIDForUpdate, id)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.PricePesewas,
		&i.Unit,
		&i.QuantityAvailable,
		&i.MinOrderQty,
		&i.IsNegotiable,
		&i.ItemState,
		&i.Status,
		&i.Region,
		&i.District,
		&i.Area,
		&i.OffersPickup,
		&i.OffersSellerDelivery,
		&i.SellerDeliveryFeePesewas,
		&i.PublishedAt,
		&i.ExpiresAt,
		&i.ViewCount,
		&i.FavoriteCount,
		&i.ContactCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListingBySlug = `-- name: GetListingBySlug :one
SELECT id, seller_id, category_id, title, slug, description, price_pesewas, unit, quantity_available, min_order_qty, is_negotiable, item_state, status, region, district, area, offers_pickup, offers_seller_delivery, seller_delivery_fee_pesewas, published_at, expires_at, view_count, favorite_count, contact_count, created_at, updated_at FROM listings WHERE slug = $1
`

func (q *Queries) GetListingBySlug(ctx context.Context, slug string) (Listing, error) {
	row := q.db.QueryRow(ctx, getListingBySlug, slug)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.PricePesewas,
		&i.Unit,
		&i.QuantityAvailable,
		&i.MinOrderQty,
		&i.IsNegotiable,
		&i.ItemState,
		&i.Status,
		&i.Region,
		&i.District,
		&i.Area,
		&i.OffersPickup,
		&i.OffersSellerDelivery,
		&i.SellerDeliveryFeePesewas,
		&i.PublishedAt,
		&i.ExpiresAt,
		&i.ViewCount,
		&i.FavoriteCount,
		&i.ContactCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertListing = `-- name: InsertListing :one
INSERT INTO listings (
  seller_id, category_id, title, slug, description, price_pesewas, unit,
  quantity_available, min_order_qty, is_negotiable, item_state, region, district, area,
  offers_pickup, offers_seller_delivery, seller_delivery_fee_pesewas
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING id, seller_id, category_id, title, slug, description, price_pesewas, unit, quantity_available, min_order_qty, is_negotiable, item_state, status, region, district, area, offers_pickup, offers_seller_delivery, seller_delivery_fee_pesewas, published_at, expires_at, view_count, favorite_count, contact_count, created_at, updated_at
`

type InsertListingParams struct {
	SellerID                 uuid.UUID
	CategoryID               uuid.UUID
	Title                    string
	Slug                     string
	Description              string
	PricePesewas             int64
	Unit                     string
	QuantityAvailable        int32
	MinOrderQty              int32
	IsNegotiable             bool
	ItemState                string
	Region                   string
	District                 string
	Area                     *string
	OffersPickup             bool
	OffersSellerDelivery     bool
	SellerDeliveryFeePesewas *int64
}

func (q *Queries) InsertListing(ctx context.Context, arg InsertListingParams) (Listing, error) {
	row := q.db.QueryRow(ctx, insertListing,
		arg.SellerID,
		arg.CategoryID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.PricePesewas,
		arg.Unit,
		arg.QuantityAvailable,
		arg.MinOrderQty,
		arg.IsNegotiable,
		arg.ItemState,
		arg.Region,
		arg.District,
		arg.Area,
		arg.OffersPickup,
		arg.OffersSellerDelivery,
		arg.SellerDeliveryFeePesewas,
	)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.PricePesewas,
		&i.Unit,
		&i.QuantityAvailable,
		&i.MinOrderQty,
		&i.IsNegotiable,
		&i.ItemState,
		&i.Status,
		&i.Region,
		&i.District,
		&i.Area,
		&i.OffersPickup,
		&i.OffersSellerDelivery,
		&i.SellerDeliveryFeePesewas,
		&i.PublishedAt,
		&i.ExpiresAt,
		&i.ViewCount,
		&i.FavoriteCount,
		&i.ContactCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertListingAttribute = `-- name: InsertListingAttribute :exec
INSERT INTO listing_attribute_values (listing_id, attribute_id, value) VALUES ($1, $2, $3)
`

type InsertListingAttributeParams struct {
	ListingID   uuid.UUID
	AttributeID uuid.UUID
	Value       string
}

func (q *Queries) InsertListingAttribute(ctx context.Context, arg InsertListingAttributeParams) error {
	_, err := q.db.Exec(ctx, insertListingAttribute, arg.ListingID, arg.AttributeID, arg.Value)
	return err
}

const insertListingImage = `-- name: InsertListingImage :exec
INSERT INTO listing_images (listing_id, media_id, sort_order) VALUES ($1, $2, $3)
`

type InsertListingImageParams struct {
	ListingID uuid.UUID
	MediaID   uuid.UUID
	SortOrder int32
}

func (q *Queries) InsertListingImage(ctx context.Context, arg InsertListingImageParams) error {
	_, err := q.db.Exec(ctx, insertListingImage, arg.ListingID, arg.MediaID, arg.SortOrder)
	return err
}

const listListingAttributes = `-- name: ListListingAttributes :many
SELECT la.listing_id, la.attribute_id, la.value, ca.key, ca.type, ca.required
FROM listing_attribute_values la
JOIN category_attributes ca ON ca.id = la.attribute_id
WHERE la.listing_id = $1
ORDER BY ca.sort_order, ca.key
`

type ListListingAttributesRow struct {
	ListingID   uuid.UUID
	AttributeID uuid.UUID
	Value       string
	Key         string
	Type        string
	Required    bool
}

func (q *Queries) ListListingAttributes(ctx context.Context, listingID uuid.UUID) ([]ListListingAttributesRow, error) {
	rows, err := q.db.Query(ctx, listListingAttributes, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListListingAttributesRow{}
	for rows.Next() {
		var i ListListingAttributesRow
		if err := rows.Scan(
			&i.ListingID,
			&i.AttributeID,
			&i.Value,
			&i.Key,
			&i.Type,
			&i.Required,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListingImages = `-- name: ListListingImages :many
SELECT li.listing_id, li.media_id, li.sort_order, mo.key, mo.content_type, mo.size_bytes
FROM listing_images li
JOIN media_objects mo ON mo.id = li.media_id
WHERE li.listing_id = $1
ORDER BY li.sort_order
`

type ListListingImagesRow struct {
	ListingID   uuid.UUID
	MediaID     uuid.UUID
	SortOrder   int32
	Key         string
	ContentType string
	SizeBytes   int64
}

// Read-only join so the owner's view can carry each object's key (and hence
// its public URL).
func (q *Queries) ListListingImages(ctx context.Context, listingID uuid.UUID) ([]ListListingImagesRow, error) {
	rows, err := q.db.Query(ctx, listListingImages, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListListingImagesRow{}
	for rows.Next() {
		var i ListListingImagesRow
		if err := rows.Scan(
			&i.ListingID,
			&i.MediaID,
			&i.SortOrder,
			&i.Key,
			&i.ContentType,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellerListings = `-- name: ListSellerListings :many
SELECT id, seller_id, category_id, title, slug, description, price_pesewas, unit, quantity_available, min_order_qty, is_negotiable, item_state, status, region, district, area, offers_pickup, offers_seller_delivery, seller_delivery_fee_pesewas, published_at, expires_at, view_count, favorite_count, contact_count, created_at, updated_at FROM listings
WHERE seller_id = $1 AND ($2::text IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListSellerListingsParams struct {
	SellerID uuid.UUID
	Status   *string
	Offset   int32
	Limit    int32
}

func (q *Queries) ListSellerListings(ctx context.Context, arg ListSellerListingsParams) ([]Listing, error) {
	rows, err := q.db.Query(ctx, listSellerListings,
		arg.SellerID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Listing{}
	for rows.Next() {
		var i Listing
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.PricePesewas,
			&i.Unit,
			&i.QuantityAvailable,
			&i.MinOrderQty,
			&i.IsNegotiable,
			&i.ItemState,
			&i.Status,
			&i.Region,
			&i.District,
			&i.Area,
			&i.OffersPickup,
			&i.OffersSellerDelivery,
			&i.SellerDeliveryFeePesewas,
			&i.PublishedAt,
			&i.ExpiresAt,
			&i.ViewCount,
			&i.FavoriteCount,
			&i.ContactCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setListingStatus = `-- name: SetListingStatus :one
UPDATE listings SET
  status = $1,
  published_at = COALESCE($2, published_at),
  expires_at = COALESCE($3, expires_at)
WHERE id = $4
RETURNING id, seller_id, category_id, title, slug, description, price_pesewas, unit, quantity_available, min_order_qty, is_negotiable, item_state, status, region, district, area, offers_pickup, offers_seller_delivery, seller_delivery_fee_pesewas, published_at, expires_at, view_count, favorite_count, contact_count, created_at, updated_at
`

type SetListingStatusParams struct {
	Status      string
	PublishedAt *time.Time
	ExpiresAt   *time.Time
	ID          uuid.UUID
}

// Only published_at / expires_at are set when they are given (publish sets
// both; mark-sold and archive leave them alone).
func (q *Queries) SetListingStatus(ctx context.Context, arg SetListingStatusParams) (Listing, error) {
	row := q.db.QueryRow(ctx, setListingStatus,
		arg.Status,
		arg.PublishedAt,
		arg.ExpiresAt,
		arg.ID,
	)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.PricePesewas,
		&i.Unit,
		&i.QuantityAvailable,
		&i.MinOrderQty,
		&i.IsNegotiable,
		&i.ItemState,
		&i.Status,
		&i.Region,
		&i.District,
		&i.Area,
		&i.OffersPickup,
		&i.OffersSellerDelivery,
		&i.SellerDeliveryFeePesewas,
		&i.PublishedAt,
		&i.ExpiresAt,
		&i.ViewCount,
		&i.FavoriteCount,
		&i.ContactCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const slugExists = `-- name: SlugExists :one
SELECT EXISTS (SELECT 1 FROM listings WHERE slug = $1) AS exists
`

func (q *Queries) SlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, slugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateListing = `-- name: UpdateListing :one
UPDATE listings SET
  category_id = COALESCE($1, category_id),
  title = COALESCE($2, title),
  description = COALESCE($3, description),
  price_pesewas = COALESCE($4, price_pesewas),
  unit = COALESCE($5, unit),
  quantity_available = COALESCE($6, quantity_available),
  min_order_qty = COALESCE($7, min_order_qty),
  is_negotiable = COALESCE($8, is_negotiable),
  item_state = COALESCE($9, item_state),
  region = COALESCE($10, region),
  district = COALESCE($11, district),
  area = COALESCE($12, area),
  offers_pickup = COALESCE($13, offers_pickup),
  offers_seller_delivery = COALESCE($14, offers_seller_delivery),
  seller_delivery_fee_pesewas = COALESCE($15, seller_delivery_fee_pesewas)
WHERE id = $16
RETURNING id, seller_id, category_id, title, slug, description, price_pesewas, unit, quantity_available, min_order_qty, is_negotiable, item_state, status, region, district, area, offers_pickup, offers_seller_delivery, seller_delivery_fee_pesewas, published_at, expires_at, view_count, favorite_count, contact_count, created_at, updated_at
`

type UpdateListingParams struct {
	CategoryID               pgtype.UUID
	Title                    *string
	Description              *string
	PricePesewas             *int64
	Unit                     *string
	QuantityAvailable        *int32
	MinOrderQty              *int32
	IsNegotiable             *bool
	ItemState                *string
	Region                   *string
	District                 *string
	Area                     *string
	OffersPickup             *bool
	OffersSellerDelivery     *bool
	SellerDeliveryFeePesewas *int64
	ID                       uuid.UUID
}

// Every editable field, COALESCE-style: a nil parameter keeps the column.
func (q *Queries) UpdateListing(ctx context.Context, arg UpdateListingParams) (Listing, error) {
	row := q.db.QueryRow(ctx, updateListing,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.PricePesewas,
		arg.Unit,
		arg.QuantityAvailable,
		arg.MinOrderQty,
		arg.IsNegotiable,
		arg.ItemState,
		arg.Region,
		arg.District,
		arg.Area,
		arg.OffersPickup,
		arg.OffersSellerDelivery,
		arg.SellerDeliveryFeePesewas,
		arg.ID,
	)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.PricePesewas,
		&i.Unit,
		&i.QuantityAvailable,
		&i.MinOrderQty,
		&i.IsNegotiable,
		&i.ItemState,
		&i.Status,
		&i.Region,
		&i.District,
		&i.Area,
		&i.OffersPickup,
		&i.OffersSellerDelivery,
		&i.SellerDeliveryFeePesewas,
		&i.PublishedAt,
		&i.ExpiresAt,
		&i.ViewCount,
		&i.FavoriteCount,
		&i.ContactCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
