// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const attachMediaObject = `-- name: AttachMediaObject :one
UPDATE media_objects SET status = 'attached', attached_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, owner_id, key, purpose, content_type, size_bytes, status, created_at, attached_at
`

// Marks the object attached, but only while it is still pending.
func (q *Queries) AttachMediaObject(ctx context.Context, id uuid.UUID) (MediaObject, error) {
	row := q.db.QueryRow(ctx, attachMediaObject, id)
	var i MediaObject
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Key,
		&i.Purpose,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.AttachedAt,
	)
	return i, err
}

const deleteMediaObject = `-- name: DeleteMediaObject :one
DELETE FROM media_objects WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteMediaObject(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteMediaObject, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const getMediaObject = `-- name: GetMediaObject :one
SELECT id, owner_id, key, purpose, content_type, size_bytes, status, created_at, attached_at FROM media_objects WHERE id = $1
`

func (q *Queries) GetMediaObject(ctx context.Context, id uuid.UUID) (MediaObject, error) {
	row := q.db.QueryRow(ctx, getMediaObject, id)
	var i MediaObject
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Key,
		&i.Purpose,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.AttachedAt,
	)
	return i, err
}

const insertMediaObject = `-- name: InsertMediaObject :one
INSERT INTO media_objects (owner_id, key, purpose, content_type, size_bytes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, key, purpose, content_type, size_bytes, status, created_at, attached_at
`

type InsertMediaObjectParams struct {
	OwnerID     uuid.UUID
	Key         string
	Purpose     string
	ContentType string
	SizeBytes   int64
}

func (q *Queries) InsertMediaObject(ctx context.Context, arg InsertMediaObjectParams) (MediaObject, error) {
	row := q.db.QueryRow(ctx, insertMediaObject,
		arg.OwnerID,
		arg.Key,
		arg.Purpose,
		arg.ContentType,
		arg.SizeBytes,
	)
	var i MediaObject
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Key,
		&i.Purpose,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.AttachedAt,
	)
	return i, err
}

const listPendingMediaBefore = `-- name: ListPendingMediaBefore :many
SELECT id, owner_id, key, purpose, content_type, size_bytes, status, created_at, attached_at FROM media_objects
WHERE status = 'pending' AND created_at < $1
ORDER BY created_at
LIMIT $2
`

type ListPendingMediaBeforeParams struct {
	CreatedAt time.Time
	Limit     int32
}

// Cleanup sweep: pending rows older than the cutoff, oldest first.
func (q *Queries) ListPendingMediaBefore(ctx context.Context, arg ListPendingMediaBeforeParams) ([]MediaObject, error) {
	rows, err := q.db.Query(ctx, listPendingMediaBefore, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaObject{}
	for rows.Next() {
		var i MediaObject
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Key,
			&i.Purpose,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.CreatedAt,
			&i.AttachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
