// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messaging.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countConversationsByParticipant = `-- name: CountConversationsByParticipant :one
SELECT count(*) FROM conversations WHERE buyer_id = $1 OR seller_id = $1
`

func (q *Queries) CountConversationsByParticipant(ctx context.Context, buyerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countConversationsByParticipant, buyerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnread = `-- name: CountUnread :one
SELECT count(*) FROM messages
WHERE conversation_id = $1 AND sender_id <> $2
  AND ($3::timestamptz IS NULL OR created_at > $3)
`

type CountUnreadParams struct {
	ConversationID uuid.UUID
	SenderID       uuid.UUID
	ReadAt         *time.Time
}

// The caller's unread: others' messages newer than their read marker, or all
// of them when they never marked read.
func (q *Queries) CountUnread(ctx context.Context, arg CountUnreadParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnread, arg.ConversationID, arg.SenderID, arg.ReadAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, listing_id, buyer_id, seller_id, order_id, last_message_at, buyer_last_read_at, seller_last_read_at, created_at FROM conversations WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.SellerID,
		&i.OrderID,
		&i.LastMessageAt,
		&i.BuyerLastReadAt,
		&i.SellerLastReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationByListingBuyer = `-- name: GetConversationByListingBuyer :one
SELECT id, listing_id, buyer_id, seller_id, order_id, last_message_at, buyer_last_read_at, seller_last_read_at, created_at FROM conversations WHERE listing_id = $1 AND buyer_id = $2
`

type GetConversationByListingBuyerParams struct {
	ListingID uuid.UUID
	BuyerID   uuid.UUID
}

// The duplicate-start match: one conversation per (listing, buyer).
func (q *Queries) GetConversationByListingBuyer(ctx context.Context, arg GetConversationByListingBuyerParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByListingBuyer, arg.ListingID, arg.BuyerID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.SellerID,
		&i.OrderID,
		&i.LastMessageAt,
		&i.BuyerLastReadAt,
		&i.SellerLastReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationForUpdate = `-- name: GetConversationForUpdate :one
SELECT id, listing_id, buyer_id, seller_id, order_id, last_message_at, buyer_last_read_at, seller_last_read_at, created_at FROM conversations WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetConversationForUpdate(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationForUpdate, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.SellerID,
		&i.OrderID,
		&i.LastMessageAt,
		&i.BuyerLastReadAt,
		&i.SellerLastReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLastMessage = `-- name: GetLastMessage :one
SELECT id, conversation_id, sender_id, body, created_at FROM messages WHERE conversation_id = $1
ORDER BY created_at DESC, id DESC LIMIT 1
`

// The newest message of a conversation, for summaries. Returns no row when
// the conversation has no messages yet.
func (q *Queries) GetLastMessage(ctx context.Context, conversationID uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getLastMessage, conversationID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getListingForMessaging = `-- name: GetListingForMessaging :one
SELECT l.id, l.seller_id, l.status, l.title, l.slug,
       (l.status = 'active' AND l.expires_at > $2::timestamptz)::bool AS active,
       COALESCE((SELECT m.key FROM listing_images li JOIN media_objects m ON m.id = li.media_id
         WHERE li.listing_id = l.id ORDER BY li.sort_order LIMIT 1), '') AS cover_key
FROM listings l WHERE l.id = $1
`

type GetListingForMessagingParams struct {
	ID  uuid.UUID
	Now time.Time
}

type GetListingForMessagingRow struct {
	ID       uuid.UUID
	SellerID uuid.UUID
	Status   string
	Title    string
	Slug     string
	Active   bool
	CoverKey interface{}
}

// The listing a conversation starts from: its seller, status and title for
// the checks and the summary. Expired counts as inactive: the public reads
// filter expires_at the same way.
func (q *Queries) GetListingForMessaging(ctx context.Context, arg GetListingForMessagingParams) (GetListingForMessagingRow, error) {
	row := q.db.QueryRow(ctx, getListingForMessaging, arg.ID, arg.Now)
	var i GetListingForMessagingRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Status,
		&i.Title,
		&i.Slug,
		&i.Active,
		&i.CoverKey,
	)
	return i, err
}

const insertConversation = `-- name: InsertConversation :one
INSERT INTO conversations (listing_id, buyer_id, seller_id)
VALUES ($1, $2, $3)
ON CONFLICT (listing_id, buyer_id) DO NOTHING
RETURNING id, listing_id, buyer_id, seller_id, order_id, last_message_at, buyer_last_read_at, seller_last_read_at, created_at
`

type InsertConversationParams struct {
	ListingID uuid.UUID
	BuyerID   uuid.UUID
	SellerID  uuid.UUID
}

// Opens a conversation. Returns no row when this buyer already has one for
// the listing: the caller appends to the existing row instead.
func (q *Queries) InsertConversation(ctx context.Context, arg InsertConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, insertConversation, arg.ListingID, arg.BuyerID, arg.SellerID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.SellerID,
		&i.OrderID,
		&i.LastMessageAt,
		&i.BuyerLastReadAt,
		&i.SellerLastReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (conversation_id, sender_id, body)
VALUES ($1, $2, $3)
RETURNING id, conversation_id, sender_id, body, created_at
`

type InsertMessageParams struct {
	ConversationID uuid.UUID
	SenderID       uuid.UUID
	Body           string
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage, arg.ConversationID, arg.SenderID, arg.Body)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listConversationsByParticipant = `-- name: ListConversationsByParticipant :many
SELECT id, listing_id, buyer_id, seller_id, order_id, last_message_at, buyer_last_read_at, seller_last_read_at, created_at FROM conversations WHERE buyer_id = $1 OR seller_id = $1
ORDER BY last_message_at DESC NULLS LAST, created_at DESC
LIMIT $3 OFFSET $2
`

type ListConversationsByParticipantParams struct {
	BuyerID uuid.UUID
	Offset  int32
	Limit   int32
}

// The caller's conversations on either side, newest activity first.
func (q *Queries) ListConversationsByParticipant(ctx context.Context, arg ListConversationsByParticipantParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsByParticipant, arg.BuyerID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.BuyerID,
			&i.SellerID,
			&i.OrderID,
			&i.LastMessageAt,
			&i.BuyerLastReadAt,
			&i.SellerLastReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, sender_id, body, created_at FROM messages
WHERE conversation_id = $1
  AND ($2::timestamptz IS NULL OR (created_at, id) < ($2, $3::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListMessagesParams struct {
	ConversationID uuid.UUID
	BeforeAt       *time.Time
	BeforeID       pgtype.UUID
	Limit          int32
}

// Newest first, before an optional cursor (created_at, id): every row is
// strictly older than the cursor, so pages never duplicate or skip, even
// under concurrent inserts.
func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages,
		arg.ConversationID,
		arg.BeforeAt,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifyMessagingEvent = `-- name: NotifyMessagingEvent :one
SELECT pg_notify('messaging_events', $1) AS notified
`

// Publishes a realtime event inside the caller's transaction: it fires at
// commit, so a rolled-back write emits nothing.
func (q *Queries) NotifyMessagingEvent(ctx context.Context, pgNotify string) (interface{}, error) {
	row := q.db.QueryRow(ctx, notifyMessagingEvent, pgNotify)
	var notified interface{}
	err := row.Scan(&notified)
	return notified, err
}

const setConversationLastMessage = `-- name: SetConversationLastMessage :exec
UPDATE conversations SET last_message_at = $2 WHERE id = $1
`

type SetConversationLastMessageParams struct {
	ID            uuid.UUID
	LastMessageAt *time.Time
}

func (q *Queries) SetConversationLastMessage(ctx context.Context, arg SetConversationLastMessageParams) error {
	_, err := q.db.Exec(ctx, setConversationLastMessage, arg.ID, arg.LastMessageAt)
	return err
}

const setConversationRead = `-- name: SetConversationRead :exec
UPDATE conversations SET buyer_last_read_at = $2 WHERE id = $1
`

type SetConversationReadParams struct {
	ID              uuid.UUID
	BuyerLastReadAt *time.Time
}

// Marks the caller's side read. The column is chosen by the caller from the
// party they proved, never from the request.
func (q *Queries) SetConversationRead(ctx context.Context, arg SetConversationReadParams) error {
	_, err := q.db.Exec(ctx, setConversationRead, arg.ID, arg.BuyerLastReadAt)
	return err
}

const setConversationReadSeller = `-- name: SetConversationReadSeller :exec
UPDATE conversations SET seller_last_read_at = $2 WHERE id = $1
`

type SetConversationReadSellerParams struct {
	ID               uuid.UUID
	SellerLastReadAt *time.Time
}

func (q *Queries) SetConversationReadSeller(ctx context.Context, arg SetConversationReadSellerParams) error {
	_, err := q.db.Exec(ctx, setConversationReadSeller, arg.ID, arg.SellerLastReadAt)
	return err
}
