// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState
	Valid         bool // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type AuditEvent struct {
	ID         int64
	ActorID    pgtype.UUID
	Action     string
	TargetType string
	TargetID   string
	Metadata   []byte
	CreatedAt  time.Time
}

type Category struct {
	ID           uuid.UUID
	ParentID     pgtype.UUID
	Name         string
	Slug         string
	Icon         *string
	ListingGroup *string
	SortOrder    int32
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type CategoryAttribute struct {
	ID         uuid.UUID
	CategoryID uuid.UUID
	Key        string
	Label      string
	Type       string
	Options    []string
	Required   bool
	SortOrder  int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Checkout struct {
	ID                   uuid.UUID
	BuyerID              uuid.UUID
	IdempotencyKey       uuid.UUID
	RequestHash          string
	BasePesewas          int64
	ProcessingFeePesewas int64
	ChargePesewas        int64
	PaymentID            pgtype.UUID
	Status               string
	ExpiresAt            time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type CommissionConfig struct {
	ID         uuid.UUID
	CategoryID pgtype.UUID
	RateBps    int32
	UpdatedAt  time.Time
}

type Conversation struct {
	ID               uuid.UUID
	ListingID        uuid.UUID
	BuyerID          uuid.UUID
	SellerID         uuid.UUID
	OrderID          pgtype.UUID
	LastMessageAt    *time.Time
	BuyerLastReadAt  *time.Time
	SellerLastReadAt *time.Time
	CreatedAt        time.Time
}

type Dispute struct {
	ID             uuid.UUID
	OrderID        uuid.UUID
	OpenedBy       uuid.UUID
	Reason         string
	Description    string
	Status         string
	Outcome        *string
	RefundPesewas  *int64
	ResolutionNote *string
	ResolvedBy     pgtype.UUID
	ResolvedAt     *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Favorite struct {
	UserID    uuid.UUID
	ListingID uuid.UUID
	CreatedAt time.Time
}

type LedgerAccount struct {
	ID        int64
	Code      string
	Type      string
	Currency  string
	OwnerID   pgtype.UUID
	CreatedAt time.Time
}

type LedgerEntry struct {
	ID            int64
	TransactionID int64
	AccountID     int64
	Amount        int64
	Currency      string
	OrderID       pgtype.UUID
	CreatedAt     time.Time
}

type LedgerTransaction struct {
	ID        int64
	Kind      string
	Reference string
	CreatedAt time.Time
}

type Listing struct {
	ID                       uuid.UUID
	SellerID                 uuid.UUID
	CategoryID               uuid.UUID
	Title                    string
	Slug                     string
	Description              string
	PricePesewas             int64
	Unit                     string
	QuantityAvailable        int32
	MinOrderQty              int32
	IsNegotiable             bool
	ItemState                string
	Status                   string
	Region                   string
	District                 string
	Area                     *string
	OffersPickup             bool
	OffersSellerDelivery     bool
	SellerDeliveryFeePesewas *int64
	PublishedAt              *time.Time
	ExpiresAt                *time.Time
	ViewCount                int32
	FavoriteCount            int32
	ContactCount             int32
	CreatedAt                time.Time
	UpdatedAt                time.Time
	SearchVector             interface{}
}

type ListingAttributeValue struct {
	ListingID   uuid.UUID
	AttributeID uuid.UUID
	Value       string
}

type ListingImage struct {
	ListingID uuid.UUID
	MediaID   uuid.UUID
	SortOrder int32
}

type ListingPromotion struct {
	ID           uuid.UUID
	ListingID    uuid.UUID
	SellerID     uuid.UUID
	Tier         string
	TierRank     int32
	StartsAt     time.Time
	EndsAt       time.Time
	CreatedAt    time.Time
	CreditsSpent int32
}

type MediaObject struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Key         string
	Purpose     string
	ContentType string
	SizeBytes   int64
	Status      string
	CreatedAt   time.Time
	AttachedAt  *time.Time
}

type Message struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	SenderID       uuid.UUID
	Body           string
	CreatedAt      time.Time
}

type Order struct {
	ID                 uuid.UUID
	CheckoutID         uuid.UUID
	BuyerID            uuid.UUID
	SellerID           uuid.UUID
	Status             string
	EscrowState        string
	SubtotalPesewas    int64
	DeliveryFeePesewas int64
	BasePesewas        int64
	CommissionRateBps  int32
	CommissionPesewas  int64
	RefundedPesewas    int64
	DeliveryMethod     string
	DeliveryAddress    *string
	DeliveryRegion     *string
	DeliveryDistrict   *string
	RecipientName      *string
	RecipientPhone     *string
	TrackingRef        *string
	PaidAt             *time.Time
	AcceptedAt         *time.Time
	ShippedAt          *time.Time
	DeliveredAt        *time.Time
	CompletedAt        *time.Time
	CancelledAt        *time.Time
	AutoCompleteAt     *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type OrderEvent struct {
	ID         int64
	OrderID    uuid.UUID
	FromStatus *string
	ToStatus   string
	ActorType  string
	ActorID    pgtype.UUID
	Note       *string
	CreatedAt  time.Time
}

type OrderItem struct {
	ID               uuid.UUID
	OrderID          uuid.UUID
	ListingID        uuid.UUID
	Title            string
	Unit             string
	UnitPricePesewas int64
	Quantity         int32
	LineTotalPesewas int64
}

type Payment struct {
	ID                   uuid.UUID
	Reference            string
	UserID               uuid.UUID
	Purpose              string
	PurposeRef           string
	BasePesewas          int64
	ProcessingFeePesewas int64
	ChargePesewas        int64
	Currency             string
	Status               string
	PaystackFeePesewas   *int64
	Channel              *string
	AuthorizationUrl     *string
	PaidAt               *time.Time
	FailureReason        *string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Metadata             []byte
}

type Payout struct {
	ID            uuid.UUID
	SellerID      uuid.UUID
	AmountPesewas int64
	Reference     string
	RecipientCode string
	TransferCode  *string
	Status        string
	FailureReason *string
	SentAt        *time.Time
	CompletedAt   *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type PromotionConfig struct {
	Tier         string
	Name         string
	PricePesewas int64
	Credits      int32
	DurationDays int32
	TierRank     int32
	Featured     bool
	Description  string
	Features     []string
	SortOrder    int32
	IsActive     bool
	UpdatedAt    time.Time
}

type Refund struct {
	ID               uuid.UUID
	OrderID          uuid.UUID
	AmountPesewas    int64
	Reason           string
	Status           string
	PaystackRefundID *string
	FailureReason    *string
	AttemptedAt      *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Report struct {
	ID             uuid.UUID
	ReporterID     uuid.UUID
	ListingID      pgtype.UUID
	ReportedUserID pgtype.UUID
	Reason         string
	Description    *string
	Status         string
	Action         *string
	ResolutionNote *string
	ResolvedBy     pgtype.UUID
	ResolvedAt     *time.Time
	CreatedAt      time.Time
}

type Review struct {
	ID         uuid.UUID
	OrderID    uuid.UUID
	ListingID  uuid.UUID
	SellerID   uuid.UUID
	ReviewerID uuid.UUID
	Rating     int16
	Comment    *string
	HiddenAt   *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type RiverJob struct {
	ID           int64
	State        RiverJobState
	Attempt      int16
	MaxAttempts  int16
	AttemptedAt  *time.Time
	CreatedAt    time.Time
	FinalizedAt  *time.Time
	ScheduledAt  time.Time
	Priority     int16
	Args         []byte
	AttemptedBy  []string
	Errors       [][]byte
	Kind         string
	Metadata     []byte
	Queue        string
	Tags         []string
	UniqueKey    []byte
	UniqueStates pgtype.Bits
}

type RiverLeader struct {
	ElectedAt time.Time
	ExpiresAt time.Time
	LeaderID  string
	Name      string
}

type RiverNotification struct {
	ID        int64
	CreatedAt time.Time
	Payload   string
	Topic     string
}

type RiverQueue struct {
	Name      string
	CreatedAt time.Time
	Metadata  []byte
	PausedAt  *time.Time
	UpdatedAt time.Time
}

type SellerPayoutAccount struct {
	SellerID          uuid.UUID
	Type              string
	BankCode          string
	BankName          string
	AccountNumberEnc  string
	AccountNumberMask string
	AccountName       string
	RecipientCode     string
	Status            string
	VerifiedAt        *time.Time
	CooldownUntil     *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type SellerProfile struct {
	UserID             uuid.UUID
	BusinessName       string
	Region             string
	District           string
	Bio                *string
	ShowPhone          bool
	ShowWhatsapp       bool
	WhatsappE164       *string
	VerificationStatus string
	IDType             *string
	IDNumberEnc        *string
	IDNumberLast4      *string
	SubmittedAt        *time.Time
	ReviewedAt         *time.Time
	ReviewedBy         pgtype.UUID
	RejectionReason    *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type SupplyRequest struct {
	ID              uuid.UUID
	RequestNumber   string
	UserID          uuid.UUID
	DeliveryName    *string
	DeliveryPhone   *string
	DeliveryAddress *string
	ExpectedDate    pgtype.Date
	Notes           *string
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type SupplyRequestEvent struct {
	ID              int64
	SupplyRequestID uuid.UUID
	FromStatus      *string
	ToStatus        string
	ActorID         pgtype.UUID
	Note            *string
	CreatedAt       time.Time
}

type SupplyRequestItem struct {
	ID              uuid.UUID
	SupplyRequestID uuid.UUID
	CategoryID      uuid.UUID
	ProductName     string
	Quantity        int32
	Unit            string
	SortOrder       int32
}

type User struct {
	ID             uuid.UUID
	FirebaseUid    string
	SignupMethod   string
	Email          *string
	EmailVerified  bool
	PhoneE164      *string
	DisplayName    *string
	Role           string
	SellerVerified bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type WebhookEvent struct {
	ID          int64
	Provider    string
	EventKey    string
	EventType   string
	Payload     []byte
	ReceivedAt  time.Time
	ProcessedAt *time.Time
	Outcome     *string
}
