// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOrdersByBuyer = `-- name: CountOrdersByBuyer :one
SELECT count(*) FROM orders
WHERE buyer_id = $1 AND ($2::text IS NULL OR status = $2)
`

type CountOrdersByBuyerParams struct {
	BuyerID uuid.UUID
	Status  *string
}

func (q *Queries) CountOrdersByBuyer(ctx context.Context, arg CountOrdersByBuyerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByBuyer, arg.BuyerID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrdersBySeller = `-- name: CountOrdersBySeller :one
SELECT count(*) FROM orders
WHERE seller_id = $1 AND ($2::text IS NULL OR status = $2)
`

type CountOrdersBySellerParams struct {
	SellerID uuid.UUID
	Status   *string
}

func (q *Queries) CountOrdersBySeller(ctx context.Context, arg CountOrdersBySellerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersBySeller, arg.SellerID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCheckoutByID = `-- name: GetCheckoutByID :one
SELECT id, buyer_id, idempotency_key, request_hash, base_pesewas, processing_fee_pesewas, charge_pesewas, payment_id, status, expires_at, created_at, updated_at FROM checkouts WHERE id = $1
`

func (q *Queries) GetCheckoutByID(ctx context.Context, id uuid.UUID) (Checkout, error) {
	row := q.db.QueryRow(ctx, getCheckoutByID, id)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.BasePesewas,
		&i.ProcessingFeePesewas,
		&i.ChargePesewas,
		&i.PaymentID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckoutByIdempotencyKey = `-- name: GetCheckoutByIdempotencyKey :one
SELECT id, buyer_id, idempotency_key, request_hash, base_pesewas, processing_fee_pesewas, charge_pesewas, payment_id, status, expires_at, created_at, updated_at FROM checkouts WHERE buyer_id = $1 AND idempotency_key = $2
`

type GetCheckoutByIdempotencyKeyParams struct {
	BuyerID        uuid.UUID
	IdempotencyKey uuid.UUID
}

func (q *Queries) GetCheckoutByIdempotencyKey(ctx context.Context, arg GetCheckoutByIdempotencyKeyParams) (Checkout, error) {
	row := q.db.QueryRow(ctx, getCheckoutByIdempotencyKey, arg.BuyerID, arg.IdempotencyKey)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.BasePesewas,
		&i.ProcessingFeePesewas,
		&i.ChargePesewas,
		&i.PaymentID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckoutForUpdate = `-- name: GetCheckoutForUpdate :one
SELECT id, buyer_id, idempotency_key, request_hash, base_pesewas, processing_fee_pesewas, charge_pesewas, payment_id, status, expires_at, created_at, updated_at FROM checkouts WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetCheckoutForUpdate(ctx context.Context, id uuid.UUID) (Checkout, error) {
	row := q.db.QueryRow(ctx, getCheckoutForUpdate, id)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.BasePesewas,
		&i.ProcessingFeePesewas,
		&i.ChargePesewas,
		&i.PaymentID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenDisputeByOrder = `-- name: GetOpenDisputeByOrder :one
SELECT id, order_id, opened_by, reason, description, status, outcome, refund_pesewas, resolution_note, resolved_by, resolved_at, created_at, updated_at FROM disputes WHERE order_id = $1 AND status = 'open'
`

// The auto-complete sweep's timer stop: an open dispute holds the order.
func (q *Queries) GetOpenDisputeByOrder(ctx context.Context, orderID uuid.UUID) (Dispute, error) {
	row := q.db.QueryRow(ctx, getOpenDisputeByOrder, orderID)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.OpenedBy,
		&i.Reason,
		&i.Description,
		&i.Status,
		&i.Outcome,
		&i.RefundPesewas,
		&i.ResolutionNote,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, checkout_id, buyer_id, seller_id, status, escrow_state, subtotal_pesewas, delivery_fee_pesewas, base_pesewas, commission_rate_bps, commission_pesewas, refunded_pesewas, delivery_method, delivery_address, delivery_region, delivery_district, recipient_name, recipient_phone, tracking_ref, paid_at, accepted_at, shipped_at, delivered_at, completed_at, cancelled_at, auto_complete_at, created_at, updated_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.BuyerID,
		&i.SellerID,
		&i.Status,
		&i.EscrowState,
		&i.SubtotalPesewas,
		&i.DeliveryFeePesewas,
		&i.BasePesewas,
		&i.CommissionRateBps,
		&i.CommissionPesewas,
		&i.RefundedPesewas,
		&i.DeliveryMethod,
		&i.DeliveryAddress,
		&i.DeliveryRegion,
		&i.DeliveryDistrict,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.TrackingRef,
		&i.PaidAt,
		&i.AcceptedAt,
		&i.ShippedAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.AutoCompleteAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderDetail = `-- name: GetOrderDetail :one
SELECT o.id, o.checkout_id, o.buyer_id, o.seller_id, o.status, o.escrow_state, o.subtotal_pesewas, o.delivery_fee_pesewas, o.base_pesewas, o.commission_rate_bps, o.commission_pesewas, o.refunded_pesewas, o.delivery_method, o.delivery_address, o.delivery_region, o.delivery_district, o.recipient_name, o.recipient_phone, o.tracking_ref, o.paid_at, o.accepted_at, o.shipped_at, o.delivered_at, o.completed_at, o.cancelled_at, o.auto_complete_at, o.created_at, o.updated_at, sp.business_name AS seller_name, sp.bio AS seller_bio,
       sp.verification_status AS seller_verification, u.created_at AS seller_member_since
FROM orders o
JOIN seller_profiles sp ON sp.user_id = o.seller_id
JOIN users u ON u.id = o.seller_id
WHERE o.id = $1
`

type GetOrderDetailRow struct {
	ID                 uuid.UUID
	CheckoutID         uuid.UUID
	BuyerID            uuid.UUID
	SellerID           uuid.UUID
	Status             string
	EscrowState        string
	SubtotalPesewas    int64
	DeliveryFeePesewas int64
	BasePesewas        int64
	CommissionRateBps  int32
	CommissionPesewas  int64
	RefundedPesewas    int64
	DeliveryMethod     string
	DeliveryAddress    *string
	DeliveryRegion     *string
	DeliveryDistrict   *string
	RecipientName      *string
	RecipientPhone     *string
	TrackingRef        *string
	PaidAt             *time.Time
	AcceptedAt         *time.Time
	ShippedAt          *time.Time
	DeliveredAt        *time.Time
	CompletedAt        *time.Time
	CancelledAt        *time.Time
	AutoCompleteAt     *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	SellerName         string
	SellerBio          *string
	SellerVerification string
	SellerMemberSince  time.Time
}

// Everything the order detail endpoint needs for either role, in one read.
func (q *Queries) GetOrderDetail(ctx context.Context, id uuid.UUID) (GetOrderDetailRow, error) {
	row := q.db.QueryRow(ctx, getOrderDetail, id)
	var i GetOrderDetailRow
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.BuyerID,
		&i.SellerID,
		&i.Status,
		&i.EscrowState,
		&i.SubtotalPesewas,
		&i.DeliveryFeePesewas,
		&i.BasePesewas,
		&i.CommissionRateBps,
		&i.CommissionPesewas,
		&i.RefundedPesewas,
		&i.DeliveryMethod,
		&i.DeliveryAddress,
		&i.DeliveryRegion,
		&i.DeliveryDistrict,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.TrackingRef,
		&i.PaidAt,
		&i.AcceptedAt,
		&i.ShippedAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.AutoCompleteAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerName,
		&i.SellerBio,
		&i.SellerVerification,
		&i.SellerMemberSince,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT id, checkout_id, buyer_id, seller_id, status, escrow_state, subtotal_pesewas, delivery_fee_pesewas, base_pesewas, commission_rate_bps, commission_pesewas, refunded_pesewas, delivery_method, delivery_address, delivery_region, delivery_district, recipient_name, recipient_phone, tracking_ref, paid_at, accepted_at, shipped_at, delivered_at, completed_at, cancelled_at, auto_complete_at, created_at, updated_at FROM orders WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetOrderForUpdate(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdate, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.BuyerID,
		&i.SellerID,
		&i.Status,
		&i.EscrowState,
		&i.SubtotalPesewas,
		&i.DeliveryFeePesewas,
		&i.BasePesewas,
		&i.CommissionRateBps,
		&i.CommissionPesewas,
		&i.RefundedPesewas,
		&i.DeliveryMethod,
		&i.DeliveryAddress,
		&i.DeliveryRegion,
		&i.DeliveryDistrict,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.TrackingRef,
		&i.PaidAt,
		&i.AcceptedAt,
		&i.ShippedAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.AutoCompleteAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuoteListingForUpdate = `-- name: GetQuoteListingForUpdate :many
SELECT l.id, l.seller_id, sp.business_name AS seller_name, l.title, l.unit,
       l.price_pesewas AS unit_price, l.quantity_available, l.min_order_qty,
       l.category_id, c.parent_id AS category_parent_id,
       (l.status = 'active' AND l.expires_at > $1::timestamptz)::bool AS active,
       l.offers_pickup, l.offers_seller_delivery, l.seller_delivery_fee_pesewas
FROM listings l
JOIN categories c ON c.id = l.category_id
JOIN seller_profiles sp ON sp.user_id = l.seller_id
WHERE l.id = ANY($2::uuid[])
ORDER BY l.id
FOR UPDATE
`

type GetQuoteListingForUpdateParams struct {
	Now        time.Time
	ListingIds []uuid.UUID
}

type GetQuoteListingForUpdateRow struct {
	ID                       uuid.UUID
	SellerID                 uuid.UUID
	SellerName               string
	Title                    string
	Unit                     string
	UnitPrice                int64
	QuantityAvailable        int32
	MinOrderQty              int32
	CategoryID               uuid.UUID
	CategoryParentID         pgtype.UUID
	Active                   bool
	OffersPickup             bool
	OffersSellerDelivery     bool
	SellerDeliveryFeePesewas *int64
}

// Snapshot locks for pricing, taken in ascending listing-id order by the
// caller to avoid deadlocks between concurrent checkouts.
func (q *Queries) GetQuoteListingForUpdate(ctx context.Context, arg GetQuoteListingForUpdateParams) ([]GetQuoteListingForUpdateRow, error) {
	rows, err := q.db.Query(ctx, getQuoteListingForUpdate, arg.Now, arg.ListingIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetQuoteListingForUpdateRow{}
	for rows.Next() {
		var i GetQuoteListingForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.SellerName,
			&i.Title,
			&i.Unit,
			&i.UnitPrice,
			&i.QuantityAvailable,
			&i.MinOrderQty,
			&i.CategoryID,
			&i.CategoryParentID,
			&i.Active,
			&i.OffersPickup,
			&i.OffersSellerDelivery,
			&i.SellerDeliveryFeePesewas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCheckout = `-- name: InsertCheckout :one
INSERT INTO checkouts (buyer_id, idempotency_key, request_hash, base_pesewas,
                      processing_fee_pesewas, charge_pesewas, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, buyer_id, idempotency_key, request_hash, base_pesewas, processing_fee_pesewas, charge_pesewas, payment_id, status, expires_at, created_at, updated_at
`

type InsertCheckoutParams struct {
	BuyerID              uuid.UUID
	IdempotencyKey       uuid.UUID
	RequestHash          string
	BasePesewas          int64
	ProcessingFeePesewas int64
	ChargePesewas        int64
	ExpiresAt            time.Time
}

// A checkout holds reserved stock and one payment while the buyer pays. The
// unique (buyer_id, idempotency_key) is what makes POST /v1/checkout replayable.
func (q *Queries) InsertCheckout(ctx context.Context, arg InsertCheckoutParams) (Checkout, error) {
	row := q.db.QueryRow(ctx, insertCheckout,
		arg.BuyerID,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.BasePesewas,
		arg.ProcessingFeePesewas,
		arg.ChargePesewas,
		arg.ExpiresAt,
	)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.BasePesewas,
		&i.ProcessingFeePesewas,
		&i.ChargePesewas,
		&i.PaymentID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDispute = `-- name: InsertDispute :one
INSERT INTO disputes (order_id, opened_by, reason, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (order_id) DO NOTHING
RETURNING id, order_id, opened_by, reason, description, status, outcome, refund_pesewas, resolution_note, resolved_by, resolved_at, created_at, updated_at
`

type InsertDisputeParams struct {
	OrderID     uuid.UUID
	OpenedBy    uuid.UUID
	Reason      string
	Description string
}

// Returns no row when the order already has a dispute: the buyer cannot open
// a second case (the unique order_id enforces it).
func (q *Queries) InsertDispute(ctx context.Context, arg InsertDisputeParams) (Dispute, error) {
	row := q.db.QueryRow(ctx, insertDispute,
		arg.OrderID,
		arg.OpenedBy,
		arg.Reason,
		arg.Description,
	)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.OpenedBy,
		&i.Reason,
		&i.Description,
		&i.Status,
		&i.Outcome,
		&i.RefundPesewas,
		&i.ResolutionNote,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders (checkout_id, buyer_id, seller_id, status, subtotal_pesewas,
                    delivery_fee_pesewas, base_pesewas, commission_rate_bps,
                    commission_pesewas, delivery_method, delivery_address,
                    delivery_region, delivery_district, recipient_name, recipient_phone)
VALUES ($1, $2, $3, 'pending_payment', $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, checkout_id, buyer_id, seller_id, status, escrow_state, subtotal_pesewas, delivery_fee_pesewas, base_pesewas, commission_rate_bps, commission_pesewas, refunded_pesewas, delivery_method, delivery_address, delivery_region, delivery_district, recipient_name, recipient_phone, tracking_ref, paid_at, accepted_at, shipped_at, delivered_at, completed_at, cancelled_at, auto_complete_at, created_at, updated_at
`

type InsertOrderParams struct {
	CheckoutID         uuid.UUID
	BuyerID            uuid.UUID
	SellerID           uuid.UUID
	SubtotalPesewas    int64
	DeliveryFeePesewas int64
	BasePesewas        int64
	CommissionRateBps  int32
	CommissionPesewas  int64
	DeliveryMethod     string
	DeliveryAddress    *string
	DeliveryRegion     *string
	DeliveryDistrict   *string
	RecipientName      *string
	RecipientPhone     *string
}

// The commission rate and amount are the resolved, snapshotted values from
// pricing: later config edits never touch an existing order.
func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.CheckoutID,
		arg.BuyerID,
		arg.SellerID,
		arg.SubtotalPesewas,
		arg.DeliveryFeePesewas,
		arg.BasePesewas,
		arg.CommissionRateBps,
		arg.CommissionPesewas,
		arg.DeliveryMethod,
		arg.DeliveryAddress,
		arg.DeliveryRegion,
		arg.DeliveryDistrict,
		arg.RecipientName,
		arg.RecipientPhone,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.BuyerID,
		&i.SellerID,
		&i.Status,
		&i.EscrowState,
		&i.SubtotalPesewas,
		&i.DeliveryFeePesewas,
		&i.BasePesewas,
		&i.CommissionRateBps,
		&i.CommissionPesewas,
		&i.RefundedPesewas,
		&i.DeliveryMethod,
		&i.DeliveryAddress,
		&i.DeliveryRegion,
		&i.DeliveryDistrict,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.TrackingRef,
		&i.PaidAt,
		&i.AcceptedAt,
		&i.ShippedAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.AutoCompleteAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrderEvent = `-- name: InsertOrderEvent :exec
INSERT INTO order_events (order_id, from_status, to_status, actor_type, actor_id, note)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOrderEventParams struct {
	OrderID    uuid.UUID
	FromStatus *string
	ToStatus   string
	ActorType  string
	ActorID    pgtype.UUID
	Note       *string
}

// The append-only event trail orders.Transition writes.
func (q *Queries) InsertOrderEvent(ctx context.Context, arg InsertOrderEventParams) error {
	_, err := q.db.Exec(ctx, insertOrderEvent,
		arg.OrderID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ActorType,
		arg.ActorID,
		arg.Note,
	)
	return err
}

const insertOrderItem = `-- name: InsertOrderItem :exec
INSERT INTO order_items (order_id, listing_id, title, unit, unit_price_pesewas, quantity, line_total_pesewas)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertOrderItemParams struct {
	OrderID          uuid.UUID
	ListingID        uuid.UUID
	Title            string
	Unit             string
	UnitPricePesewas int64
	Quantity         int32
	LineTotalPesewas int64
}

func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error {
	_, err := q.db.Exec(ctx, insertOrderItem,
		arg.OrderID,
		arg.ListingID,
		arg.Title,
		arg.Unit,
		arg.UnitPricePesewas,
		arg.Quantity,
		arg.LineTotalPesewas,
	)
	return err
}

const listCheckoutOrders = `-- name: ListCheckoutOrders :many
SELECT o.id, o.checkout_id, o.buyer_id, o.seller_id, o.status, o.escrow_state, o.subtotal_pesewas, o.delivery_fee_pesewas, o.base_pesewas, o.commission_rate_bps, o.commission_pesewas, o.refunded_pesewas, o.delivery_method, o.delivery_address, o.delivery_region, o.delivery_district, o.recipient_name, o.recipient_phone, o.tracking_ref, o.paid_at, o.accepted_at, o.shipped_at, o.delivered_at, o.completed_at, o.cancelled_at, o.auto_complete_at, o.created_at, o.updated_at, sp.business_name AS seller_name
FROM orders o
JOIN seller_profiles sp ON sp.user_id = o.seller_id
WHERE o.checkout_id = $1
ORDER BY o.seller_id
`

type ListCheckoutOrdersRow struct {
	ID                 uuid.UUID
	CheckoutID         uuid.UUID
	BuyerID            uuid.UUID
	SellerID           uuid.UUID
	Status             string
	EscrowState        string
	SubtotalPesewas    int64
	DeliveryFeePesewas int64
	BasePesewas        int64
	CommissionRateBps  int32
	CommissionPesewas  int64
	RefundedPesewas    int64
	DeliveryMethod     string
	DeliveryAddress    *string
	DeliveryRegion     *string
	DeliveryDistrict   *string
	RecipientName      *string
	RecipientPhone     *string
	TrackingRef        *string
	PaidAt             *time.Time
	AcceptedAt         *time.Time
	ShippedAt          *time.Time
	DeliveredAt        *time.Time
	CompletedAt        *time.Time
	CancelledAt        *time.Time
	AutoCompleteAt     *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	SellerName         string
}

// One row per seller order of a checkout, with the seller's public name for
// summaries and replays.
func (q *Queries) ListCheckoutOrders(ctx context.Context, checkoutID uuid.UUID) ([]ListCheckoutOrdersRow, error) {
	rows, err := q.db.Query(ctx, listCheckoutOrders, checkoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheckoutOrdersRow{}
	for rows.Next() {
		var i ListCheckoutOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.CheckoutID,
			&i.BuyerID,
			&i.SellerID,
			&i.Status,
			&i.EscrowState,
			&i.SubtotalPesewas,
			&i.DeliveryFeePesewas,
			&i.BasePesewas,
			&i.CommissionRateBps,
			&i.CommissionPesewas,
			&i.RefundedPesewas,
			&i.DeliveryMethod,
			&i.DeliveryAddress,
			&i.DeliveryRegion,
			&i.DeliveryDistrict,
			&i.RecipientName,
			&i.RecipientPhone,
			&i.TrackingRef,
			&i.PaidAt,
			&i.AcceptedAt,
			&i.ShippedAt,
			&i.DeliveredAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.AutoCompleteAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SellerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueDeliveredOrders = `-- name: ListDueDeliveredOrders :many
SELECT id, checkout_id, buyer_id, seller_id, status, escrow_state, subtotal_pesewas, delivery_fee_pesewas, base_pesewas, commission_rate_bps, commission_pesewas, refunded_pesewas, delivery_method, delivery_address, delivery_region, delivery_district, recipient_name, recipient_phone, tracking_ref, paid_at, accepted_at, shipped_at, delivered_at, completed_at, cancelled_at, auto_complete_at, created_at, updated_at FROM orders
WHERE status = 'delivered' AND auto_complete_at <= $1
ORDER BY auto_complete_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListDueDeliveredOrdersParams struct {
	AutoCompleteAt *time.Time
	Limit          int32
}

// Delivered orders past their auto-complete deadline, for the sweep to finish.
// The open-dispute exclusion lives in the sweep's per-order check under the
// row lock, so a dispute opened mid-sweep is still honoured.
func (q *Queries) ListDueDeliveredOrders(ctx context.Context, arg ListDueDeliveredOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listDueDeliveredOrders, arg.AutoCompleteAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CheckoutID,
			&i.BuyerID,
			&i.SellerID,
			&i.Status,
			&i.EscrowState,
			&i.SubtotalPesewas,
			&i.DeliveryFeePesewas,
			&i.BasePesewas,
			&i.CommissionRateBps,
			&i.CommissionPesewas,
			&i.RefundedPesewas,
			&i.DeliveryMethod,
			&i.DeliveryAddress,
			&i.DeliveryRegion,
			&i.DeliveryDistrict,
			&i.RecipientName,
			&i.RecipientPhone,
			&i.TrackingRef,
			&i.PaidAt,
			&i.AcceptedAt,
			&i.ShippedAt,
			&i.DeliveredAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.AutoCompleteAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredPendingCheckouts = `-- name: ListExpiredPendingCheckouts :many
SELECT id, buyer_id, idempotency_key, request_hash, base_pesewas, processing_fee_pesewas, charge_pesewas, payment_id, status, expires_at, created_at, updated_at FROM checkouts
WHERE status = 'pending_payment' AND expires_at <= $1
ORDER BY expires_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListExpiredPendingCheckoutsParams struct {
	ExpiresAt time.Time
	Limit     int32
}

// Unpaid checkouts past their window, in a deterministic order so the sweep
// behaves the same on every run. SKIP LOCKED keeps concurrent sweeps from
// fighting over the same checkout.
func (q *Queries) ListExpiredPendingCheckouts(ctx context.Context, arg ListExpiredPendingCheckoutsParams) ([]Checkout, error) {
	rows, err := q.db.Query(ctx, listExpiredPendingCheckouts, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Checkout{}
	for rows.Next() {
		var i Checkout
		if err := rows.Scan(
			&i.ID,
			&i.BuyerID,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.BasePesewas,
			&i.ProcessingFeePesewas,
			&i.ChargePesewas,
			&i.PaymentID,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderEvents = `-- name: ListOrderEvents :many
SELECT id, order_id, from_status, to_status, actor_type, actor_id, note, created_at FROM order_events WHERE order_id = $1 ORDER BY id
`

func (q *Queries) ListOrderEvents(ctx context.Context, orderID uuid.UUID) ([]OrderEvent, error) {
	rows, err := q.db.Query(ctx, listOrderEvents, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderEvent{}
	for rows.Next() {
		var i OrderEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ActorType,
			&i.ActorID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByCheckout = `-- name: ListOrderItemsByCheckout :many
SELECT oi.id, oi.order_id, oi.listing_id, oi.title, oi.unit, oi.unit_price_pesewas, oi.quantity, oi.line_total_pesewas FROM order_items oi
JOIN orders o ON o.id = oi.order_id
WHERE o.checkout_id = $1
ORDER BY oi.listing_id
`

// The stock a checkout reserved, for restoring it exactly on expiry or
// provider failure. Ordered by listing id, the same order used to reserve.
func (q *Queries) ListOrderItemsByCheckout(ctx context.Context, checkoutID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByCheckout, checkoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ListingID,
			&i.Title,
			&i.Unit,
			&i.UnitPricePesewas,
			&i.Quantity,
			&i.LineTotalPesewas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrder = `-- name: ListOrderItemsByOrder :many
SELECT id, order_id, listing_id, title, unit, unit_price_pesewas, quantity, line_total_pesewas FROM order_items WHERE order_id = $1 ORDER BY listing_id
`

func (q *Queries) ListOrderItemsByOrder(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ListingID,
			&i.Title,
			&i.Unit,
			&i.UnitPricePesewas,
			&i.Quantity,
			&i.LineTotalPesewas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByBuyer = `-- name: ListOrdersByBuyer :many
SELECT o.id, o.checkout_id, o.buyer_id, o.seller_id, o.status, o.escrow_state, o.subtotal_pesewas, o.delivery_fee_pesewas, o.base_pesewas, o.commission_rate_bps, o.commission_pesewas, o.refunded_pesewas, o.delivery_method, o.delivery_address, o.delivery_region, o.delivery_district, o.recipient_name, o.recipient_phone, o.tracking_ref, o.paid_at, o.accepted_at, o.shipped_at, o.delivered_at, o.completed_at, o.cancelled_at, o.auto_complete_at, o.created_at, o.updated_at, sp.business_name AS seller_name
FROM orders o
JOIN seller_profiles sp ON sp.user_id = o.seller_id
WHERE o.buyer_id = $1 AND ($2::text IS NULL OR o.status = $2)
ORDER BY o.created_at DESC
LIMIT $4 OFFSET $3
`

type ListOrdersByBuyerParams struct {
	BuyerID uuid.UUID
	Status  *string
	Offset  int32
	Limit   int32
}

type ListOrdersByBuyerRow struct {
	ID                 uuid.UUID
	CheckoutID         uuid.UUID
	BuyerID            uuid.UUID
	SellerID           uuid.UUID
	Status             string
	EscrowState        string
	SubtotalPesewas    int64
	DeliveryFeePesewas int64
	BasePesewas        int64
	CommissionRateBps  int32
	CommissionPesewas  int64
	RefundedPesewas    int64
	DeliveryMethod     string
	DeliveryAddress    *string
	DeliveryRegion     *string
	DeliveryDistrict   *string
	RecipientName      *string
	RecipientPhone     *string
	TrackingRef        *string
	PaidAt             *time.Time
	AcceptedAt         *time.Time
	ShippedAt          *time.Time
	DeliveredAt        *time.Time
	CompletedAt        *time.Time
	CancelledAt        *time.Time
	AutoCompleteAt     *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	SellerName         string
}

func (q *Queries) ListOrdersByBuyer(ctx context.Context, arg ListOrdersByBuyerParams) ([]ListOrdersByBuyerRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByBuyer,
		arg.BuyerID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersByBuyerRow{}
	for rows.Next() {
		var i ListOrdersByBuyerRow
		if err := rows.Scan(
			&i.ID,
			&i.CheckoutID,
			&i.BuyerID,
			&i.SellerID,
			&i.Status,
			&i.EscrowState,
			&i.SubtotalPesewas,
			&i.DeliveryFeePesewas,
			&i.BasePesewas,
			&i.CommissionRateBps,
			&i.CommissionPesewas,
			&i.RefundedPesewas,
			&i.DeliveryMethod,
			&i.DeliveryAddress,
			&i.DeliveryRegion,
			&i.DeliveryDistrict,
			&i.RecipientName,
			&i.RecipientPhone,
			&i.TrackingRef,
			&i.PaidAt,
			&i.AcceptedAt,
			&i.ShippedAt,
			&i.DeliveredAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.AutoCompleteAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SellerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByCheckout = `-- name: ListOrdersByCheckout :many
SELECT id, checkout_id, buyer_id, seller_id, status, escrow_state, subtotal_pesewas, delivery_fee_pesewas, base_pesewas, commission_rate_bps, commission_pesewas, refunded_pesewas, delivery_method, delivery_address, delivery_region, delivery_district, recipient_name, recipient_phone, tracking_ref, paid_at, accepted_at, shipped_at, delivered_at, completed_at, cancelled_at, auto_complete_at, created_at, updated_at FROM orders WHERE checkout_id = $1 ORDER BY seller_id
`

// Deterministic seller order, matching how the checkout created them.
func (q *Queries) ListOrdersByCheckout(ctx context.Context, checkoutID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByCheckout, checkoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CheckoutID,
			&i.BuyerID,
			&i.SellerID,
			&i.Status,
			&i.EscrowState,
			&i.SubtotalPesewas,
			&i.DeliveryFeePesewas,
			&i.BasePesewas,
			&i.CommissionRateBps,
			&i.CommissionPesewas,
			&i.RefundedPesewas,
			&i.DeliveryMethod,
			&i.DeliveryAddress,
			&i.DeliveryRegion,
			&i.DeliveryDistrict,
			&i.RecipientName,
			&i.RecipientPhone,
			&i.TrackingRef,
			&i.PaidAt,
			&i.AcceptedAt,
			&i.ShippedAt,
			&i.DeliveredAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.AutoCompleteAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersBySeller = `-- name: ListOrdersBySeller :many
SELECT o.id, o.checkout_id, o.buyer_id, o.seller_id, o.status, o.escrow_state, o.subtotal_pesewas, o.delivery_fee_pesewas, o.base_pesewas, o.commission_rate_bps, o.commission_pesewas, o.refunded_pesewas, o.delivery_method, o.delivery_address, o.delivery_region, o.delivery_district, o.recipient_name, o.recipient_phone, o.tracking_ref, o.paid_at, o.accepted_at, o.shipped_at, o.delivered_at, o.completed_at, o.cancelled_at, o.auto_complete_at, o.created_at, o.updated_at, sp.business_name AS seller_name
FROM orders o
JOIN seller_profiles sp ON sp.user_id = o.seller_id
WHERE o.seller_id = $1 AND ($2::text IS NULL OR o.status = $2)
ORDER BY o.created_at DESC
LIMIT $4 OFFSET $3
`

type ListOrdersBySellerParams struct {
	SellerID uuid.UUID
	Status   *string
	Offset   int32
	Limit    int32
}

type ListOrdersBySellerRow struct {
	ID                 uuid.UUID
	CheckoutID         uuid.UUID
	BuyerID            uuid.UUID
	SellerID           uuid.UUID
	Status             string
	EscrowState        string
	SubtotalPesewas    int64
	DeliveryFeePesewas int64
	BasePesewas        int64
	CommissionRateBps  int32
	CommissionPesewas  int64
	RefundedPesewas    int64
	DeliveryMethod     string
	DeliveryAddress    *string
	DeliveryRegion     *string
	DeliveryDistrict   *string
	RecipientName      *string
	RecipientPhone     *string
	TrackingRef        *string
	PaidAt             *time.Time
	AcceptedAt         *time.Time
	ShippedAt          *time.Time
	DeliveredAt        *time.Time
	CompletedAt        *time.Time
	CancelledAt        *time.Time
	AutoCompleteAt     *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	SellerName         string
}

func (q *Queries) ListOrdersBySeller(ctx context.Context, arg ListOrdersBySellerParams) ([]ListOrdersBySellerRow, error) {
	rows, err := q.db.Query(ctx, listOrdersBySeller,
		arg.SellerID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersBySellerRow{}
	for rows.Next() {
		var i ListOrdersBySellerRow
		if err := rows.Scan(
			&i.ID,
			&i.CheckoutID,
			&i.BuyerID,
			&i.SellerID,
			&i.Status,
			&i.EscrowState,
			&i.SubtotalPesewas,
			&i.DeliveryFeePesewas,
			&i.BasePesewas,
			&i.CommissionRateBps,
			&i.CommissionPesewas,
			&i.RefundedPesewas,
			&i.DeliveryMethod,
			&i.DeliveryAddress,
			&i.DeliveryRegion,
			&i.DeliveryDistrict,
			&i.RecipientName,
			&i.RecipientPhone,
			&i.TrackingRef,
			&i.PaidAt,
			&i.AcceptedAt,
			&i.ShippedAt,
			&i.DeliveredAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.AutoCompleteAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SellerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnacceptedPaidOrders = `-- name: ListUnacceptedPaidOrders :many
SELECT id, checkout_id, buyer_id, seller_id, status, escrow_state, subtotal_pesewas, delivery_fee_pesewas, base_pesewas, commission_rate_bps, commission_pesewas, refunded_pesewas, delivery_method, delivery_address, delivery_region, delivery_district, recipient_name, recipient_phone, tracking_ref, paid_at, accepted_at, shipped_at, delivered_at, completed_at, cancelled_at, auto_complete_at, created_at, updated_at FROM orders
WHERE status = 'paid' AND paid_at <= $1
ORDER BY paid_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListUnacceptedPaidOrdersParams struct {
	PaidAt *time.Time
	Limit  int32
}

// Orders whose seller has not accepted within the timeout window, in a
// deterministic order. SKIP LOCKED keeps concurrent sweeps from fighting.
func (q *Queries) ListUnacceptedPaidOrders(ctx context.Context, arg ListUnacceptedPaidOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listUnacceptedPaidOrders, arg.PaidAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CheckoutID,
			&i.BuyerID,
			&i.SellerID,
			&i.Status,
			&i.EscrowState,
			&i.SubtotalPesewas,
			&i.DeliveryFeePesewas,
			&i.BasePesewas,
			&i.CommissionRateBps,
			&i.CommissionPesewas,
			&i.RefundedPesewas,
			&i.DeliveryMethod,
			&i.DeliveryAddress,
			&i.DeliveryRegion,
			&i.DeliveryDistrict,
			&i.RecipientName,
			&i.RecipientPhone,
			&i.TrackingRef,
			&i.PaidAt,
			&i.AcceptedAt,
			&i.ShippedAt,
			&i.DeliveredAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.AutoCompleteAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveListingStock = `-- name: ReserveListingStock :execrows
UPDATE listings SET quantity_available = quantity_available - $2
WHERE id = $1 AND quantity_available >= $2
`

type ReserveListingStockParams struct {
	ID                uuid.UUID
	QuantityAvailable int32
}

// Atomically decrements stock only while enough remains. Zero affected rows is
// ErrInsufficientStock; the caller's transaction rolls back.
func (q *Queries) ReserveListingStock(ctx context.Context, arg ReserveListingStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, reserveListingStock, arg.ID, arg.QuantityAvailable)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreListingStock = `-- name: RestoreListingStock :exec
UPDATE listings SET quantity_available = quantity_available + $2 WHERE id = $1
`

type RestoreListingStockParams struct {
	ID                uuid.UUID
	QuantityAvailable int32
}

// The exact inverse of a reservation, from the stored order items rather than
// the request, so a restored checkout can never drift.
func (q *Queries) RestoreListingStock(ctx context.Context, arg RestoreListingStockParams) error {
	_, err := q.db.Exec(ctx, restoreListingStock, arg.ID, arg.QuantityAvailable)
	return err
}

const setCheckoutPayment = `-- name: SetCheckoutPayment :exec
UPDATE checkouts SET payment_id = $2 WHERE id = $1
`

type SetCheckoutPaymentParams struct {
	ID        uuid.UUID
	PaymentID pgtype.UUID
}

func (q *Queries) SetCheckoutPayment(ctx context.Context, arg SetCheckoutPaymentParams) error {
	_, err := q.db.Exec(ctx, setCheckoutPayment, arg.ID, arg.PaymentID)
	return err
}

const setCheckoutStatus = `-- name: SetCheckoutStatus :exec
UPDATE checkouts SET status = $2 WHERE id = $1 AND status = $3
`

type SetCheckoutStatusParams struct {
	ID       uuid.UUID
	Status   string
	Status_2 string
}

func (q *Queries) SetCheckoutStatus(ctx context.Context, arg SetCheckoutStatusParams) error {
	_, err := q.db.Exec(ctx, setCheckoutStatus, arg.ID, arg.Status, arg.Status_2)
	return err
}

const setOrderAcceptedAt = `-- name: SetOrderAcceptedAt :exec
UPDATE orders SET accepted_at = $2 WHERE id = $1 AND status = 'accepted'
`

type SetOrderAcceptedAtParams struct {
	ID         uuid.UUID
	AcceptedAt *time.Time
}

func (q *Queries) SetOrderAcceptedAt(ctx context.Context, arg SetOrderAcceptedAtParams) error {
	_, err := q.db.Exec(ctx, setOrderAcceptedAt, arg.ID, arg.AcceptedAt)
	return err
}

const setOrderCancelledAt = `-- name: SetOrderCancelledAt :exec
UPDATE orders SET cancelled_at = $2 WHERE id = $1 AND status = 'cancelled'
`

type SetOrderCancelledAtParams struct {
	ID          uuid.UUID
	CancelledAt *time.Time
}

func (q *Queries) SetOrderCancelledAt(ctx context.Context, arg SetOrderCancelledAtParams) error {
	_, err := q.db.Exec(ctx, setOrderCancelledAt, arg.ID, arg.CancelledAt)
	return err
}

const setOrderCompletedAt = `-- name: SetOrderCompletedAt :exec
UPDATE orders SET completed_at = $2 WHERE id = $1 AND status = 'completed'
`

type SetOrderCompletedAtParams struct {
	ID          uuid.UUID
	CompletedAt *time.Time
}

func (q *Queries) SetOrderCompletedAt(ctx context.Context, arg SetOrderCompletedAtParams) error {
	_, err := q.db.Exec(ctx, setOrderCompletedAt, arg.ID, arg.CompletedAt)
	return err
}

const setOrderDeliveredAt = `-- name: SetOrderDeliveredAt :exec
UPDATE orders SET delivered_at = $2, auto_complete_at = $3
WHERE id = $1 AND status = 'delivered'
`

type SetOrderDeliveredAtParams struct {
	ID             uuid.UUID
	DeliveredAt    *time.Time
	AutoCompleteAt *time.Time
}

// The auto-complete clock starts at delivery (DOMAIN §3: 3 days).
func (q *Queries) SetOrderDeliveredAt(ctx context.Context, arg SetOrderDeliveredAtParams) error {
	_, err := q.db.Exec(ctx, setOrderDeliveredAt, arg.ID, arg.DeliveredAt, arg.AutoCompleteAt)
	return err
}

const setOrderEscrowState = `-- name: SetOrderEscrowState :exec
UPDATE orders SET escrow_state = $2 WHERE id = $1
`

type SetOrderEscrowStateParams struct {
	ID          uuid.UUID
	EscrowState string
}

func (q *Queries) SetOrderEscrowState(ctx context.Context, arg SetOrderEscrowStateParams) error {
	_, err := q.db.Exec(ctx, setOrderEscrowState, arg.ID, arg.EscrowState)
	return err
}

const setOrderPaid = `-- name: SetOrderPaid :exec
UPDATE orders SET escrow_state = 'held', paid_at = $2 WHERE id = $1 AND status = 'paid'
`

type SetOrderPaidParams struct {
	ID     uuid.UUID
	PaidAt *time.Time
}

func (q *Queries) SetOrderPaid(ctx context.Context, arg SetOrderPaidParams) error {
	_, err := q.db.Exec(ctx, setOrderPaid, arg.ID, arg.PaidAt)
	return err
}

const setOrderShipped = `-- name: SetOrderShipped :exec
UPDATE orders SET shipped_at = $2, tracking_ref = COALESCE($3, tracking_ref)
WHERE id = $1 AND status = 'shipped'
`

type SetOrderShippedParams struct {
	ID          uuid.UUID
	ShippedAt   *time.Time
	TrackingRef *string
}

func (q *Queries) SetOrderShipped(ctx context.Context, arg SetOrderShippedParams) error {
	_, err := q.db.Exec(ctx, setOrderShipped, arg.ID, arg.ShippedAt, arg.TrackingRef)
	return err
}

const setOrderStatus = `-- name: SetOrderStatus :one
UPDATE orders SET status = $2 WHERE id = $1 AND status = $3
RETURNING id, checkout_id, buyer_id, seller_id, status, escrow_state, subtotal_pesewas, delivery_fee_pesewas, base_pesewas, commission_rate_bps, commission_pesewas, refunded_pesewas, delivery_method, delivery_address, delivery_region, delivery_district, recipient_name, recipient_phone, tracking_ref, paid_at, accepted_at, shipped_at, delivered_at, completed_at, cancelled_at, auto_complete_at, created_at, updated_at
`

type SetOrderStatusParams struct {
	ID       uuid.UUID
	Status   string
	Status_2 string
}

// Transition's status write. Only the target status's timestamp column moves;
// escrow_state is the caller's to set, because it depends on why the order
// moved. Returns no row when the current status differs, which Transition
// treats as a lost race rather than a silent no-op.
func (q *Queries) SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, setOrderStatus, arg.ID, arg.Status, arg.Status_2)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.BuyerID,
		&i.SellerID,
		&i.Status,
		&i.EscrowState,
		&i.SubtotalPesewas,
		&i.DeliveryFeePesewas,
		&i.BasePesewas,
		&i.CommissionRateBps,
		&i.CommissionPesewas,
		&i.RefundedPesewas,
		&i.DeliveryMethod,
		&i.DeliveryAddress,
		&i.DeliveryRegion,
		&i.DeliveryDistrict,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.TrackingRef,
		&i.PaidAt,
		&i.AcceptedAt,
		&i.ShippedAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.AutoCompleteAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
