// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const completeWebhookEvent = `-- name: CompleteWebhookEvent :exec
UPDATE webhook_events SET processed_at = now(), outcome = $2 WHERE id = $1
`

type CompleteWebhookEventParams struct {
	ID      int64
	Outcome *string
}

func (q *Queries) CompleteWebhookEvent(ctx context.Context, arg CompleteWebhookEventParams) error {
	_, err := q.db.Exec(ctx, completeWebhookEvent, arg.ID, arg.Outcome)
	return err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, reference, user_id, purpose, purpose_ref, base_pesewas, processing_fee_pesewas, charge_pesewas, currency, status, paystack_fee_pesewas, channel, authorization_url, paid_at, failure_reason, created_at, updated_at, metadata FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.UserID,
		&i.Purpose,
		&i.PurposeRef,
		&i.BasePesewas,
		&i.ProcessingFeePesewas,
		&i.ChargePesewas,
		&i.Currency,
		&i.Status,
		&i.PaystackFeePesewas,
		&i.Channel,
		&i.AuthorizationUrl,
		&i.PaidAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getPaymentByReference = `-- name: GetPaymentByReference :one
SELECT id, reference, user_id, purpose, purpose_ref, base_pesewas, processing_fee_pesewas, charge_pesewas, currency, status, paystack_fee_pesewas, channel, authorization_url, paid_at, failure_reason, created_at, updated_at, metadata FROM payments WHERE reference = $1
`

func (q *Queries) GetPaymentByReference(ctx context.Context, reference string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByReference, reference)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.UserID,
		&i.Purpose,
		&i.PurposeRef,
		&i.BasePesewas,
		&i.ProcessingFeePesewas,
		&i.ChargePesewas,
		&i.Currency,
		&i.Status,
		&i.PaystackFeePesewas,
		&i.Channel,
		&i.AuthorizationUrl,
		&i.PaidAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getPaymentByReferenceForUpdate = `-- name: GetPaymentByReferenceForUpdate :one
SELECT id, reference, user_id, purpose, purpose_ref, base_pesewas, processing_fee_pesewas, charge_pesewas, currency, status, paystack_fee_pesewas, channel, authorization_url, paid_at, failure_reason, created_at, updated_at, metadata FROM payments WHERE reference = $1 FOR UPDATE
`

// Row-locked. Two webhook deliveries for the same reference must not both
// settle the payment, so the handler settles it under this lock.
func (q *Queries) GetPaymentByReferenceForUpdate(ctx context.Context, reference string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByReferenceForUpdate, reference)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.UserID,
		&i.Purpose,
		&i.PurposeRef,
		&i.BasePesewas,
		&i.ProcessingFeePesewas,
		&i.ChargePesewas,
		&i.Currency,
		&i.Status,
		&i.PaystackFeePesewas,
		&i.Channel,
		&i.AuthorizationUrl,
		&i.PaidAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getPaymentsByPurposeRef = `-- name: GetPaymentsByPurposeRef :many
SELECT id, reference, user_id, purpose, purpose_ref, base_pesewas, processing_fee_pesewas, charge_pesewas, currency, status, paystack_fee_pesewas, channel, authorization_url, paid_at, failure_reason, created_at, updated_at, metadata FROM payments WHERE purpose = $1 AND purpose_ref = $2
ORDER BY created_at DESC
`

type GetPaymentsByPurposeRefParams struct {
	Purpose    string
	PurposeRef string
}

// A buyer retrying after a failed attempt needs to find the earlier rows.
func (q *Queries) GetPaymentsByPurposeRef(ctx context.Context, arg GetPaymentsByPurposeRefParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, getPaymentsByPurposeRef, arg.Purpose, arg.PurposeRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.UserID,
			&i.Purpose,
			&i.PurposeRef,
			&i.BasePesewas,
			&i.ProcessingFeePesewas,
			&i.ChargePesewas,
			&i.Currency,
			&i.Status,
			&i.PaystackFeePesewas,
			&i.Channel,
			&i.AuthorizationUrl,
			&i.PaidAt,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO payments (reference, user_id, purpose, purpose_ref, base_pesewas,
                      processing_fee_pesewas, charge_pesewas, currency, status, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'GHS', 'pending', $8)
RETURNING id, reference, user_id, purpose, purpose_ref, base_pesewas, processing_fee_pesewas, charge_pesewas, currency, status, paystack_fee_pesewas, channel, authorization_url, paid_at, failure_reason, created_at, updated_at, metadata
`

type InsertPaymentParams struct {
	Reference            string
	UserID               uuid.UUID
	Purpose              string
	PurposeRef           string
	BasePesewas          int64
	ProcessingFeePesewas int64
	ChargePesewas        int64
	Metadata             []byte
}

// A pending payment, before Paystack is called. The gross-up is computed by
// the caller from internal/money and the CHECK on charge_pesewas enforces it.
func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, insertPayment,
		arg.Reference,
		arg.UserID,
		arg.Purpose,
		arg.PurposeRef,
		arg.BasePesewas,
		arg.ProcessingFeePesewas,
		arg.ChargePesewas,
		arg.Metadata,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.UserID,
		&i.Purpose,
		&i.PurposeRef,
		&i.BasePesewas,
		&i.ProcessingFeePesewas,
		&i.ChargePesewas,
		&i.Currency,
		&i.Status,
		&i.PaystackFeePesewas,
		&i.Channel,
		&i.AuthorizationUrl,
		&i.PaidAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const insertWebhookEvent = `-- name: InsertWebhookEvent :one
INSERT INTO webhook_events (provider, event_key, event_type, payload)
VALUES ($1, $2, $3, $4)
ON CONFLICT (provider, event_key) DO NOTHING
RETURNING id, provider, event_key, event_type, payload, received_at, processed_at, outcome
`

type InsertWebhookEventParams struct {
	Provider  string
	EventKey  string
	EventType string
	Payload   []byte
}

// Returns no row when (provider, event_key) already exists: that is a replay,
// and the caller answers 200 without dispatching anything.
func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, insertWebhookEvent,
		arg.Provider,
		arg.EventKey,
		arg.EventType,
		arg.Payload,
	)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.EventKey,
		&i.EventType,
		&i.Payload,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.Outcome,
	)
	return i, err
}

const markPaymentAbandoned = `-- name: MarkPaymentAbandoned :one
UPDATE payments
SET status = 'abandoned', failure_reason = $2
WHERE id = $1 AND status = 'pending'
RETURNING id, reference, user_id, purpose, purpose_ref, base_pesewas, processing_fee_pesewas, charge_pesewas, currency, status, paystack_fee_pesewas, channel, authorization_url, paid_at, failure_reason, created_at, updated_at, metadata
`

type MarkPaymentAbandonedParams struct {
	ID            uuid.UUID
	FailureReason *string
}

func (q *Queries) MarkPaymentAbandoned(ctx context.Context, arg MarkPaymentAbandonedParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentAbandoned, arg.ID, arg.FailureReason)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.UserID,
		&i.Purpose,
		&i.PurposeRef,
		&i.BasePesewas,
		&i.ProcessingFeePesewas,
		&i.ChargePesewas,
		&i.Currency,
		&i.Status,
		&i.PaystackFeePesewas,
		&i.Channel,
		&i.AuthorizationUrl,
		&i.PaidAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const markPaymentFailed = `-- name: MarkPaymentFailed :one
UPDATE payments
SET status = 'failed', failure_reason = $2
WHERE id = $1 AND status = 'pending'
RETURNING id, reference, user_id, purpose, purpose_ref, base_pesewas, processing_fee_pesewas, charge_pesewas, currency, status, paystack_fee_pesewas, channel, authorization_url, paid_at, failure_reason, created_at, updated_at, metadata
`

type MarkPaymentFailedParams struct {
	ID            uuid.UUID
	FailureReason *string
}

func (q *Queries) MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentFailed, arg.ID, arg.FailureReason)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.UserID,
		&i.Purpose,
		&i.PurposeRef,
		&i.BasePesewas,
		&i.ProcessingFeePesewas,
		&i.ChargePesewas,
		&i.Currency,
		&i.Status,
		&i.PaystackFeePesewas,
		&i.Channel,
		&i.AuthorizationUrl,
		&i.PaidAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const setPaymentAuthorizationURL = `-- name: SetPaymentAuthorizationURL :one
UPDATE payments SET authorization_url = $2 WHERE id = $1
RETURNING id, reference, user_id, purpose, purpose_ref, base_pesewas, processing_fee_pesewas, charge_pesewas, currency, status, paystack_fee_pesewas, channel, authorization_url, paid_at, failure_reason, created_at, updated_at, metadata
`

type SetPaymentAuthorizationURLParams struct {
	ID               uuid.UUID
	AuthorizationUrl *string
}

// Stored after InitializeTransaction, which happens outside the insert's
// transaction: the provider call must never hold a database transaction open.
func (q *Queries) SetPaymentAuthorizationURL(ctx context.Context, arg SetPaymentAuthorizationURLParams) (Payment, error) {
	row := q.db.QueryRow(ctx, setPaymentAuthorizationURL, arg.ID, arg.AuthorizationUrl)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.UserID,
		&i.Purpose,
		&i.PurposeRef,
		&i.BasePesewas,
		&i.ProcessingFeePesewas,
		&i.ChargePesewas,
		&i.Currency,
		&i.Status,
		&i.PaystackFeePesewas,
		&i.Channel,
		&i.AuthorizationUrl,
		&i.PaidAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const settlePaymentSuccess = `-- name: SettlePaymentSuccess :one
UPDATE payments
SET status = 'success',
    paid_at = $2,
    channel = $3,
    paystack_fee_pesewas = $4,
    failure_reason = NULL
WHERE id = $1 AND status IN ('pending', 'abandoned')
RETURNING id, reference, user_id, purpose, purpose_ref, base_pesewas, processing_fee_pesewas, charge_pesewas, currency, status, paystack_fee_pesewas, channel, authorization_url, paid_at, failure_reason, created_at, updated_at, metadata
`

type SettlePaymentSuccessParams struct {
	ID                 uuid.UUID
	PaidAt             *time.Time
	Channel            *string
	PaystackFeePesewas *int64
}

// The single writer of success. It fires from pending, or from abandoned when
// the buyer paid just before the checkout expired and the webhook arrived
// just after: the expiry sweep guessed no charge would come, and the money
// proved it wrong. From any other state it is a no-op that returns no row.
func (q *Queries) SettlePaymentSuccess(ctx context.Context, arg SettlePaymentSuccessParams) (Payment, error) {
	row := q.db.QueryRow(ctx, settlePaymentSuccess,
		arg.ID,
		arg.PaidAt,
		arg.Channel,
		arg.PaystackFeePesewas,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.UserID,
		&i.Purpose,
		&i.PurposeRef,
		&i.BasePesewas,
		&i.ProcessingFeePesewas,
		&i.ChargePesewas,
		&i.Currency,
		&i.Status,
		&i.PaystackFeePesewas,
		&i.Channel,
		&i.AuthorizationUrl,
		&i.PaidAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}
