// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payouts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPayoutAccountBySeller = `-- name: GetPayoutAccountBySeller :one
SELECT seller_id, type, bank_code, bank_name, account_number_enc, account_number_mask, account_name, recipient_code, status, verified_at, cooldown_until, created_at, updated_at FROM seller_payout_accounts WHERE seller_id = $1
`

// The seller's current payout account, if they set one.
func (q *Queries) GetPayoutAccountBySeller(ctx context.Context, sellerID uuid.UUID) (SellerPayoutAccount, error) {
	row := q.db.QueryRow(ctx, getPayoutAccountBySeller, sellerID)
	var i SellerPayoutAccount
	err := row.Scan(
		&i.SellerID,
		&i.Type,
		&i.BankCode,
		&i.BankName,
		&i.AccountNumberEnc,
		&i.AccountNumberMask,
		&i.AccountName,
		&i.RecipientCode,
		&i.Status,
		&i.VerifiedAt,
		&i.CooldownUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPayoutAccountVerified = `-- name: SetPayoutAccountVerified :one
UPDATE seller_payout_accounts
SET status = 'verified', verified_at = $2
WHERE seller_id = $1 AND status = 'needs_review'
RETURNING seller_id, type, bank_code, bank_name, account_number_enc, account_number_mask, account_name, recipient_code, status, verified_at, cooldown_until, created_at, updated_at
`

type SetPayoutAccountVerifiedParams struct {
	SellerID   uuid.UUID
	VerifiedAt *time.Time
}

// An admin approves a needs_review account. Returns no row unless the
// account is waiting for review: the caller treats that as "cannot approve".
func (q *Queries) SetPayoutAccountVerified(ctx context.Context, arg SetPayoutAccountVerifiedParams) (SellerPayoutAccount, error) {
	row := q.db.QueryRow(ctx, setPayoutAccountVerified, arg.SellerID, arg.VerifiedAt)
	var i SellerPayoutAccount
	err := row.Scan(
		&i.SellerID,
		&i.Type,
		&i.BankCode,
		&i.BankName,
		&i.AccountNumberEnc,
		&i.AccountNumberMask,
		&i.AccountName,
		&i.RecipientCode,
		&i.Status,
		&i.VerifiedAt,
		&i.CooldownUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPayoutAccount = `-- name: UpsertPayoutAccount :one
INSERT INTO seller_payout_accounts (seller_id, type, bank_code, bank_name,
  account_number_enc, account_number_mask, account_name, recipient_code,
  status, verified_at, cooldown_until)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (seller_id) DO UPDATE SET
  type = EXCLUDED.type, bank_code = EXCLUDED.bank_code, bank_name = EXCLUDED.bank_name,
  account_number_enc = EXCLUDED.account_number_enc, account_number_mask = EXCLUDED.account_number_mask,
  account_name = EXCLUDED.account_name, recipient_code = EXCLUDED.recipient_code,
  status = EXCLUDED.status, verified_at = EXCLUDED.verified_at, cooldown_until = EXCLUDED.cooldown_until
RETURNING seller_id, type, bank_code, bank_name, account_number_enc, account_number_mask, account_name, recipient_code, status, verified_at, cooldown_until, created_at, updated_at
`

type UpsertPayoutAccountParams struct {
	SellerID          uuid.UUID
	Type              string
	BankCode          string
	BankName          string
	AccountNumberEnc  string
	AccountNumberMask string
	AccountName       string
	RecipientCode     string
	Status            string
	VerifiedAt        *time.Time
	CooldownUntil     *time.Time
}

// Records the resolved account. On a repeat setup the row already exists:
// the caller sets cooldown_until (now + 48h) itself, and passes NULL for a
// first setup.
func (q *Queries) UpsertPayoutAccount(ctx context.Context, arg UpsertPayoutAccountParams) (SellerPayoutAccount, error) {
	row := q.db.QueryRow(ctx, upsertPayoutAccount,
		arg.SellerID,
		arg.Type,
		arg.BankCode,
		arg.BankName,
		arg.AccountNumberEnc,
		arg.AccountNumberMask,
		arg.AccountName,
		arg.RecipientCode,
		arg.Status,
		arg.VerifiedAt,
		arg.CooldownUntil,
	)
	var i SellerPayoutAccount
	err := row.Scan(
		&i.SellerID,
		&i.Type,
		&i.BankCode,
		&i.BankName,
		&i.AccountNumberEnc,
		&i.AccountNumberMask,
		&i.AccountName,
		&i.RecipientCode,
		&i.Status,
		&i.VerifiedAt,
		&i.CooldownUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
