// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: promotions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const endActiveListingPromotions = `-- name: EndActiveListingPromotions :exec
UPDATE listing_promotions
SET ends_at = GREATEST($2, starts_at + INTERVAL '1 microsecond')
WHERE listing_id = $1 AND starts_at <= $2 AND ends_at > $2
`

type EndActiveListingPromotionsParams struct {
	ListingID uuid.UUID
	EndsAt    time.Time
}

// Forfeit the remaining time on every currently active promotion when a higher
// tier replaces it. The table requires ends_at > starts_at, even for a row
// being replaced at the instant it started, so an immediate replacement ends
// one microsecond after its start rather than exactly at the replacement time.
func (q *Queries) EndActiveListingPromotions(ctx context.Context, arg EndActiveListingPromotionsParams) error {
	_, err := q.db.Exec(ctx, endActiveListingPromotions, arg.ListingID, arg.EndsAt)
	return err
}

const getActiveListingPromotionForUpdate = `-- name: GetActiveListingPromotionForUpdate :one
SELECT id, listing_id, seller_id, tier, tier_rank, starts_at, ends_at, created_at, credits_spent FROM listing_promotions
WHERE listing_id = $1 AND starts_at <= $2 AND ends_at > $2
ORDER BY tier_rank DESC, ends_at DESC
LIMIT 1
FOR UPDATE
`

type GetActiveListingPromotionForUpdateParams struct {
	ListingID uuid.UUID
	StartsAt  time.Time
}

// The currently effective promotion, locked so two applications cannot both
// conclude that the same row is active. When rankings overlap after a
// replacement bug, the highest rank wins and the latest expiry breaks the tie.
func (q *Queries) GetActiveListingPromotionForUpdate(ctx context.Context, arg GetActiveListingPromotionForUpdateParams) (ListingPromotion, error) {
	row := q.db.QueryRow(ctx, getActiveListingPromotionForUpdate, arg.ListingID, arg.StartsAt)
	var i ListingPromotion
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.SellerID,
		&i.Tier,
		&i.TierRank,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.CreditsSpent,
	)
	return i, err
}

const getPromotionConfig = `-- name: GetPromotionConfig :one
SELECT tier, name, price_pesewas, credits, duration_days, tier_rank, featured, description, features, sort_order, is_active, updated_at FROM promotion_configs WHERE tier = $1
`

func (q *Queries) GetPromotionConfig(ctx context.Context, tier string) (PromotionConfig, error) {
	row := q.db.QueryRow(ctx, getPromotionConfig, tier)
	var i PromotionConfig
	err := row.Scan(
		&i.Tier,
		&i.Name,
		&i.PricePesewas,
		&i.Credits,
		&i.DurationDays,
		&i.TierRank,
		&i.Featured,
		&i.Description,
		&i.Features,
		&i.SortOrder,
		&i.IsActive,
		&i.UpdatedAt,
	)
	return i, err
}

const insertListingPromotion = `-- name: InsertListingPromotion :one
INSERT INTO listing_promotions (listing_id, seller_id, tier, tier_rank, starts_at, ends_at, credits_spent)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, listing_id, seller_id, tier, tier_rank, starts_at, ends_at, created_at, credits_spent
`

type InsertListingPromotionParams struct {
	ListingID    uuid.UUID
	SellerID     uuid.UUID
	Tier         string
	TierRank     int32
	StartsAt     time.Time
	EndsAt       time.Time
	CreditsSpent int32
}

// A promotion application always inserts a row. A higher tier replaces an
// active promotion by ending that row first; the replacement row is the only
// one active from the replacement time onward.
func (q *Queries) InsertListingPromotion(ctx context.Context, arg InsertListingPromotionParams) (ListingPromotion, error) {
	row := q.db.QueryRow(ctx, insertListingPromotion,
		arg.ListingID,
		arg.SellerID,
		arg.Tier,
		arg.TierRank,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreditsSpent,
	)
	var i ListingPromotion
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.SellerID,
		&i.Tier,
		&i.TierRank,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.CreditsSpent,
	)
	return i, err
}

const listActivePromotionConfigs = `-- name: ListActivePromotionConfigs :many
SELECT tier, name, price_pesewas, credits, duration_days, tier_rank, featured, description, features, sort_order, is_active, updated_at FROM promotion_configs WHERE is_active ORDER BY sort_order, tier
`

// The public package list, in display order.
func (q *Queries) ListActivePromotionConfigs(ctx context.Context) ([]PromotionConfig, error) {
	rows, err := q.db.Query(ctx, listActivePromotionConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromotionConfig{}
	for rows.Next() {
		var i PromotionConfig
		if err := rows.Scan(
			&i.Tier,
			&i.Name,
			&i.PricePesewas,
			&i.Credits,
			&i.DurationDays,
			&i.TierRank,
			&i.Featured,
			&i.Description,
			&i.Features,
			&i.SortOrder,
			&i.IsActive,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListingPromotions = `-- name: ListListingPromotions :many
SELECT id, listing_id, seller_id, tier, tier_rank, starts_at, ends_at, created_at, credits_spent FROM listing_promotions
WHERE listing_id = $1
ORDER BY starts_at DESC, created_at DESC
`

// One listing's promotion history, newest effective window first.
func (q *Queries) ListListingPromotions(ctx context.Context, listingID uuid.UUID) ([]ListingPromotion, error) {
	rows, err := q.db.Query(ctx, listListingPromotions, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListingPromotion{}
	for rows.Next() {
		var i ListingPromotion
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.SellerID,
			&i.Tier,
			&i.TierRank,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.CreditsSpent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPromotionCredits = `-- name: LockPromotionCredits :one
SELECT pg_advisory_xact_lock(hashtext('promo:' || $1::text)) AS locked
`

// Serializes one buyer's credit balance changes for the transaction. The
// ledger keeps no mutable balance row to lock, so the advisory lock is the
// concurrency control DOMAIN §5.3.5 requires.
func (q *Queries) LockPromotionCredits(ctx context.Context, dollar_1 string) (interface{}, error) {
	row := q.db.QueryRow(ctx, lockPromotionCredits, dollar_1)
	var locked interface{}
	err := row.Scan(&locked)
	return locked, err
}

const upsertPromotionConfig = `-- name: UpsertPromotionConfig :one
INSERT INTO promotion_configs (tier, name, price_pesewas, credits, duration_days,
                               tier_rank, featured, description, features, sort_order, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (tier) DO UPDATE SET
  name = EXCLUDED.name, price_pesewas = EXCLUDED.price_pesewas, credits = EXCLUDED.credits,
  duration_days = EXCLUDED.duration_days, tier_rank = EXCLUDED.tier_rank, featured = EXCLUDED.featured,
  description = EXCLUDED.description, features = EXCLUDED.features, sort_order = EXCLUDED.sort_order,
  is_active = EXCLUDED.is_active, updated_at = now()
WHERE promotion_configs.name IS DISTINCT FROM EXCLUDED.name
   OR promotion_configs.price_pesewas IS DISTINCT FROM EXCLUDED.price_pesewas
   OR promotion_configs.credits IS DISTINCT FROM EXCLUDED.credits
   OR promotion_configs.duration_days IS DISTINCT FROM EXCLUDED.duration_days
   OR promotion_configs.tier_rank IS DISTINCT FROM EXCLUDED.tier_rank
   OR promotion_configs.featured IS DISTINCT FROM EXCLUDED.featured
   OR promotion_configs.description IS DISTINCT FROM EXCLUDED.description
   OR promotion_configs.features IS DISTINCT FROM EXCLUDED.features
   OR promotion_configs.sort_order IS DISTINCT FROM EXCLUDED.sort_order
   OR promotion_configs.is_active IS DISTINCT FROM EXCLUDED.is_active
RETURNING tier, name, price_pesewas, credits, duration_days, tier_rank, featured, description, features, sort_order, is_active, updated_at
`

type UpsertPromotionConfigParams struct {
	Tier         string
	Name         string
	PricePesewas int64
	Credits      int32
	DurationDays int32
	TierRank     int32
	Featured     bool
	Description  string
	Features     []string
	SortOrder    int32
	IsActive     bool
}

// Seed upsert: updates only when something changed (the WHERE guard keeps a
// repeat run from touching updated_at). Returns no row when unchanged.
func (q *Queries) UpsertPromotionConfig(ctx context.Context, arg UpsertPromotionConfigParams) (PromotionConfig, error) {
	row := q.db.QueryRow(ctx, upsertPromotionConfig,
		arg.Tier,
		arg.Name,
		arg.PricePesewas,
		arg.Credits,
		arg.DurationDays,
		arg.TierRank,
		arg.Featured,
		arg.Description,
		arg.Features,
		arg.SortOrder,
		arg.IsActive,
	)
	var i PromotionConfig
	err := row.Scan(
		&i.Tier,
		&i.Name,
		&i.PricePesewas,
		&i.Credits,
		&i.DurationDays,
		&i.TierRank,
		&i.Featured,
		&i.Description,
		&i.Features,
		&i.SortOrder,
		&i.IsActive,
		&i.UpdatedAt,
	)
	return i, err
}
