// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Marks the object attached, but only while it is still pending.
	AttachMediaObject(ctx context.Context, id uuid.UUID) (MediaObject, error)
	CompleteWebhookEvent(ctx context.Context, arg CompleteWebhookEventParams) error
	// A listing's category must be a leaf (or a parent with no children).
	CountCategoryChildren(ctx context.Context, parentID pgtype.UUID) (int64, error)
	CountListingImages(ctx context.Context, listingID uuid.UUID) (int64, error)
	CountSearchListings(ctx context.Context, arg CountSearchListingsParams) (int64, error)
	CountSellerListings(ctx context.Context, arg CountSellerListingsParams) (int64, error)
	CountSellerProfilesByStatus(ctx context.Context, verificationStatus string) (int64, error)
	DeleteAttribute(ctx context.Context, arg DeleteAttributeParams) (uuid.UUID, error)
	DeleteListing(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	DeleteListingAttributes(ctx context.Context, listingID uuid.UUID) error
	DeleteListingImages(ctx context.Context, listingID uuid.UUID) error
	DeleteMediaObject(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	// The expiry sweep: active listings past their expiry become expired.
	ExpireDueListings(ctx context.Context, expiresAt *time.Time) ([]uuid.UUID, error)
	GetCategoryAttribute(ctx context.Context, arg GetCategoryAttributeParams) (CategoryAttribute, error)
	GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetListingByID(ctx context.Context, id uuid.UUID) (Listing, error)
	GetListingByIDForUpdate(ctx context.Context, id uuid.UUID) (Listing, error)
	GetListingBySlug(ctx context.Context, slug string) (Listing, error)
	// The contact reveal. Carries the listing's seller and state as well as the
	// two opt-in flags, so the handler can tell "your own listing" (403) from
	// "not browsable" (404) and answer in one round trip. phone_e164 and
	// whatsapp_e164 are the seller's own values: they leave the building only
	// when the matching show_* flag is true.
	GetListingContactDetails(ctx context.Context, id uuid.UUID) (GetListingContactDetailsRow, error)
	GetMediaObject(ctx context.Context, id uuid.UUID) (MediaObject, error)
	GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error)
	GetPaymentByReference(ctx context.Context, reference string) (Payment, error)
	// Row-locked. Two webhook deliveries for the same reference must not both
	// settle the payment, so the handler settles it under this lock.
	GetPaymentByReferenceForUpdate(ctx context.Context, reference string) (Payment, error)
	// A buyer retrying after a failed attempt needs to find the earlier rows.
	GetPaymentsByPurposeRef(ctx context.Context, arg GetPaymentsByPurposeRefParams) ([]Payment, error)
	// One listing with its category, its active promotion and the seller's safe
	// profile fields. Never selects contact or identity data. The caller decides
	// whether the listing is browsable.
	GetPublicListingBySlug(ctx context.Context, arg GetPublicListingBySlugParams) (GetPublicListingBySlugRow, error)
	// Narrow projection for the public endpoint: never selects id_number_enc.
	GetPublicSeller(ctx context.Context, userID uuid.UUID) (GetPublicSellerRow, error)
	GetSellerProfile(ctx context.Context, userID uuid.UUID) (SellerProfile, error)
	GetSellerProfileForUpdate(ctx context.Context, userID uuid.UUID) (SellerProfile, error)
	GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	IncrementListingContactCount(ctx context.Context, id uuid.UUID) error
	IncrementListingViewCount(ctx context.Context, id uuid.UUID) error
	// Returns no row when the key is taken on this category (409).
	InsertAttribute(ctx context.Context, arg InsertAttributeParams) (CategoryAttribute, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error)
	// Returns no row when the slug is taken (callers map that to 409).
	InsertCategory(ctx context.Context, arg InsertCategoryParams) (Category, error)
	InsertListing(ctx context.Context, arg InsertListingParams) (Listing, error)
	InsertListingAttribute(ctx context.Context, arg InsertListingAttributeParams) error
	InsertListingImage(ctx context.Context, arg InsertListingImageParams) error
	InsertMediaObject(ctx context.Context, arg InsertMediaObjectParams) (MediaObject, error)
	// A pending payment, before Paystack is called. The gross-up is computed by
	// the caller from internal/money and the CHECK on charge_pesewas enforces it.
	InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error)
	// Returns no row if a concurrent request created the user first.
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	// Returns no row when (provider, event_key) already exists: that is a replay,
	// and the caller answers 200 without dispatching anything.
	InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (WebhookEvent, error)
	ListActiveCategories(ctx context.Context) ([]Category, error)
	ListAttributesByCategory(ctx context.Context, categoryID uuid.UUID) ([]CategoryAttribute, error)
	// A category filter on a parent slug must include its children (DOMAIN §9);
	// on a child slug it returns just that child.
	ListCategoryAndChildIDs(ctx context.Context, slug string) ([]uuid.UUID, error)
	// Installed Postgres extensions; used by tests to assert migration 000001.
	ListExtensions(ctx context.Context) ([]string, error)
	ListListingAttributes(ctx context.Context, listingID uuid.UUID) ([]ListListingAttributesRow, error)
	// Read-only join so the owner's view can carry each object's key (and hence
	// its public URL).
	ListListingImages(ctx context.Context, listingID uuid.UUID) ([]ListListingImagesRow, error)
	// Cleanup sweep: pending rows older than the cutoff, oldest first.
	ListPendingMediaBefore(ctx context.Context, arg ListPendingMediaBeforeParams) ([]MediaObject, error)
	ListSellerListings(ctx context.Context, arg ListSellerListingsParams) ([]Listing, error)
	// Admin review queue: oldest submission first.
	ListSellerProfilesByStatus(ctx context.Context, arg ListSellerProfilesByStatusParams) ([]ListSellerProfilesByStatusRow, error)
	// Several accounts may share an email (no account linking in v1).
	ListUsersByEmail(ctx context.Context, email *string) ([]User, error)
	MarkPaymentAbandoned(ctx context.Context, arg MarkPaymentAbandonedParams) (Payment, error)
	MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) (Payment, error)
	// Public search (Phase 12). `now` is always passed from the service clock,
	// never SQL now(), so tests are deterministic.
	//
	// Notes:
	//   - websearch_to_tsquery never errors on user input (to_tsquery does), so
	//     it is safe with raw search text.
	//   - The free-text filter coalesces: with no q the condition is TRUE, and
	//     Postgres does not guarantee OR short-circuits, so a NULL tsquery must
	//     not turn the predicate into NULL.
	//   - Promoted listings rank first (highest active tier rank), then the
	//     requested sort. An expired promotion is not active, so it ranks as
	//     unpromoted (DOMAIN §6).
	//
	SearchListings(ctx context.Context, arg SearchListingsParams) ([]SearchListingsRow, error)
	// Only published_at / expires_at are set when they are given (publish sets
	// both; mark-sold and archive leave them alone).
	SetListingStatus(ctx context.Context, arg SetListingStatusParams) (Listing, error)
	// Stored after InitializeTransaction, which happens outside the insert's
	// transaction: the provider call must never hold a database transaction open.
	SetPaymentAuthorizationURL(ctx context.Context, arg SetPaymentAuthorizationURLParams) (Payment, error)
	// Stores a (new) encrypted ID and (re)submits the profile for verification.
	SetSellerIdentity(ctx context.Context, arg SetSellerIdentityParams) (SellerProfile, error)
	// Records an admin verification decision (reviewed_at = now()).
	SetSellerVerification(ctx context.Context, arg SetSellerVerificationParams) (SellerProfile, error)
	SetUserRole(ctx context.Context, arg SetUserRoleParams) (User, error)
	SetUserSellerVerified(ctx context.Context, arg SetUserSellerVerifiedParams) (User, error)
	// The single writer of success. It only fires from pending, so a replay (or a
	// webhook racing the verify fallback) is a no-op that returns no row.
	SettlePaymentSuccess(ctx context.Context, arg SettlePaymentSuccessParams) (Payment, error)
	SlugExists(ctx context.Context, slug string) (bool, error)
	// Mirror Firebase-owned identity fields; only writes when something changed.
	SyncUserIdentity(ctx context.Context, arg SyncUserIdentityParams) (User, error)
	// Scoped to the category: an attribute of another category reads as missing.
	UpdateAttribute(ctx context.Context, arg UpdateAttributeParams) (CategoryAttribute, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	// Every editable field, COALESCE-style: a nil parameter keeps the column.
	UpdateListing(ctx context.Context, arg UpdateListingParams) (Listing, error)
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (User, error)
	// Seed upsert with the same no-change guard as categories.
	UpsertCategoryAttribute(ctx context.Context, arg UpsertCategoryAttributeParams) (CategoryAttribute, error)
	// Seed upsert: updates only when something changed (the WHERE guard keeps a
	// repeat run from touching updated_at). Returns no row when unchanged.
	UpsertCategoryBySlug(ctx context.Context, arg UpsertCategoryBySlugParams) (Category, error)
	// Creates the profile or edits its non-identity fields. Identity
	// (id_type/id_number) and verification status are managed separately, so an
	// edit never changes them.
	UpsertSellerProfile(ctx context.Context, arg UpsertSellerProfileParams) (SellerProfile, error)
}

var _ Querier = (*Queries)(nil)
