// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refunds.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addOrderRefundedPesewas = `-- name: AddOrderRefundedPesewas :one
UPDATE orders SET refunded_pesewas = refunded_pesewas + $2 WHERE id = $1
RETURNING id, checkout_id, buyer_id, seller_id, status, escrow_state, subtotal_pesewas, delivery_fee_pesewas, base_pesewas, commission_rate_bps, commission_pesewas, refunded_pesewas, delivery_method, delivery_address, delivery_region, delivery_district, recipient_name, recipient_phone, tracking_ref, paid_at, accepted_at, shipped_at, delivered_at, completed_at, cancelled_at, auto_complete_at, created_at, updated_at
`

type AddOrderRefundedPesewasParams struct {
	ID              uuid.UUID
	RefundedPesewas int64
}

func (q *Queries) AddOrderRefundedPesewas(ctx context.Context, arg AddOrderRefundedPesewasParams) (Order, error) {
	row := q.db.QueryRow(ctx, addOrderRefundedPesewas, arg.ID, arg.RefundedPesewas)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CheckoutID,
		&i.BuyerID,
		&i.SellerID,
		&i.Status,
		&i.EscrowState,
		&i.SubtotalPesewas,
		&i.DeliveryFeePesewas,
		&i.BasePesewas,
		&i.CommissionRateBps,
		&i.CommissionPesewas,
		&i.RefundedPesewas,
		&i.DeliveryMethod,
		&i.DeliveryAddress,
		&i.DeliveryRegion,
		&i.DeliveryDistrict,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.TrackingRef,
		&i.PaidAt,
		&i.AcceptedAt,
		&i.ShippedAt,
		&i.DeliveredAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.AutoCompleteAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentReferenceForOrder = `-- name: GetPaymentReferenceForOrder :one
SELECT p.reference FROM payments p
JOIN checkouts c ON c.payment_id = p.id
JOIN orders o ON o.checkout_id = c.id
WHERE o.id = $1
`

// The reference Paystack refunds against: the order's checkout payment.
func (q *Queries) GetPaymentReferenceForOrder(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getPaymentReferenceForOrder, id)
	var reference string
	err := row.Scan(&reference)
	return reference, err
}

const getRefundForUpdate = `-- name: GetRefundForUpdate :one
SELECT id, order_id, amount_pesewas, reason, status, paystack_refund_id, failure_reason, attempted_at, created_at, updated_at FROM refunds WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetRefundForUpdate(ctx context.Context, id uuid.UUID) (Refund, error) {
	row := q.db.QueryRow(ctx, getRefundForUpdate, id)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AmountPesewas,
		&i.Reason,
		&i.Status,
		&i.PaystackRefundID,
		&i.FailureReason,
		&i.AttemptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefundForUpdateByPaystackRefundID = `-- name: GetRefundForUpdateByPaystackRefundID :one
SELECT id, order_id, amount_pesewas, reason, status, paystack_refund_id, failure_reason, attempted_at, created_at, updated_at FROM refunds WHERE paystack_refund_id = $1 FOR UPDATE
`

// Matches a refund webhook once Paystack's id has been stored by the job.
func (q *Queries) GetRefundForUpdateByPaystackRefundID(ctx context.Context, paystackRefundID *string) (Refund, error) {
	row := q.db.QueryRow(ctx, getRefundForUpdateByPaystackRefundID, paystackRefundID)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AmountPesewas,
		&i.Reason,
		&i.Status,
		&i.PaystackRefundID,
		&i.FailureReason,
		&i.AttemptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRefund = `-- name: InsertRefund :one
INSERT INTO refunds (order_id, amount_pesewas, reason)
VALUES ($1, $2, $3)
ON CONFLICT (order_id) WHERE reason IN ('seller_rejected','buyer_cancelled','seller_timeout','stock_unavailable','dispute_refund')
DO NOTHING
RETURNING id, order_id, amount_pesewas, reason, status, paystack_refund_id, failure_reason, attempted_at, created_at, updated_at
`

type InsertRefundParams struct {
	OrderID       uuid.UUID
	AmountPesewas int64
	Reason        string
}

// Records money owed for an order, inside the transition's own transaction
// (the side effect of a cancellation, or the checkout expiry recovery path).
// Returns no row when a full refund already exists for this order: the
// partial unique index is the idempotency guard, and the caller treats a
// missing row as "already recorded".
func (q *Queries) InsertRefund(ctx context.Context, arg InsertRefundParams) (Refund, error) {
	row := q.db.QueryRow(ctx, insertRefund, arg.OrderID, arg.AmountPesewas, arg.Reason)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AmountPesewas,
		&i.Reason,
		&i.Status,
		&i.PaystackRefundID,
		&i.FailureReason,
		&i.AttemptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInFlightRefundsByReference = `-- name: ListInFlightRefundsByReference :many
SELECT r.id, r.order_id, r.amount_pesewas, r.reason, r.status, r.paystack_refund_id, r.failure_reason, r.attempted_at, r.created_at, r.updated_at FROM refunds r
JOIN orders o ON o.id = r.order_id
JOIN checkouts c ON c.id = o.checkout_id
JOIN payments p ON p.id = c.payment_id
WHERE p.reference = $1 AND r.amount_pesewas = $2 AND r.status IN ('queued','pending')
ORDER BY r.created_at
FOR UPDATE OF r
`

type ListInFlightRefundsByReferenceParams struct {
	Reference     string
	AmountPesewas int64
}

// The webhook fallback match, before a refund's paystack_refund_id is known:
// the order's payment reference plus the refunded amount, restricted to
// refunds still in flight. A multi-seller checkout shares one reference, so
// the caller must only act when exactly one row matches (ADR-0027).
func (q *Queries) ListInFlightRefundsByReference(ctx context.Context, arg ListInFlightRefundsByReferenceParams) ([]Refund, error) {
	rows, err := q.db.Query(ctx, listInFlightRefundsByReference, arg.Reference, arg.AmountPesewas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Refund{}
	for rows.Next() {
		var i Refund
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.AmountPesewas,
			&i.Reason,
			&i.Status,
			&i.PaystackRefundID,
			&i.FailureReason,
			&i.AttemptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefundsByOrder = `-- name: ListRefundsByOrder :many
SELECT id, order_id, amount_pesewas, reason, status, paystack_refund_id, failure_reason, attempted_at, created_at, updated_at FROM refunds WHERE order_id = $1 ORDER BY created_at
`

func (q *Queries) ListRefundsByOrder(ctx context.Context, orderID uuid.UUID) ([]Refund, error) {
	rows, err := q.db.Query(ctx, listRefundsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Refund{}
	for rows.Next() {
		var i Refund
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.AmountPesewas,
			&i.Reason,
			&i.Status,
			&i.PaystackRefundID,
			&i.FailureReason,
			&i.AttemptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paystackRefundIDLinked = `-- name: PaystackRefundIDLinked :one
SELECT EXISTS (SELECT 1 FROM refunds WHERE paystack_refund_id = $1)::bool
`

// Whether a Paystack refund id already belongs to one of our rows, so
// reconciliation never adopts the same Paystack refund twice.
func (q *Queries) PaystackRefundIDLinked(ctx context.Context, paystackRefundID *string) (bool, error) {
	row := q.db.QueryRow(ctx, paystackRefundIDLinked, paystackRefundID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const setRefundFailed = `-- name: SetRefundFailed :exec
UPDATE refunds SET status = 'failed', failure_reason = $2 WHERE id = $1 AND status <> 'processed'
`

type SetRefundFailedParams struct {
	ID            uuid.UUID
	FailureReason *string
}

func (q *Queries) SetRefundFailed(ctx context.Context, arg SetRefundFailedParams) error {
	_, err := q.db.Exec(ctx, setRefundFailed, arg.ID, arg.FailureReason)
	return err
}

const setRefundPaystackID = `-- name: SetRefundPaystackID :exec
UPDATE refunds SET paystack_refund_id = $2 WHERE id = $1
`

type SetRefundPaystackIDParams struct {
	ID               uuid.UUID
	PaystackRefundID *string
}

func (q *Queries) SetRefundPaystackID(ctx context.Context, arg SetRefundPaystackIDParams) error {
	_, err := q.db.Exec(ctx, setRefundPaystackID, arg.ID, arg.PaystackRefundID)
	return err
}

const setRefundPending = `-- name: SetRefundPending :exec
UPDATE refunds SET status = 'pending', attempted_at = $2 WHERE id = $1 AND status = 'queued'
`

type SetRefundPendingParams struct {
	ID          uuid.UUID
	AttemptedAt *time.Time
}

// The job is about to call Paystack: committed before the call, so a crash
// mid-call leaves a pending refund that reconciliation finds, never a queued
// one that a retry would send twice.
func (q *Queries) SetRefundPending(ctx context.Context, arg SetRefundPendingParams) error {
	_, err := q.db.Exec(ctx, setRefundPending, arg.ID, arg.AttemptedAt)
	return err
}

const setRefundProcessed = `-- name: SetRefundProcessed :one
UPDATE refunds SET status = 'processed' WHERE id = $1 AND status <> 'processed'
RETURNING id, order_id, amount_pesewas, reason, status, paystack_refund_id, failure_reason, attempted_at, created_at, updated_at
`

// Returns no row when the refund was already processed: the caller treats
// that as a replay.
func (q *Queries) SetRefundProcessed(ctx context.Context, id uuid.UUID) (Refund, error) {
	row := q.db.QueryRow(ctx, setRefundProcessed, id)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AmountPesewas,
		&i.Reason,
		&i.Status,
		&i.PaystackRefundID,
		&i.FailureReason,
		&i.AttemptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setRefundQueuedForRetry = `-- name: SetRefundQueuedForRetry :exec
UPDATE refunds SET status = 'queued' WHERE id = $1 AND status = 'pending' AND paystack_refund_id IS NULL
`

// Only from pending with no Paystack refund: reconciliation proved Paystack
// holds nothing for this attempt, so sending again cannot double-refund.
func (q *Queries) SetRefundQueuedForRetry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setRefundQueuedForRetry, id)
	return err
}

const setRefundStatus = `-- name: SetRefundStatus :exec
UPDATE refunds SET status = $2 WHERE id = $1 AND status <> 'processed'
`

type SetRefundStatusParams struct {
	ID     uuid.UUID
	Status string
}

// Any status except processed may still move; processed is final, so a
// replayed webhook or a job retry can never reopen a settled refund.
func (q *Queries) SetRefundStatus(ctx context.Context, arg SetRefundStatusParams) error {
	_, err := q.db.Exec(ctx, setRefundStatus, arg.ID, arg.Status)
	return err
}

const sumOutstandingRefundsForOrder = `-- name: SumOutstandingRefundsForOrder :one
SELECT coalesce(sum(amount_pesewas), 0)::bigint FROM refunds
WHERE order_id = $1 AND status <> 'failed'
`

// Every refund that has or may still move money (all but failed ones). New
// refunds must keep this within the order's base.
func (q *Queries) SumOutstandingRefundsForOrder(ctx context.Context, orderID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumOutstandingRefundsForOrder, orderID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
