// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countSearchListings = `-- name: CountSearchListings :one
WITH active_promo AS (
  SELECT DISTINCT ON (listing_id) listing_id, tier, tier_rank
  FROM listing_promotions
  WHERE starts_at <= $1 AND ends_at > $1
  ORDER BY listing_id, tier_rank DESC
)
SELECT count(*)
FROM listings l
JOIN categories c ON c.id = l.category_id
JOIN seller_profiles sp ON sp.user_id = l.seller_id
LEFT JOIN active_promo p ON p.listing_id = l.id
WHERE l.status = 'active' AND l.expires_at > $1
  AND (coalesce($2::text, '') = ''
       OR l.search_vector @@ websearch_to_tsquery('simple', $2)
       OR l.title % $2)
  AND ($3::uuid[] IS NULL OR l.category_id = ANY($3))
  AND ($4::text IS NULL OR l.region = $4)
  AND ($5::text IS NULL OR l.district ILIKE $5)
  AND ($6::bigint IS NULL OR l.price_pesewas >= $6)
  AND ($7::bigint IS NULL OR l.price_pesewas <= $7)
  AND ($8::text IS NULL OR l.item_state = $8)
`

type CountSearchListingsParams struct {
	Now         *time.Time
	Q           *string
	CategoryIds []uuid.UUID
	Region      *string
	District    *string
	MinPrice    *int64
	MaxPrice    *int64
	ItemState   *string
}

func (q *Queries) CountSearchListings(ctx context.Context, arg CountSearchListingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchListings,
		arg.Now,
		arg.Q,
		arg.CategoryIds,
		arg.Region,
		arg.District,
		arg.MinPrice,
		arg.MaxPrice,
		arg.ItemState,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getListingContactDetails = `-- name: GetListingContactDetails :one
SELECT l.seller_id, l.status, l.expires_at,
       u.phone_e164, sp.whatsapp_e164, sp.show_phone, sp.show_whatsapp
FROM listings l
JOIN users u ON u.id = l.seller_id
JOIN seller_profiles sp ON sp.user_id = l.seller_id
WHERE l.id = $1
`

type GetListingContactDetailsRow struct {
	SellerID     uuid.UUID
	Status       string
	ExpiresAt    *time.Time
	PhoneE164    *string
	WhatsappE164 *string
	ShowPhone    bool
	ShowWhatsapp bool
}

// The contact reveal. Carries the listing's seller and state as well as the
// two opt-in flags, so the handler can tell "your own listing" (403) from
// "not browsable" (404) and answer in one round trip. phone_e164 and
// whatsapp_e164 are the seller's own values: they leave the building only
// when the matching show_* flag is true.
func (q *Queries) GetListingContactDetails(ctx context.Context, id uuid.UUID) (GetListingContactDetailsRow, error) {
	row := q.db.QueryRow(ctx, getListingContactDetails, id)
	var i GetListingContactDetailsRow
	err := row.Scan(
		&i.SellerID,
		&i.Status,
		&i.ExpiresAt,
		&i.PhoneE164,
		&i.WhatsappE164,
		&i.ShowPhone,
		&i.ShowWhatsapp,
	)
	return i, err
}

const getPublicListingBySlug = `-- name: GetPublicListingBySlug :one
WITH active_promo AS (
  SELECT DISTINCT ON (listing_id) listing_id, tier
  FROM listing_promotions
  WHERE starts_at <= $2 AND ends_at > $2
  ORDER BY listing_id, tier_rank DESC
)
SELECT l.id, l.seller_id, l.category_id, l.title, l.slug, l.description, l.price_pesewas, l.unit, l.quantity_available, l.min_order_qty, l.is_negotiable, l.item_state, l.status, l.region, l.district, l.area, l.offers_pickup, l.offers_seller_delivery, l.seller_delivery_fee_pesewas, l.published_at, l.expires_at, l.view_count, l.favorite_count, l.contact_count, l.created_at, l.updated_at, l.search_vector, c.slug AS category_slug, c.name AS category_name,
       c.listing_group AS category_group,
       sp.business_name, sp.region AS seller_region, sp.district AS seller_district,
       sp.bio AS seller_bio, (sp.verification_status = 'verified') AS seller_verified,
       u.created_at AS seller_created_at,
       -- A left join yields NULL when nothing is running, so the tier is
       -- coalesced to an empty string: the page reports "not promoted".
       coalesce(p.tier, '') AS promo_tier
FROM listings l
JOIN categories c ON c.id = l.category_id
JOIN seller_profiles sp ON sp.user_id = l.seller_id
JOIN users u ON u.id = l.seller_id
LEFT JOIN active_promo p ON p.listing_id = l.id
WHERE l.slug = $1
`

type GetPublicListingBySlugParams struct {
	Slug     string
	StartsAt time.Time
}

type GetPublicListingBySlugRow struct {
	ID                       uuid.UUID
	SellerID                 uuid.UUID
	CategoryID               uuid.UUID
	Title                    string
	Slug                     string
	Description              string
	PricePesewas             int64
	Unit                     string
	QuantityAvailable        int32
	MinOrderQty              int32
	IsNegotiable             bool
	ItemState                string
	Status                   string
	Region                   string
	District                 string
	Area                     *string
	OffersPickup             bool
	OffersSellerDelivery     bool
	SellerDeliveryFeePesewas *int64
	PublishedAt              *time.Time
	ExpiresAt                *time.Time
	ViewCount                int32
	FavoriteCount            int32
	ContactCount             int32
	CreatedAt                time.Time
	UpdatedAt                time.Time
	SearchVector             interface{}
	CategorySlug             string
	CategoryName             string
	CategoryGroup            *string
	BusinessName             string
	SellerRegion             string
	SellerDistrict           string
	SellerBio                *string
	SellerVerified           bool
	SellerCreatedAt          time.Time
	PromoTier                string
}

// One listing with its category, its active promotion and the seller's safe
// profile fields. Never selects contact or identity data. The caller decides
// whether the listing is browsable.
func (q *Queries) GetPublicListingBySlug(ctx context.Context, arg GetPublicListingBySlugParams) (GetPublicListingBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublicListingBySlug, arg.Slug, arg.StartsAt)
	var i GetPublicListingBySlugRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.PricePesewas,
		&i.Unit,
		&i.QuantityAvailable,
		&i.MinOrderQty,
		&i.IsNegotiable,
		&i.ItemState,
		&i.Status,
		&i.Region,
		&i.District,
		&i.Area,
		&i.OffersPickup,
		&i.OffersSellerDelivery,
		&i.SellerDeliveryFeePesewas,
		&i.PublishedAt,
		&i.ExpiresAt,
		&i.ViewCount,
		&i.FavoriteCount,
		&i.ContactCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
		&i.CategorySlug,
		&i.CategoryName,
		&i.CategoryGroup,
		&i.BusinessName,
		&i.SellerRegion,
		&i.SellerDistrict,
		&i.SellerBio,
		&i.SellerVerified,
		&i.SellerCreatedAt,
		&i.PromoTier,
	)
	return i, err
}

const incrementListingContactCount = `-- name: IncrementListingContactCount :exec
UPDATE listings SET contact_count = contact_count + 1 WHERE id = $1
`

func (q *Queries) IncrementListingContactCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementListingContactCount, id)
	return err
}

const incrementListingViewCount = `-- name: IncrementListingViewCount :exec
UPDATE listings SET view_count = view_count + 1 WHERE id = $1
`

func (q *Queries) IncrementListingViewCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementListingViewCount, id)
	return err
}

const searchListings = `-- name: SearchListings :many
WITH active_promo AS (
  SELECT DISTINCT ON (listing_id) listing_id, tier, tier_rank
  FROM listing_promotions
  WHERE starts_at <= $1 AND ends_at > $1
  ORDER BY listing_id, tier_rank DESC
)
SELECT l.id, l.slug, l.title, l.price_pesewas, l.unit, l.region, l.district, l.item_state,
       l.published_at, c.slug AS category_slug, c.name AS category_name,
       p.tier AS promo_tier, coalesce(p.tier_rank, 0)::int AS promo_rank,
       (SELECT m.key FROM listing_images li JOIN media_objects m ON m.id = li.media_id
         WHERE li.listing_id = l.id ORDER BY li.sort_order LIMIT 1) AS cover_key,
       sp.business_name AS seller_name, (sp.verification_status = 'verified') AS seller_verified
FROM listings l
JOIN categories c ON c.id = l.category_id
JOIN seller_profiles sp ON sp.user_id = l.seller_id
LEFT JOIN active_promo p ON p.listing_id = l.id
WHERE l.status = 'active' AND l.expires_at > $1
  AND (coalesce($2::text, '') = ''
       OR l.search_vector @@ websearch_to_tsquery('simple', $2)
       OR l.title % $2)
  AND ($3::uuid[] IS NULL OR l.category_id = ANY($3))
  AND ($4::text IS NULL OR l.region = $4)
  AND ($5::text IS NULL OR l.district ILIKE $5)
  AND ($6::bigint IS NULL OR l.price_pesewas >= $6)
  AND ($7::bigint IS NULL OR l.price_pesewas <= $7)
  AND ($8::text IS NULL OR l.item_state = $8)
ORDER BY promo_rank DESC,
  CASE WHEN $9 = 'price_asc' THEN l.price_pesewas END ASC,
  CASE WHEN $9 = 'price_desc' THEN l.price_pesewas END DESC,
  CASE WHEN $9 = 'relevance' AND $2::text IS NOT NULL
       THEN ts_rank(l.search_vector, websearch_to_tsquery('simple', $2)) END DESC,
  l.published_at DESC, l.id
LIMIT $11 OFFSET $10
`

type SearchListingsParams struct {
	Now         *time.Time
	Q           *string
	CategoryIds []uuid.UUID
	Region      *string
	District    *string
	MinPrice    *int64
	MaxPrice    *int64
	ItemState   *string
	Sort        interface{}
	Offset      int32
	Limit       int32
}

type SearchListingsRow struct {
	ID             uuid.UUID
	Slug           string
	Title          string
	PricePesewas   int64
	Unit           string
	Region         string
	District       string
	ItemState      string
	PublishedAt    *time.Time
	CategorySlug   string
	CategoryName   string
	PromoTier      *string
	PromoRank      int32
	CoverKey       string
	SellerName     string
	SellerVerified bool
}

// Public search (Phase 12). `now` is always passed from the service clock,
// never SQL now(), so tests are deterministic.
//
// Notes:
//   - websearch_to_tsquery never errors on user input (to_tsquery does), so
//     it is safe with raw search text.
//   - The free-text filter coalesces: with no q the condition is TRUE, and
//     Postgres does not guarantee OR short-circuits, so a NULL tsquery must
//     not turn the predicate into NULL.
//   - Promoted listings rank first (highest active tier rank), then the
//     requested sort. An expired promotion is not active, so it ranks as
//     unpromoted (DOMAIN §6).
func (q *Queries) SearchListings(ctx context.Context, arg SearchListingsParams) ([]SearchListingsRow, error) {
	rows, err := q.db.Query(ctx, searchListings,
		arg.Now,
		arg.Q,
		arg.CategoryIds,
		arg.Region,
		arg.District,
		arg.MinPrice,
		arg.MaxPrice,
		arg.ItemState,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchListingsRow{}
	for rows.Next() {
		var i SearchListingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.PricePesewas,
			&i.Unit,
			&i.Region,
			&i.District,
			&i.ItemState,
			&i.PublishedAt,
			&i.CategorySlug,
			&i.CategoryName,
			&i.PromoTier,
			&i.PromoRank,
			&i.CoverKey,
			&i.SellerName,
			&i.SellerVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
