// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sellers.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSellerProfilesByStatus = `-- name: CountSellerProfilesByStatus :one
SELECT count(*) FROM seller_profiles WHERE verification_status = $1
`

func (q *Queries) CountSellerProfilesByStatus(ctx context.Context, verificationStatus string) (int64, error) {
	row := q.db.QueryRow(ctx, countSellerProfilesByStatus, verificationStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPublicSeller = `-- name: GetPublicSeller :one
SELECT sp.business_name, sp.region, sp.district, sp.bio, sp.verification_status, u.created_at
FROM seller_profiles sp JOIN users u ON u.id = sp.user_id
WHERE sp.user_id = $1
`

type GetPublicSellerRow struct {
	BusinessName       string
	Region             string
	District           string
	Bio                *string
	VerificationStatus string
	CreatedAt          time.Time
}

// Narrow projection for the public endpoint: never selects id_number_enc.
func (q *Queries) GetPublicSeller(ctx context.Context, userID uuid.UUID) (GetPublicSellerRow, error) {
	row := q.db.QueryRow(ctx, getPublicSeller, userID)
	var i GetPublicSellerRow
	err := row.Scan(
		&i.BusinessName,
		&i.Region,
		&i.District,
		&i.Bio,
		&i.VerificationStatus,
		&i.CreatedAt,
	)
	return i, err
}

const getSellerProfile = `-- name: GetSellerProfile :one
SELECT user_id, business_name, region, district, bio, show_phone, show_whatsapp, whatsapp_e164, verification_status, id_type, id_number_enc, id_number_last4, submitted_at, reviewed_at, reviewed_by, rejection_reason, created_at, updated_at FROM seller_profiles WHERE user_id = $1
`

func (q *Queries) GetSellerProfile(ctx context.Context, userID uuid.UUID) (SellerProfile, error) {
	row := q.db.QueryRow(ctx, getSellerProfile, userID)
	var i SellerProfile
	err := row.Scan(
		&i.UserID,
		&i.BusinessName,
		&i.Region,
		&i.District,
		&i.Bio,
		&i.ShowPhone,
		&i.ShowWhatsapp,
		&i.WhatsappE164,
		&i.VerificationStatus,
		&i.IDType,
		&i.IDNumberEnc,
		&i.IDNumberLast4,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSellerProfileForUpdate = `-- name: GetSellerProfileForUpdate :one
SELECT user_id, business_name, region, district, bio, show_phone, show_whatsapp, whatsapp_e164, verification_status, id_type, id_number_enc, id_number_last4, submitted_at, reviewed_at, reviewed_by, rejection_reason, created_at, updated_at FROM seller_profiles WHERE user_id = $1 FOR UPDATE
`

func (q *Queries) GetSellerProfileForUpdate(ctx context.Context, userID uuid.UUID) (SellerProfile, error) {
	row := q.db.QueryRow(ctx, getSellerProfileForUpdate, userID)
	var i SellerProfile
	err := row.Scan(
		&i.UserID,
		&i.BusinessName,
		&i.Region,
		&i.District,
		&i.Bio,
		&i.ShowPhone,
		&i.ShowWhatsapp,
		&i.WhatsappE164,
		&i.VerificationStatus,
		&i.IDType,
		&i.IDNumberEnc,
		&i.IDNumberLast4,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSellerProfilesByStatus = `-- name: ListSellerProfilesByStatus :many
SELECT sp.user_id, sp.business_name, sp.region, sp.district, sp.bio, sp.show_phone, sp.show_whatsapp, sp.whatsapp_e164, sp.verification_status, sp.id_type, sp.id_number_enc, sp.id_number_last4, sp.submitted_at, sp.reviewed_at, sp.reviewed_by, sp.rejection_reason, sp.created_at, sp.updated_at, u.display_name, u.email, u.phone_e164
FROM seller_profiles sp JOIN users u ON u.id = sp.user_id
WHERE sp.verification_status = $1
ORDER BY sp.submitted_at ASC NULLS LAST, sp.created_at ASC
LIMIT $3 OFFSET $2
`

type ListSellerProfilesByStatusParams struct {
	VerificationStatus string
	Offset             int32
	Limit              int32
}

type ListSellerProfilesByStatusRow struct {
	UserID             uuid.UUID
	BusinessName       string
	Region             string
	District           string
	Bio                *string
	ShowPhone          bool
	ShowWhatsapp       bool
	WhatsappE164       *string
	VerificationStatus string
	IDType             *string
	IDNumberEnc        *string
	IDNumberLast4      *string
	SubmittedAt        *time.Time
	ReviewedAt         *time.Time
	ReviewedBy         pgtype.UUID
	RejectionReason    *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DisplayName        *string
	Email              *string
	PhoneE164          *string
}

// Admin review queue: oldest submission first.
func (q *Queries) ListSellerProfilesByStatus(ctx context.Context, arg ListSellerProfilesByStatusParams) ([]ListSellerProfilesByStatusRow, error) {
	rows, err := q.db.Query(ctx, listSellerProfilesByStatus, arg.VerificationStatus, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSellerProfilesByStatusRow{}
	for rows.Next() {
		var i ListSellerProfilesByStatusRow
		if err := rows.Scan(
			&i.UserID,
			&i.BusinessName,
			&i.Region,
			&i.District,
			&i.Bio,
			&i.ShowPhone,
			&i.ShowWhatsapp,
			&i.WhatsappE164,
			&i.VerificationStatus,
			&i.IDType,
			&i.IDNumberEnc,
			&i.IDNumberLast4,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.Email,
			&i.PhoneE164,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSellerIdentity = `-- name: SetSellerIdentity :one
UPDATE seller_profiles
SET id_type = $2, id_number_enc = $3, id_number_last4 = $4,
    verification_status = 'pending', submitted_at = now()
WHERE user_id = $1
RETURNING user_id, business_name, region, district, bio, show_phone, show_whatsapp, whatsapp_e164, verification_status, id_type, id_number_enc, id_number_last4, submitted_at, reviewed_at, reviewed_by, rejection_reason, created_at, updated_at
`

type SetSellerIdentityParams struct {
	UserID        uuid.UUID
	IDType        *string
	IDNumberEnc   *string
	IDNumberLast4 *string
}

// Stores a (new) encrypted ID and (re)submits the profile for verification.
func (q *Queries) SetSellerIdentity(ctx context.Context, arg SetSellerIdentityParams) (SellerProfile, error) {
	row := q.db.QueryRow(ctx, setSellerIdentity,
		arg.UserID,
		arg.IDType,
		arg.IDNumberEnc,
		arg.IDNumberLast4,
	)
	var i SellerProfile
	err := row.Scan(
		&i.UserID,
		&i.BusinessName,
		&i.Region,
		&i.District,
		&i.Bio,
		&i.ShowPhone,
		&i.ShowWhatsapp,
		&i.WhatsappE164,
		&i.VerificationStatus,
		&i.IDType,
		&i.IDNumberEnc,
		&i.IDNumberLast4,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSellerVerification = `-- name: SetSellerVerification :one
UPDATE seller_profiles
SET verification_status = $2, reviewed_at = now(), reviewed_by = $3, rejection_reason = $4
WHERE user_id = $1
RETURNING user_id, business_name, region, district, bio, show_phone, show_whatsapp, whatsapp_e164, verification_status, id_type, id_number_enc, id_number_last4, submitted_at, reviewed_at, reviewed_by, rejection_reason, created_at, updated_at
`

type SetSellerVerificationParams struct {
	UserID             uuid.UUID
	VerificationStatus string
	ReviewedBy         pgtype.UUID
	RejectionReason    *string
}

// Records an admin verification decision (reviewed_at = now()).
func (q *Queries) SetSellerVerification(ctx context.Context, arg SetSellerVerificationParams) (SellerProfile, error) {
	row := q.db.QueryRow(ctx, setSellerVerification,
		arg.UserID,
		arg.VerificationStatus,
		arg.ReviewedBy,
		arg.RejectionReason,
	)
	var i SellerProfile
	err := row.Scan(
		&i.UserID,
		&i.BusinessName,
		&i.Region,
		&i.District,
		&i.Bio,
		&i.ShowPhone,
		&i.ShowWhatsapp,
		&i.WhatsappE164,
		&i.VerificationStatus,
		&i.IDType,
		&i.IDNumberEnc,
		&i.IDNumberLast4,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSellerProfile = `-- name: UpsertSellerProfile :one
INSERT INTO seller_profiles (user_id, business_name, region, district, bio, show_phone, show_whatsapp, whatsapp_e164)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id) DO UPDATE SET
  business_name = EXCLUDED.business_name,
  region = EXCLUDED.region,
  district = EXCLUDED.district,
  bio = EXCLUDED.bio,
  show_phone = EXCLUDED.show_phone,
  show_whatsapp = EXCLUDED.show_whatsapp,
  whatsapp_e164 = EXCLUDED.whatsapp_e164
RETURNING user_id, business_name, region, district, bio, show_phone, show_whatsapp, whatsapp_e164, verification_status, id_type, id_number_enc, id_number_last4, submitted_at, reviewed_at, reviewed_by, rejection_reason, created_at, updated_at
`

type UpsertSellerProfileParams struct {
	UserID       uuid.UUID
	BusinessName string
	Region       string
	District     string
	Bio          *string
	ShowPhone    bool
	ShowWhatsapp bool
	WhatsappE164 *string
}

// Creates the profile or edits its non-identity fields. Identity
// (id_type/id_number) and verification status are managed separately, so an
// edit never changes them.
func (q *Queries) UpsertSellerProfile(ctx context.Context, arg UpsertSellerProfileParams) (SellerProfile, error) {
	row := q.db.QueryRow(ctx, upsertSellerProfile,
		arg.UserID,
		arg.BusinessName,
		arg.Region,
		arg.District,
		arg.Bio,
		arg.ShowPhone,
		arg.ShowWhatsapp,
		arg.WhatsappE164,
	)
	var i SellerProfile
	err := row.Scan(
		&i.UserID,
		&i.BusinessName,
		&i.Region,
		&i.District,
		&i.Bio,
		&i.ShowPhone,
		&i.ShowWhatsapp,
		&i.WhatsappE164,
		&i.VerificationStatus,
		&i.IDType,
		&i.IDNumberEnc,
		&i.IDNumberLast4,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
