// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: supply.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAllSupplyRequests = `-- name: CountAllSupplyRequests :one
SELECT count(*) FROM supply_requests
WHERE ($1::text IS NULL OR status = $1)
`

func (q *Queries) CountAllSupplyRequests(ctx context.Context, status *string) (int64, error) {
	row := q.db.QueryRow(ctx, countAllSupplyRequests, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSupplyRequestsByUser = `-- name: CountSupplyRequestsByUser :one
SELECT count(*) FROM supply_requests
WHERE user_id = $1 AND ($2::text IS NULL OR status = $2)
`

type CountSupplyRequestsByUserParams struct {
	UserID uuid.UUID
	Status *string
}

func (q *Queries) CountSupplyRequestsByUser(ctx context.Context, arg CountSupplyRequestsByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSupplyRequestsByUser, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSupplyCategoryBySlug = `-- name: GetSupplyCategoryBySlug :one
SELECT id, parent_id, name, slug, icon, listing_group, sort_order, is_active, created_at, updated_at FROM categories WHERE slug = $1
`

// Items must name a parent category: children are rejected by the caller.
func (q *Queries) GetSupplyCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getSupplyCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.ListingGroup,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplyRequestByID = `-- name: GetSupplyRequestByID :one
SELECT id, request_number, user_id, delivery_name, delivery_phone, delivery_address, expected_date, notes, status, created_at, updated_at FROM supply_requests WHERE id = $1
`

func (q *Queries) GetSupplyRequestByID(ctx context.Context, id uuid.UUID) (SupplyRequest, error) {
	row := q.db.QueryRow(ctx, getSupplyRequestByID, id)
	var i SupplyRequest
	err := row.Scan(
		&i.ID,
		&i.RequestNumber,
		&i.UserID,
		&i.DeliveryName,
		&i.DeliveryPhone,
		&i.DeliveryAddress,
		&i.ExpectedDate,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplyRequestForUpdate = `-- name: GetSupplyRequestForUpdate :one
SELECT id, request_number, user_id, delivery_name, delivery_phone, delivery_address, expected_date, notes, status, created_at, updated_at FROM supply_requests WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetSupplyRequestForUpdate(ctx context.Context, id uuid.UUID) (SupplyRequest, error) {
	row := q.db.QueryRow(ctx, getSupplyRequestForUpdate, id)
	var i SupplyRequest
	err := row.Scan(
		&i.ID,
		&i.RequestNumber,
		&i.UserID,
		&i.DeliveryName,
		&i.DeliveryPhone,
		&i.DeliveryAddress,
		&i.ExpectedDate,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSupplyRequest = `-- name: InsertSupplyRequest :one
INSERT INTO supply_requests (request_number, user_id, delivery_name, delivery_phone,
  delivery_address, expected_date, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (request_number) DO NOTHING
RETURNING id, request_number, user_id, delivery_name, delivery_phone, delivery_address, expected_date, notes, status, created_at, updated_at
`

type InsertSupplyRequestParams struct {
	RequestNumber   string
	UserID          uuid.UUID
	DeliveryName    *string
	DeliveryPhone   *string
	DeliveryAddress *string
	ExpectedDate    pgtype.Date
	Notes           *string
}

// Records a supply request with its generated number. A number collision
// returns no row (the UNIQUE is the retry signal); anything else errors.
func (q *Queries) InsertSupplyRequest(ctx context.Context, arg InsertSupplyRequestParams) (SupplyRequest, error) {
	row := q.db.QueryRow(ctx, insertSupplyRequest,
		arg.RequestNumber,
		arg.UserID,
		arg.DeliveryName,
		arg.DeliveryPhone,
		arg.DeliveryAddress,
		arg.ExpectedDate,
		arg.Notes,
	)
	var i SupplyRequest
	err := row.Scan(
		&i.ID,
		&i.RequestNumber,
		&i.UserID,
		&i.DeliveryName,
		&i.DeliveryPhone,
		&i.DeliveryAddress,
		&i.ExpectedDate,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSupplyRequestEvent = `-- name: InsertSupplyRequestEvent :exec
INSERT INTO supply_request_events (supply_request_id, from_status, to_status, actor_id, note)
VALUES ($1, $2, $3, $4, $5)
`

type InsertSupplyRequestEventParams struct {
	SupplyRequestID uuid.UUID
	FromStatus      *string
	ToStatus        string
	ActorID         pgtype.UUID
	Note            *string
}

// The append-only transition trail: every move writes exactly one row.
func (q *Queries) InsertSupplyRequestEvent(ctx context.Context, arg InsertSupplyRequestEventParams) error {
	_, err := q.db.Exec(ctx, insertSupplyRequestEvent,
		arg.SupplyRequestID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ActorID,
		arg.Note,
	)
	return err
}

const insertSupplyRequestItem = `-- name: InsertSupplyRequestItem :exec
INSERT INTO supply_request_items (supply_request_id, category_id, product_name, quantity, unit, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSupplyRequestItemParams struct {
	SupplyRequestID uuid.UUID
	CategoryID      uuid.UUID
	ProductName     string
	Quantity        int32
	Unit            string
	SortOrder       int32
}

func (q *Queries) InsertSupplyRequestItem(ctx context.Context, arg InsertSupplyRequestItemParams) error {
	_, err := q.db.Exec(ctx, insertSupplyRequestItem,
		arg.SupplyRequestID,
		arg.CategoryID,
		arg.ProductName,
		arg.Quantity,
		arg.Unit,
		arg.SortOrder,
	)
	return err
}

const listAllSupplyRequests = `-- name: ListAllSupplyRequests :many
SELECT id, request_number, user_id, delivery_name, delivery_phone, delivery_address, expected_date, notes, status, created_at, updated_at FROM supply_requests
WHERE ($1::text IS NULL OR status = $1)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListAllSupplyRequestsParams struct {
	Status *string
	Offset int32
	Limit  int32
}

func (q *Queries) ListAllSupplyRequests(ctx context.Context, arg ListAllSupplyRequestsParams) ([]SupplyRequest, error) {
	rows, err := q.db.Query(ctx, listAllSupplyRequests, arg.Status, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupplyRequest{}
	for rows.Next() {
		var i SupplyRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequestNumber,
			&i.UserID,
			&i.DeliveryName,
			&i.DeliveryPhone,
			&i.DeliveryAddress,
			&i.ExpectedDate,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplyRequestEvents = `-- name: ListSupplyRequestEvents :many
SELECT id, supply_request_id, from_status, to_status, actor_id, note, created_at FROM supply_request_events WHERE supply_request_id = $1 ORDER BY id
`

func (q *Queries) ListSupplyRequestEvents(ctx context.Context, supplyRequestID uuid.UUID) ([]SupplyRequestEvent, error) {
	rows, err := q.db.Query(ctx, listSupplyRequestEvents, supplyRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupplyRequestEvent{}
	for rows.Next() {
		var i SupplyRequestEvent
		if err := rows.Scan(
			&i.ID,
			&i.SupplyRequestID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ActorID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplyRequestItems = `-- name: ListSupplyRequestItems :many
SELECT id, supply_request_id, category_id, product_name, quantity, unit, sort_order FROM supply_request_items WHERE supply_request_id = $1 ORDER BY sort_order
`

func (q *Queries) ListSupplyRequestItems(ctx context.Context, supplyRequestID uuid.UUID) ([]SupplyRequestItem, error) {
	rows, err := q.db.Query(ctx, listSupplyRequestItems, supplyRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupplyRequestItem{}
	for rows.Next() {
		var i SupplyRequestItem
		if err := rows.Scan(
			&i.ID,
			&i.SupplyRequestID,
			&i.CategoryID,
			&i.ProductName,
			&i.Quantity,
			&i.Unit,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplyRequestsByUser = `-- name: ListSupplyRequestsByUser :many
SELECT id, request_number, user_id, delivery_name, delivery_phone, delivery_address, expected_date, notes, status, created_at, updated_at FROM supply_requests
WHERE user_id = $1 AND ($2::text IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListSupplyRequestsByUserParams struct {
	UserID uuid.UUID
	Status *string
	Offset int32
	Limit  int32
}

func (q *Queries) ListSupplyRequestsByUser(ctx context.Context, arg ListSupplyRequestsByUserParams) ([]SupplyRequest, error) {
	rows, err := q.db.Query(ctx, listSupplyRequestsByUser,
		arg.UserID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupplyRequest{}
	for rows.Next() {
		var i SupplyRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequestNumber,
			&i.UserID,
			&i.DeliveryName,
			&i.DeliveryPhone,
			&i.DeliveryAddress,
			&i.ExpectedDate,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSupplyRequestStatus = `-- name: SetSupplyRequestStatus :one
UPDATE supply_requests SET status = $2 WHERE id = $1 AND status = $3
RETURNING id, request_number, user_id, delivery_name, delivery_phone, delivery_address, expected_date, notes, status, created_at, updated_at
`

type SetSupplyRequestStatusParams struct {
	ID       uuid.UUID
	Status   string
	Status_2 string
}

// Moves a request guarded by its current status: no row means the move is
// illegal from where the request actually is.
func (q *Queries) SetSupplyRequestStatus(ctx context.Context, arg SetSupplyRequestStatusParams) (SupplyRequest, error) {
	row := q.db.QueryRow(ctx, setSupplyRequestStatus, arg.ID, arg.Status, arg.Status_2)
	var i SupplyRequest
	err := row.Scan(
		&i.ID,
		&i.RequestNumber,
		&i.UserID,
		&i.DeliveryName,
		&i.DeliveryPhone,
		&i.DeliveryAddress,
		&i.ExpectedDate,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
