// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package db

import (
	"context"
)

const listExtensions = `-- name: ListExtensions :many
SELECT extname::text AS name
FROM pg_catalog.pg_extension
ORDER BY extname
`

// Installed Postgres extensions; used by tests to assert migration 000001.
func (q *Queries) ListExtensions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listExtensions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
