// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, firebase_uid, signup_method, email, email_verified, phone_e164, display_name, role, seller_verified, created_at, updated_at FROM users WHERE firebase_uid = $1
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.SignupMethod,
		&i.Email,
		&i.EmailVerified,
		&i.PhoneE164,
		&i.DisplayName,
		&i.Role,
		&i.SellerVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, firebase_uid, signup_method, email, email_verified, phone_e164, display_name, role, seller_verified, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.SignupMethod,
		&i.Email,
		&i.EmailVerified,
		&i.PhoneE164,
		&i.DisplayName,
		&i.Role,
		&i.SellerVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (firebase_uid, signup_method, email, email_verified, phone_e164, display_name)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (firebase_uid) DO NOTHING
RETURNING id, firebase_uid, signup_method, email, email_verified, phone_e164, display_name, role, seller_verified, created_at, updated_at
`

type InsertUserParams struct {
	FirebaseUid   string
	SignupMethod  string
	Email         *string
	EmailVerified bool
	PhoneE164     *string
	DisplayName   *string
}

// Returns no row if a concurrent request created the user first.
func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.FirebaseUid,
		arg.SignupMethod,
		arg.Email,
		arg.EmailVerified,
		arg.PhoneE164,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.SignupMethod,
		&i.Email,
		&i.EmailVerified,
		&i.PhoneE164,
		&i.DisplayName,
		&i.Role,
		&i.SellerVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersByEmail = `-- name: ListUsersByEmail :many
SELECT id, firebase_uid, signup_method, email, email_verified, phone_e164, display_name, role, seller_verified, created_at, updated_at FROM users WHERE email = $1 ORDER BY created_at
`

// Several accounts may share an email (no account linking in v1).
func (q *Queries) ListUsersByEmail(ctx context.Context, email *string) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirebaseUid,
			&i.SignupMethod,
			&i.Email,
			&i.EmailVerified,
			&i.PhoneE164,
			&i.DisplayName,
			&i.Role,
			&i.SellerVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserRole = `-- name: SetUserRole :one
UPDATE users SET role = $2 WHERE id = $1 RETURNING id, firebase_uid, signup_method, email, email_verified, phone_e164, display_name, role, seller_verified, created_at, updated_at
`

type SetUserRoleParams struct {
	ID   uuid.UUID
	Role string
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.SignupMethod,
		&i.Email,
		&i.EmailVerified,
		&i.PhoneE164,
		&i.DisplayName,
		&i.Role,
		&i.SellerVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserSellerVerified = `-- name: SetUserSellerVerified :one
UPDATE users SET seller_verified = $2 WHERE id = $1 RETURNING id, firebase_uid, signup_method, email, email_verified, phone_e164, display_name, role, seller_verified, created_at, updated_at
`

type SetUserSellerVerifiedParams struct {
	ID             uuid.UUID
	SellerVerified bool
}

func (q *Queries) SetUserSellerVerified(ctx context.Context, arg SetUserSellerVerifiedParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserSellerVerified, arg.ID, arg.SellerVerified)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.SignupMethod,
		&i.Email,
		&i.EmailVerified,
		&i.PhoneE164,
		&i.DisplayName,
		&i.Role,
		&i.SellerVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const syncUserIdentity = `-- name: SyncUserIdentity :one
UPDATE users
SET email = $2, email_verified = $3, phone_e164 = $4
WHERE id = $1
  AND (email IS DISTINCT FROM $2 OR email_verified IS DISTINCT FROM $3 OR phone_e164 IS DISTINCT FROM $4)
RETURNING id, firebase_uid, signup_method, email, email_verified, phone_e164, display_name, role, seller_verified, created_at, updated_at
`

type SyncUserIdentityParams struct {
	ID            uuid.UUID
	Email         *string
	EmailVerified bool
	PhoneE164     *string
}

// Mirror Firebase-owned identity fields; only writes when something changed.
func (q *Queries) SyncUserIdentity(ctx context.Context, arg SyncUserIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, syncUserIdentity,
		arg.ID,
		arg.Email,
		arg.EmailVerified,
		arg.PhoneE164,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.SignupMethod,
		&i.Email,
		&i.EmailVerified,
		&i.PhoneE164,
		&i.DisplayName,
		&i.Role,
		&i.SellerVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :one
UPDATE users SET display_name = $2 WHERE id = $1 RETURNING id, firebase_uid, signup_method, email, email_verified, phone_e164, display_name, role, seller_verified, created_at, updated_at
`

type UpdateUserDisplayNameParams struct {
	ID          uuid.UUID
	DisplayName *string
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.SignupMethod,
		&i.Email,
		&i.EmailVerified,
		&i.PhoneE164,
		&i.DisplayName,
		&i.Role,
		&i.SellerVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
